- NOTICE.txt
- package-lock.json
- package.json
- src/extension.ts
- src/sourcekit-lsp/extension.ts
- src/sourcekit-lsp/inlayHints.ts
- src/sourcekit-lsp/lspExtensions.ts
Copied code straight from apple [repo](https://github.com/apple/sourcekit-lsp/tree/main/Editors/vscode). Keeping identical at the moment just in case they edit their version.
> SourceKit LSP integration

- package.json
- src/PackageWatcher.ts
- src/SwiftContext.ts
- src/SwiftPackage.ts
- src/SwiftTaskProvider.ts
- src/commands.ts
- src/debug.ts
- src/extension.ts
- add CoreLLDB to packageDependencies in `package.json`
- Added command to build `launch.json` based off contents of Package.swift
- Updating Package.swift will run `swift package describe` and update `launch.json` if necessary
> CoreLLDB integration

- Package.swift
- src/FolderContext.ts
- src/PackageWatcher.ts
- src/SwiftOutputChannel.ts
- src/WorkspaceContext.ts
- src/commands.ts
- src/extension.ts
And log everything we do in it. This will give us a useful log for when things go wrong in the wild.
You can find it in the dropdown list of the Output tab. It is called "Swift" funnily enough
> Add Swift Output channel

- src/SwiftTaskProvider.ts
- src/debug.ts
- src/utilities.ts
Add launch.json configs for building release executables and running tests
Did a quick check on Linux and it isn't work just at the moment
> Add building of release/test builds

- package-lock.json
- package.json
- src/FolderContext.ts
- src/WorkspaceContext.ts
- src/debug.ts
- src/utilities.ts
This fixes #63 
It doesn't support cross-compilation, but it does use **DEVELOPER_DIR** and **Info.plist** to find the path to **XCTest.dll**.
> Add debug configuration for tests on Windows.

- CHANGELOG.md
I have assume #57 will be merged
> Additions to CHANGELOG

- README.md
Preparing for the 0.1.0 release
> Update README for relaese

- .vscode/settings.json
- src/FolderContext.ts
- src/PackageDependencyProvider.ts
- src/PackageWatcher.ts
- src/StatusItem.ts
- src/SwiftOutputChannel.ts
- src/SwiftPackage.ts
- src/SwiftTaskProvider.ts
- src/WorkspaceContext.ts
- src/commands.ts
- src/configuration.ts
- src/contextKeys.ts
- src/debug.ts
- src/extension.ts
- src/lldb.ts
- src/test/runTest.ts
- src/test/suite/index.ts
- src/test/suite/utilities.test.ts
- src/utilities.ts
Also applied it to all the typescript files
> Enable prettier on save

- src/SwiftPackage.ts
- src/SwiftTaskProvider.ts
- src/WorkspaceContext.ts
- src/debugger/launch.ts
- src/debugger/lldb.ts
- src/extension.ts
- src/sourcekit-lsp/LanguageClientManager.ts
- src/test/suite/utilities.test.ts
- src/ui/PackageDependencyProvider.ts
Project appeared to build but wasn't
This PR tidies up after my previous tidy
We need CI
> Fixup paths after tidy

- src/FolderContext.ts
- src/WorkspaceContext.ts
> Remove isRootFolder

- package.json
Remove experimental, add swift 5.6 requirement
> Change InlayHints configuration description

- src/WorkspaceContext.ts
When `swift.path` configuration is changed display information popup saying you need to restart the extension and when 'Ok' is pressed restart extension.
> Restart extension when swift.path is changed

- package.json
- src/WorkspaceContext.ts
- src/commands.ts
- src/utilities/tempFolder.ts
Add command that runs swift file through swift interpreter.
If file isn't saved it will save it to a temp file before running
Can you use this as a basic swift playground.
> Add runSingleFile command

- CHANGELOG.md
- CONTRIBUTORS.txt
- README.md
- package-lock.json
- package.json
- Update Readme task and add command section
- Add section for 0.3.0 for changeling
> Readme, Contributors, Changelog updates for v0.3.0

- src/extension.ts
- src/ui/PackageDependencyProvider.ts
This is useful for when you have multiple projects in one workspace
Resolves #165
> Set PackageDependency View title based on current project

- src/sourcekit-lsp/LanguageClientManager.ts
Instead of creating a new LanguageClient every time we move between workspace folders change the workspace folder on the one we have just stopped and restart it.
Main thing this fixes is it stops creating a new `Sourcekit Language Server` output pane. Probably saves on some shutdown and setup code as well.
> Restart instead of creating new LanguageClient

- src/TestExplorer/TestRunner.ts
This fixes an issue where the `onDidTerminateDebugSession` handler was not deleted. This meant with each run of tests a new handler would be added without the previous being deleted.
> bug fix: Dispose of terminateSession handler at end of tests

- src/WorkspaceContext.ts
- src/debugger/launch.ts
- src/toolchain/toolchain.ts
- src/utilities/utilities.ts
- src/utilities/version.ts
Stores details about the current swift toolchain. Collects various functions into one class
> Add SwiftToolchain class

- src/TestExplorer/TestRunner.ts
- src/debugger/launch.ts
This involves invoking CodeLLDB with a custom launch setup. And sending LLDB commands directly
> Fix 5.6 test explorer

- src/TestExplorer/TestRunner.ts
- src/debugger/launch.ts
Fixes test results disappearing
Also add a comment at top of debug console detailing tests being run
> Only output stderr to file on macOS

- CHANGELOG.md
> Changelog changes for 0.4.0

- CHANGELOG.md
Messed up the previous changelog PR. This fixes it
> Changelog 0.4.0 (edit)

- package.json
- src/configuration.ts
- src/debugger/launch.ts
Add option to enable/disable the automatic generation of launch.json configurations
> Add auto-generate launch config setting

- src/TestExplorer/LSPTestDiscovery.ts
Update class TestItem with URL and range from LSP results
> Store class positions/URL from LSP symbols

- src/TestExplorer/TestRunner.ts
And then mark the TestItem as skipped
> Add regex to catch skipped tests

- src/TestExplorer/TestRunner.ts
Extract Linux test search into separate function and use with skipped tests as well.
> Extract Linux test search

- src/TestExplorer/TestRunner.ts
These are all related to running non-debug tests ie not through the debugger
Don't run tests if compile fails
Pass both stderr/stdout to writeStream (doesn't seem to have ordering issues debugger has). Previously didn't pass both in as I was getting weird output order but this only seems to be the case when running inside the debugger.
Catch errors from xctest run and ignore as stderr output is already parsed
> Minor bug fixes for test runner

- CHANGELOG.md
- package-lock.json
- package.json
This is the branch for v0.4.2. It has cherry-picked commits as a couple of the commits on main would require a major (well not patch) release update which I'm not ready for.
> v0.4.2 release

- package.json
- src/BackgroundCompilation.ts
- src/FolderContext.ts
- src/WorkspaceContext.ts
- src/configuration.ts
- src/extension.ts
Adds settings config to run compilation in the background whenever a file is saved. It is currently defaulted to off
> Experimental: Background compilation

- src/SwiftTaskProvider.ts
- src/TestExplorer/TestRunner.ts
- src/utilities/utilities.ts
- test/suite/TemporaryFolder.test.ts
- test/suite/WorkspaceContext.test.ts
- test/suite/utilities.test.ts
- Temporary file test
- ExecFile with streaming test
- Task creation tests
> Adding some more tests

- package.json
Start of break up of settings into sections
> Add settings sub-section Sourcekit-LSP

- package.json
- src/SwiftPackage.ts
- src/SwiftTaskProvider.ts
- src/TestExplorer/TestExplorer.ts
- src/commands.ts
- src/configuration.ts
- src/sourcekit-lsp/LanguageClientManager.ts
- src/toolchain/toolchain.ts
- src/utilities/utilities.ts
- test/suite/WorkspaceContext.test.ts
- More precise output for SDKs;
- Support non-standardized SDK layout on Windows;
- Support custom SDK through configuration.
> Support custom SDK

- src/toolchain/toolchain.ts
XCTest parallel installs the XCTest runtime, and we should dynamically
select the last path component.  The following mapping applies:
i686: bin32
x86_64: bin64
armv7: bin32a
aarch64: bin64a
> toolchain: adjust the path for XCTest

- src/WorkspaceContext.ts
Not sure why I made this was a class
> Change FolderEvent to an enum

- src/sourcekit-lsp/LanguageClientManager.ts
- src/utilities/utilities.ts
- test/suite/utilities.test.ts
This should resolve an issue where swift build needs to do a full rebuild all the time.
> Pass swift build arguments to sourcekit-lsp

- .vscode/launch.json
- assets/test/.vscode/settings.json
- test/fixtures.ts
- test/suite/WorkspaceContext.test.ts
- test/suite/extension.test.ts
- Fix setting workspace folder when running tests from VSCode
- Reset any config settings setup in tests
- Add test for setting swift path
- Add test for adding new FolderContext based on the active text document
> Active folder and settings tests

- src/TestExplorer/TestRunner.ts
When starting tests, set which tests are enqueued. 
When a test starts set it to be started.
When a test passes parse duration from output.
> Test Runner improvements

- src/TestExplorer/TestExplorer.ts
And print "No tests found" error message instead of "Test Discovery Error".
Also if there is an error clear out all previous listed tests
> Catch no test found error

- package.json
- src/SwiftPackage.ts
- src/SwiftPluginTaskProvider.ts
- src/WorkspaceContext.ts
- src/commands.ts
- src/contextKeys.ts
- src/extension.ts
- src/ui/PackageDependencyProvider.ts
This is the start of the swift plugin support. 
It adds a task provider that generates tasks to run swift plugins.
> Swift plugin tasks

- src/toolchain/toolchain.ts
> Fix compatibility with Swift 5.3 and older toolchains

- assets/test/.vscode/tasks.json
- src/SwiftTaskProvider.ts
- test/suite/extension.test.ts
> Add test to read tasks.json

- src/SwiftPackage.ts
- src/ui/PackageDependencyProvider.ts
Fixes #357 
Need to verify this works with older versions of Swift before merging though
> Need to test `path` for local dependencies

- package.json
> Remove runPlugin command

- package.json
This allows them to be set on folders as well as workspaces
> Change settings scope for configuration settings

- package.json
- src/SwiftPackage.ts
- src/SwiftSnippets.ts
- src/WorkspaceContext.ts
- src/commands.ts
- src/contextKeys.ts
- src/debugger/launch.ts
- src/utilities/version.ts
Add support for running/debugging Swift Snippets
> Swift Snippets

- src/TestExplorer/TestRunner.ts
This adds support for parsing multiline errors from XCTest output. This is not 100% accurate as it is not always possible to distinguish between XCTest output and general print output from tests. 
I have also added support for parsing XCTest message from the correct output stream when running tests. MacOS outputs to stderr, Linux output to stdout. Unfortunately I haven't been able to do this for debugging tests as the extracting the output from lldb is complex and so far I've only managed to output it to a file, which is dumped to the log once testing has completed.
> Improve XCTest output parsing

- package-lock.json
- package.json
- src/commands.ts
- src/ui/QuickPick.ts
Uses `runTask` command with a `swift-plugin` filter.
> Add run command plugin command

- src/TestExplorer/TestRunner.ts
> Fix test output parsing,now we use swift test

- package-lock.json
- package.json
> Use @vscode/vsce instead of vsce

- CHANGELOG.md
- package-lock.json
- package.json
Also changed dev-package script to have it's own version number
> Changelog and package.json for 1.0.0

- src/coverage/TestCoverageReport.ts
- Fix file links with spaces
- Fix refresh preview command (was calling wrong command)
> Couple of Coverage Report fixes

- package.json
- src/configuration.ts
- src/sourcekit-lsp/LanguageClientManager.ts
This is mainly a development option, but may be of use to some other people.
> Add option to disable SourceKit-LSP

- src/TestExplorer/TestRunner.ts
This broke the Linux and Windows test explorer
> Remove "/" prefix I added in the last PR

- src/WorkspaceContext.ts
This enables conditional breakpoints
> Set lldb.launch.expressions to native

- src/sourcekit-lsp/LanguageClientManager.ts
This fixes an issue on my Windows image where the LSP server never restarts
> If LSP server shutdown times out still restart it

- src/SwiftTaskProvider.ts
This allows the default build task to be something other than a swift process eg CMake.
The default build task is triggered by the test explorer and the background compilation
> Allow getBuildAllTask() to return non-swift task

- src/TestExplorer/TestRunner.ts
The reason for the custom path was fixed in 5.7
Probably should have done this a while back
> Only use custom Darwin test config on swift 5.6

- test/suite/WorkspaceContext.test.ts
Get rid of remove as it does bad things to test workspace
> Fix WorkspaceContext add/remove test

- package.json
- src/commands.ts
- src/contextKeys.ts
- src/debugger/debugAdapter.ts
Add attach to process command that uses lldb-vscode
> Attach to process command

- package.json
Make it clearer what it is doing
> Changed text for Clean Build to Clean Build Folder

- docker/docker-compose.2204.59.yaml
- docker/docker-compose.2204.main.yaml
Please note this is using jammy and not focal
Also I changed the docker-compose file for main to use jammy as well
@tomerd can you organise this please
> Add docker-compose file for Swift 5.9 CI

- package.json
- src/TestExplorer/TestExplorer.ts
Test discovery can kick off a resolve
> Disable initial test discovery is auto-resolve is disabled

- src/FolderContext.ts
- src/TestExplorer/LSPTestDiscovery.ts
- src/TestExplorer/TestExplorer.ts
- src/WorkspaceContext.ts
And flag that test discovery is needed to be run if a swift file inside a test target has changed.
> Observe changes to swift files in test folders

- CHANGELOG.md
- docker/Dockerfile
- package-lock.json
- package.json
- test/runTest.ts
Updated package.json versions
Also upped the node.js target to v18
This CHANGELOG assumes #680 and #684 are merged
> CHANGELOG for v1.8.0

- .gitignore
- CHANGELOG.md
- package-lock.json
- package.json
- src/SwiftPackage.ts
Support Package.resolved version 3 - needed to support Swift 5.10 packages
> Changes from Release 1.8.1

- .prettierrc.json
- src/LinuxMain.ts
- src/PackageWatcher.ts
- src/TestExplorer/TestRunner.ts
- src/WorkspaceContext.ts
- src/editor/DocumentParser.ts
- src/toolchain/Sanitizer.ts
- src/ui/PackageDependencyProvider.ts
- src/utilities/result.ts
- src/utilities/version.ts
- Update config file to continue with trailing commas
- Constructors are always spread across multiple lines
> Updates from new prettier

- src/commands.ts
- src/debugger/lldb.ts
- src/toolchain/toolchain.ts
It was looking for LLDB in the wrong folder
> Fix attach to process on macOS

- package.json
> Add create swift project button to the explorer

- test/suite/tasks.test.ts
This "Build complete" string hasn't changed
> Fix failing SwiftExecution test

- package.json
- snippets/swift-testing.code-snippets
- snippets/swift.code-snippets
- snippets/xctest.code-snippets
Augment the built in collection of Swift snippets with some common snippets that were not included. Also adds snippets for creating test suites and cases in both XCTest and swift-testing.
> Add Code Snippets

- src/ui/SwiftBuildStatus.ts
Fixes #694
addresses last review comment of PR #794
> Don't quote task name for build status

- src/TestExplorer/TestRunner.ts
#837 fixed this for regular runs, but more work was required for debug runs
> Fix flakey pipe removal for debug runs

- src/debugger/buildConfig.ts
When debugging an XCTest in a project that contains both XCTests and swift-testing tests the `xctest` utility runs both test executables. This results in an empty swift testing test run output being printed to console.
Prevent `xctest` from running the swift-testing binary by setting the `SWIFT_TESTING_ENABLED` environment variable to 0.
> Suppress swift-testing output when debugging XCTests

- src/debugger/buildConfig.ts
> Include additional args in test build configs

- CHANGELOG.md
- package-lock.json
- package.json
CHANGELOG and package.json changes for v1.10.1
> Release 1.10.1

- src/ui/ToolchainSelection.ts
> Improve toolchain error message when swift.path exists in settings

- src/TestExplorer/TestRunner.ts
We were creating the fifo pipe when doing a debugging run whith only XCTests, which is not necessary.
Issue: #852
> Dont create fifo pipe unless there are swift-testing tests

- src/ui/ToolchainSelection.ts
Place the recommended workspace configuration first in the menu.
Issue: #933
> Reorder settings selection

- src/debugger/buildConfig.ts
This fixes the fatalError seen on Windows when attempting to build tests with code coverage enabled. The linker doesn't allow duplicate symbols by default on Windows, while this is OK on macOS/Linux.
Use the `-lldmingw` linker flag to work around this issue.
> Fix linker error when building Windows tests w/ coverage

- .vscode-test.js
- .vscode/launch.json
- CONTRIBUTING.md
- docs/contributor/test-strategy.md
- package-lock.json
- package.json
- test/unit-tests/MockUtils.ts
- test/unit-tests/ui/ReloadExtension.test.ts
- test/unit-tests/ui/SwiftBuildStatus.test.ts
* Propose levels of testing and the test matrix
* Propose a single mocking library to introduce unit testing
* Add test strategy documentation
> Test strategy proposal

- test/suite/testexplorer/TestExplorerIntegration.test.ts
- test/suite/testexplorer/utilities.ts
Fix the assertion string on an `@slow` test that doesn't run in CI.
> Fixup failing `@slow` test

- test/unit-tests/debugger/debugAdapter.test.ts
Add unit test for verifyDebugAdapterExists
Issue: #1023
> Add unit test for verifyDebugAdapterExists

- package.json
- scripts/soundness.sh
> npm script for testing soundness job

- .vscode-test.js
> Disable telemetry and other services when running tests

- README.md
The section outlining what commands are added to the command palette is out of date. Add missing commands with a brief description of their purpose.
> Update available commands in README

- .gitignore
- .mocha-reporter.js
- .vscode-test.js
* Want to be able to archive some results as part of build jobs
> Produce JSON report for archiving by build jobs

- .github/dependabot.yml
Mocha 11 seems to fail, see #1252
> Don't allow major updates of mocha

- test/integration-tests/testexplorer/TestExplorerIntegration.test.ts
- test/integration-tests/testexplorer/utilities.ts
* trying to fix some intermittent timing issues
> Await focus of test explorer 

- assets/test/swift-macro/Package.swift
- test/integration-tests/language/LanguageClientIntegration.test.ts
- test/integration-tests/utilities/lsputilities.ts
* Experimental feature was not getting enabled
* Wait for document to be indexed before proceeding
Issue: #1286
> Fix macro expansion test

- .github/ISSUE_TEMPLATE/test_failure.md
> Add a test failure issue template

- src/toolchain/BuildFlags.ts
> Add packageArgs to swift test/run

- test/integration-tests/testexplorer/TestExplorerIntegration.test.ts
Started failing with the merge of https://github.com/swiftlang/vscode-swift/pull/1381
> Fix failing CodeLLDB swift-testing test

- src/ui/ProjectPanelProvider.ts
And ensure they have a unique ID.
Issue: #1445
> Only show Swift tasks in the Project Panel

- package.json
For completeness, include all supported language versions
> Support all supported swift language versions in swift.scriptSwiftLanguageVersion

- .github/workflows/pull_request.yml
Wasn't hooked up right to run against VSIX and that had the unfortunate side effect of send PR check email early
> Clean up PR GH workflow

- src/WorkspaceContext.ts
- src/extension.ts
- test/integration-tests/tasks/SwiftTaskProvider.test.ts
Match setup of plugin task provider
> Have single instance of task provider

- test/integration-tests/SwiftSnippet.test.ts
Cleanup and add a retry mechanism for continue
> Fix the snippet test

- test/integration-tests/DiagnosticsManager.test.ts
Properly cleanup
cut out LSP dependency
> Simplify diagnostics tests

- .vscode-test.js
- test/integration-tests/ui/ProjectPanelProvider.test.ts
> Try to fix project panel tests

- CHANGELOG.md
- package-lock.json
- package.json
> Start initial changelog for 2.6

- src/utilities/workspace.ts
Use glob approach and exclude those patterns
Issue: #1641
> Exclude folders in `files.exclude` from activating

- .github/PULL_REQUEST_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- Add some tasks that submitter must consider
- Request Issue number and details
- Move to default location suggested by https://stackoverflow.com/a/64367212
> Propose new PR template

- test/integration-tests/tasks/SwiftPluginTaskProvider.test.ts
> Try to renable expectation for plugin output

- CHANGELOG.md
- package-lock.json
- package.json
Describe your changes clearly and use examples if possible
Bumping package version to 2.6.2
> Bump version to 2.6.2

- userdocs/userdocs.docc/Articles/Reference/commands.md
Add documentation for the `Swift: Generate Launch Configurations` command
Issue: #1615
> Generate launch configuration command docs

- README.md
The getting started guide contains helpful additional information that may be useful for first time extension users. Add a link to this in the README.md file.
> Add a link to the getting started guide in README

- CHANGELOG.md
Bump the changelog to finalize the 2.10.0 release
Issue: N/A
> Bump CHANGELOG for 2.10.0 release

- assets/test/.vscode/settings.json
- assets/test/dependencies/Package.swift
- assets/test/targets/Package.swift
- test/integration-tests/commands/dependency.test.ts
- Sometimes compete over lock
Issue: #1867
> Disable LSP for dependency tests
