swiftlang/vscode-swift

package-lock.json
package.json
src/commands.ts

This is probably the operation I do the most often in relation to swift package manager, making it easy of access would be a good thing
I've included the package-lock.json as it has the wrong package name

Add Update Dependencies button to Package Dependencies title bar

---

src/PackageDependencyProvider.ts
src/SwiftPackage.ts
src/extension.ts

This gets the list of local dependencies from `SwiftPackage`. To detect a local dependency, I've checked that it does not have a `requirement`, but does have a `url`. Can we depend on this always being the case?
I've also fixed a small bug in that directories shouldn't have an Open File command attached to them.
As a side note: When does a dependency have a `path` property instead of a `url`? I haven't seen any paths so far.

Get local dependencies from SwiftPackage (fix #30)

---

src/PackageWatcher.ts
src/SwiftTaskProvider.ts
src/commands.ts
src/extension.ts

- Add function `executeTaskAndWait` which runs a task and waits for it to finish.
- Use this function in resolve/UpdateDependencies.
- Add global flags to only allow entry into these functions if they are not already running

Stop multiple resolves running at same time

---

src/WorkspaceContext.ts

Minor code fix. 
```swift
this.observers.forEach(async fn => { await fn(folderContext, 'add'); });
```
runs everything in parallel.
We want to run these serially. So using 
```swift
for (const observer of this.observers) {
await observer(folderContext, 'add');
}
```

Make sure we await for add/remove observers

---

src/FolderContext.ts
src/PackageWatcher.ts
src/SwiftPackage.ts

Currently if a Package.swift fails to load it is as if it doesn't exist
Sometimes we want to know there is a Package.swift but that it failed to load. So I created a `InvalidPackage` class which is returned for a Package.swift that fails to load. `SwiftPackage.contents` can now be one of three thing
- Contents of a valid Package.swift
- `InvalidPackage` meaning a Package.swift was there but failed to load
- null meaning there was no Package.swift
I then added a test `SwiftPackage.foundPackage` which returns true for valid or invalid contents but not `null`
I use this in the PackageWatcher to decide when I should run the resolve task

Add InvalidPackage for package that exists but failed to load

---

src/SwiftTaskProvider.ts

I keep seeing reasons to add more configuration options to `createSwiftTask`. Instead of adding a new function parameter every time I need a new config option. I've create a TaskConfig interface class
I'm not actually using this at the moment but will be in the future

Add TaskConfig to simplify createSwiftTask calls

---

src/FolderContext.ts

We need the configKey.hasPackage to be true for tasks to be enabled. If tasks aren't enabled we no error messages for invalid `Package.swift`

Set config keys on package found instead of package is valid

---

.vscode/extensions.json
.vscode/launch.json
.vscode/tasks.json
.vscodeignore
package-lock.json
package.json

This uses `esbuild` to bundle the extension into a single file. Some notable changes:
* The output of `esbuild` goes into the **dist** folder. Only that file needs to be included in the extension. We can ignore the regular compilation output that goes into **out**.
* Make sure to install the recommended extensions (listed in **.vscode/extensions.json**) as the new one includes a problem matcher for `esbuild`.
* **package.json** still includes the old compilation scripts. Some of them are still used for testing, which relies on regular compilation, not bundling.
With this, the extension now includes only 11 files. The output of `npm run package` says 13 files, but I think that includes directories. In any case, you can check which files are included with `npx vsce ls`.
This fixes #50 and …

Bundle using esbuild

---

src/PackageDependencyProvider.ts
src/SwiftTaskProvider.ts
src/commands.ts

Using task definition `command` and `args` seems to produce inconsistent results. See #65. Instead if you use `Task.name` you get the correct result every time.
I have added static variables for all the standard task names to ensure consistency across the project.

Use Task name to identify tasks

---

src/SwiftTaskProvider.ts

This just adds some build arguments for debugging on Windows as @compnerd suggested.

Add build arguments for debugging on Windows

---

NOTICE.txt
src/SwiftPackage.ts
src/WorkspaceContext.ts
src/extension.ts
src/lldb.ts
src/utilities.ts

Attempts to find the correct version of LLDB for debugging Swift and then suggests to the user they allow it to update their CoreLLDB settings. The code is the same as is used in CoreLLDB's use alternate backend command.
Testing to do:

Setup CoreLLDB Configuration automatically

---

src/lldb.ts

I missed a section of the LLDB config setup. This is causing it to fail setting up correctly when using remote containers.

Fix LLDB config setup

---

src/WorkspaceContext.ts
src/extension.ts

`focus` and `unfocus` events are sent to observers when a file is opened based on which workspace folder the file is in.
If when opening a file it is from a different workspace folder than the previous active file then an `unfocus` event is sent for the previous active workspace folder and a `focus` event is sent for the new workspace folder.
This PR assumes the prettier PR #79 has been merged

Add `focus`, `unfocus` events for workspace folders

---

src/debug.ts

Need to include workspace folder in launch.json `program` field otherwise lldb won't find the executable

Use workspace folder in launch.json program name

---

README.md
docs/README.md
docs/remote-dev.md

Add a new `Documentation` section for adding docs to the extension. This PR starts by adding docs on how to use the extension with VSCode Remote Development.
Resolves #82

Add Remote Development docs

---

src/FolderContext.ts
src/PackageDependencyProvider.ts
src/PackageWatcher.ts
src/SwiftPackage.ts

- Store copy of `Package.resolved` in `SwiftPackage`.
- Update cached copy of `Package.resolved` when file changes.
- Use cached version of `Package.resolved` in PackageDependencyProvider.ts.
Currently PackageDependencyProvider.ts rebuild is triggered off finishing a resolve or update task, eventually I want to add an `update` event for the WorkspaceContext observers which will trigger on Package.resolved being updated and use that to trigger a rebuild.

Cache Package.resolved contents in `SwiftPackage`

---

package.json
src/FolderContext.ts
src/PackageWatcher.ts
src/SwiftTaskProvider.ts
src/commands.ts
src/extension.ts

- Instead of using task provider, generate resolve and update tasks on the fly.
- Make resolve and update commands available in command palette (current only act on first folder, once focus PR is in we can change to active folder)
- Add package watchers for all folders
- Added `executeSwiftTaskAndWait` for running swift command as a task

Multi folder resolve/update tasks

---

src/sourcekit-lsp/LanguageClientManager.ts

`documentSelector` using just single strings is deprecated we should use `DocumentSelector` instead.

Document selector for LSP

---

src/FolderContext.ts
src/PackageDependencyProvider.ts
src/PackageWatcher.ts
src/WorkspaceContext.ts
src/commands.ts
src/extension.ts

- Add `packageUpdated` event for when Package.swift is updated
- Add `resolvedUpdated` event for when Package.resolved is updated
- PackageDependencyProvider now uses a workspace observer to update its contents. Using `focus`, `unfocus` and `resolvedUpdated` events to rebuild the tree.
- Add update/resolve commands to command palette which work on the current workspace folder

Add Package events and use to update dependency view

---

src/FolderContext.ts
src/StatusItem.ts
src/SwiftTaskProvider.ts
src/commands.ts
src/extension.ts

- Added support for StatusItem to be initialised with a string
- Added support for StatusItem to include task folder name if it exists
- Use when loading package (larger packages take time so worthwhile having)
- Also the resolve tasks are awaited on now. Previously they were just left to run so you could resolve multiple folders in parallel but the task management gets all confused if you do that for some reason.

Add Package loading status item

---

package.json
src/SwiftTaskProvider.ts
src/commands.ts

Also add package reset and resolve to dependency view
question: should reset run a resolve immediately after as it completely clears out the `.build` folder

Add reset/clean commands

---

package.json

This adds a `dev-package` "script" that allows for building an
unversioned VSIX for development snapshots.  This allows for use  in out
of band builds meant for testing.

packaging: add support for a `dev-package`

---

src/WorkspaceContext.ts
src/extension.ts
src/test/suite/version.test.ts
src/utilities/version.ts

As features appear in swift we will want to take advantage of them but to do that we need to know what version of swift we are running. This PR adds a version object and extracts the version from the output of `swift --version`.
I've also added tests to ensure the version comparisons are working.
The first use of this will be checking whether we need to restart the LSP server when we add a new file. Currently we need to do this, but when swift 5.6  is released it should no longer be necessary.

Add Version Object for comparing Swift versions

---

package.json
src/FolderContext.ts
src/SwiftPackage.ts
src/SwiftTaskProvider.ts
src/commands.ts
src/ui/PackageDependencyProvider.ts

Added commands
- useLocalDependency
- editDependency
- uneditDependency
- openInWorkspace
Added right click menu to dependency view which use above commands
- Added menu items for remote packages
- Edit Locally: This will create local version of module that can be edited and add it to the workspace.
- Use local version: This will bring up a file dialog so you can choose a local version of the dependency
- Added menu item for local or edited dependency
- Open in Workspace: This will add the dependency folder to the workspace
- Added menu item for edited dependency
- Revert to Original Version: This will revert to the version of the dependency detailed in Package.swift
An edited dependency will have the pencil icon next to it, instead of the archive icon
The extension works out what are …

Edit package menu

---

src/sourcekit-lsp/LanguageClientManager.ts

Swift 5.6 adds support for the LSP server `workspace/didChangeWatchedFiles` message. Until we have this though we need to restart the LSP every time a new file is created/deleted if we want symbol completion to work. 
Had to add a bunch of promises to ensure we aren't restarting the LSP server in the middle of restarting it already.

Restart LSP Server on new file is running Swift 5.5 or lower

---

src/WorkspaceContext.ts
src/extension.ts
src/sourcekit-lsp/LanguageClientManager.ts
src/ui/PackageDependencyProvider.ts

This is mainly being implemented so we can start the LSP server without a workspace folder. LSP server requires a focus event to startup, if you startup with no folders then a focus event is sent with a null folder.
This should fix #127

Allow events to be triggered with a null folder

---

package.json
src/FolderContext.ts
src/SwiftPackage.ts

Previously when trying to get the list of locally edited dependencies, the extension would look into the Packages folder and work out from what was in there what was locally edited. This is not a very stable method as the edit/unedit paths can fail and do not always clean up the Packages folder.
Instead this PR loads the `workspace-state.json` in the `.build` folder. The data in this file is up to date and should be correct. It is an internal file format though so changes could happen to it. It is versioned though.

Workspace state json and edited dependencies

---

package.json
src/FolderContext.ts
src/SwiftPackage.ts
src/SwiftTaskProvider.ts
src/WorkspaceContext.ts
src/commands.ts
src/debugger/launch.ts
src/extension.ts
src/sourcekit-lsp/LanguageClientManager.ts
src/test/suite/SwiftPackage.test.ts
src/test/suite/WorkspaceContext.test.ts
src/ui/PackageDependencyProvider.ts
src/ui/StatusItem.ts

This is part of the process of getting #131 working. Previously FolderContext used WorkspaceFolder to define where the root of the swift package. To support #131 we need to have FolderContext whose root folder is defined by an arbitrary file path (or vscode.Uri).
This change requires 
- adding a `cwd` parameter to tasks to define where the task should be run as we cannot use the workspace folder scope.
- adding `FolderContext.name` to return a user friendly name for the folder
- launch configurations are edited to include the correct path based on the folder uri.
- to get the LSP server working I have to create a temporary `WorkspaceFolder` from the package uri.
I also deleted `executeSwiftTaskAndWait` and `executeShellTaskAndWait` as neither are used.

Replace WorkspaceFolder in FolderContext with a Uri

---

package.json

Make sure edit package commands are not available from the command palette. They should only be available from context menu.
You have to add them to the command palette with a `when` clause set to false

Remove edit package commands from palette

---

package.json
src/FolderContext.ts
src/commands.ts

Store if resolve/update fails. If previous failed but this one is successful then send a package.resolved updated event to ensure UI is updated.

Add Folder error state

---

src/SwiftPackage.ts

`swift package describe --type json` will output any warnings to stdout which interferes with the JSON parsing. This code removes lines from its output until it finds a line starting with "{".

Remove warnings from beginning of swift package describe

---

src/SwiftTaskProvider.ts

Set windows debug options for DWARF debug generation as detailed in #80 
I'm unable to test these options, but they are what @compnerd suggested for DWARF debug output.
The option to do CodeView debug info will be in a different PR. I would rather someone else (with access to a Windows PC) did it though as I cannot test.

Set windows DWARF debug options

---

src/SwiftTaskProvider.ts

Found this useful, when working on the Sendable issues. Kept trying to fix issues from previous builds

Clear terminal window for every new build

---

src/FolderContext.ts
src/TestExplorer/TestExplorer.ts
src/extension.ts
src/ui/SwiftOutputChannel.ts

This is the start of the TestExplorer work. I am going to break it into a number of PRs. This PR contains the basic test discovery. 
Function `discoverTestsInWorkspace` parses the output of `swift test --skip-build --list-test` and then adds/removes TestItems based on the results. This does mean you have the limitation that the project needs built.
Test discovery is run when a project gets focus, or when a build process has just finished.

Add TestExplorer with test discovery

---

src/TestExplorer/TestExplorer.ts
src/TestExplorer/TestRunner.ts
src/debugger/launch.ts

Add ability to run tests discovered in the previous PR #154 
- Builds test configuration
- Run tests
- Use CodeLLDB stdio tag to output result of tests to a file. Unfortunately it doesn't seem possible to output both stdout and stderr to the same file. macOS outputs to both, while non Darwin platforms output to just stdout
- Parse results of tests and flag which TestItems passed/failed
- Non Darwin platforms complicate things slightly by never outputting the test target name, so if two test targets have a test function with the same class and function name it is hard to differentiate them. The only way to do this is if one of them fails. At that point you can work out the test target from the file name which caused the error

Test runner

---

package.json

As long as there is a package, even if there aren't any package dependencies.
The view has useful shortcut buttons (resolve, reset, update package) that you lose if it is hidden
Thoughts?

Always show package dependencies view

---

src/SwiftPackage.ts

So need to check for the new error string as well as the old

Swift 5.6 changed the no package error

---

src/TestExplorer/TestRunner.ts
src/WorkspaceContext.ts
src/commands.ts
src/utilities/tempFolder.ts
src/utilities/utilities.ts

Previously every VSCode session would create a new temp folder for test build logs, and swift scripts. This was not getting cleaned up. It doesn't appear there is a consistent way to do this as shell commands run by an extension are killed as soon as it exits.
Therefore I have reduced the temp folder down to one folder and ensure test runs and running swift scripts clean up after themselves.

Single tempfolder

---

src/TestExplorer/LSPTestDiscovery.ts

When opening/saving a file update `TestItems` to include location data for test functions (file uri and range inside file).

Get test location from document symbol request

---

src/TestExplorer/TestRunner.ts

Fix minor issue where test errors were displayed on the line below the error

Move test errors up one line

---

src/SwiftTaskProvider.ts
src/TestExplorer/TestRunner.ts
src/debugger/launch.ts
src/utilities/utilities.ts

- Don't run non-debug tests through the debugger
- This means when they crash you aren't stuck inside a debugger 
- I have access to `stdout` and `stderr` from the test process and can stream them into Test Explorer output pane, thus giving the user better feedback. On macOS test output comes in a mixture of `stdout` and `stderr` and these buffer at different rates which makes life difficult. So temporarily I have disabled showing `stdout` because test results are output to `stderr`
- Added proper cancellation processing. If you cancel a test run the test process will be killed.
- Display Test Explorer output as soon as testing starts.

Test Explorer improvements

---

package.json
src/SwiftTaskProvider.ts
src/commands.ts
src/configuration.ts

Currently only compile errors LSP server finds are shown. This change would display all errors found during build phase
Add problem matcher for swift compile
Add option to enable/disable the problem matcher (default: on)
issues: compile errors will duplicate what SourceKit-lsp provides. Compile errors only disappear once another compile is run

Display compile errors in problems view

---

package-lock.json
package.json
src/configuration.ts
src/sourcekit-lsp/LanguageClientManager.ts
src/sourcekit-lsp/inlayHints.ts

Up to this point Inlay hints have had a custom renderer. With version 1.65.0 of VSCode was released an official Inlay hints renderer. This PR moves the Inlay hints code to use that.
Note this PR requires people to upgrade to v1.65.0 of VSCode

Inlay hints Provider v2

---

package-lock.json
package.json
src/commands.ts
src/extension.ts
src/ui/LanguageStatusItems.ts

Provides a menu that displays the current version of Swift and the option to jump to the Package.swift for the currently edited file. The menu is accessible via the `{ }` icon next to the Swift label in the bottom right hand corner. 
This is a standard now. Check the same for typescript and json in the vscode-swift project.
This requires v1.65.0 of VSCode.

Add Language status item for Swift

---

src/SwiftTaskProvider.ts
src/TaskManager.ts
src/TestExplorer/TestExplorer.ts
src/TestExplorer/TestRunner.ts
src/WorkspaceContext.ts
src/commands.ts
src/extension.ts

It looks like there can only be one `vscode.tasks.onDidEndTaskProcess` handler running at any one time. So running two tasks at the same time might mean one of the tasks isn't registered as completed.
This PR centralise all task tracking in one place. Instead of calling `vscode.tasks.onDidEndTaskProcess` in multiple places. Have the TaskManager make this call and then other systems can subscribe to these message with TaskManagers own version of `onDidEndTaskProcess`

Task manager

---

src/TaskManager.ts

The execution termination doesn't trigger an onDidEndTaskProcess call so we need to dispose the handler and resolve the promise there and then

fix issue where a task is cancelled before it starts

---

src/TestExplorer/TestRunner.ts
src/extension.ts

Move build task out of `runHandler` and run it for both run and debug. remove preLaunchTask from debug config so it doesn't attempt to build the tests again.
Minor event change as well. When reacting to packageResolved events await for the resolve to finish before continuing. Otherwise it attempts to run multiple resolves at the same time.

Let TestExplorer cancel build when debug has been selected

---

src/WorkspaceContext.ts
src/extension.ts
src/sourcekit-lsp/LanguageClientManager.ts

It seems on Linux you cannot restart the LSP server. It passes back we sent an invalid messages without params when this is wrong. This means the shutdown of the server never completes.
These changes are an attempt to avoid requiring a restart by setting it pointing to the correct workspace folder at the beginning. I also added the await back onto the resolveDependencies as running these in parallel seems to be causing issues

LSP restart issues

---

src/TestExplorer/LSPTestDiscovery.ts
src/TestExplorer/TestExplorer.ts
src/sourcekit-lsp/DocumentSymbols.ts
src/sourcekit-lsp/LanguageClientManager.ts

Instead of calling LSP document symbol requests directly on file active and save events add a LanguageClient middleware that will extract the results of every document symbol request VSCode makes. 
This cleans the code up slightly and also means we don't make extra calls on top of what VSCode already makes. Also because document symbol calls are made as you are editing, the test list will be updated as you type.

Use Document symbol middleware in Test explorer

---

src/WorkspaceContext.ts

This means we stop removing focus from current edited file, when selecting problems, output, debug console etc

Don't send `unfocus` event when moving to non file view

---

package.json
src/BackgroundCompilation.ts
src/SwiftTaskProvider.ts
src/TestExplorer/TestRunner.ts

If a user has created a copy of the build task in tasks.json then use that version when building before running tests and for the background compilation.

Use task from tasks.json if it exists

---

src/SwiftTaskProvider.ts

When getting the correct build all task you need to check against the current working directory for the folder to ensure you get the correct task.

Need to check `cwd` in get build all task

---

package.json
src/TestExplorer/TestExplorer.ts
src/TestExplorer/TestRunner.ts
src/WorkspaceContext.ts
src/commands.ts
src/configuration.ts
src/toolchain/toolchain.ts
src/ui/SwiftOutputChannel.ts
src/utilities/utilities.ts

Add setting to output additional diagnostics to help debug issues. This has been prompted by the conversation in #188 
Additional diagnostics include, 
- toolchain values
- process executions
- testing launch config
- test debug start/cancel/stop events

Additional Diagnostics

---

src/debugger/launch.ts

Create a local variable with the `xctestPath` similar to the Darwin
case.  This reduces the line length subsequently and makes the test
match the use rather than use a proxy variable for the test.

debugger: simplify the logic for launching a test on Windows

---

src/TestExplorer/TestExplorer.ts

The Windows error message does not match Darwin nor Linux.  Add a
special case to ensure that the message is displayed properly.

TestExplorer: repair the messaging on Windows

---

package.json
src/configuration.ts
src/sourcekit-lsp/LanguageClientManager.ts

After speaking with @ahoppen it was decided the extension doesn't need the setting `sourcekit-lsp:toolchainPath` as it can set the toolchain using `swift:path`.
When starting an LSP server if both `swift:path` and `sourcekit-lsp:serverPath` are set and they point to different toolchains then set the lsp server toolchain to point to the swift toolchain.

Remove sourcekit-lsp.toolchainPath setting

---

src/debugger/launch.ts

The tests would silently fail previously due to the `Path` being setup
improperly.  We assumed that we could create a string that could be
evaluated by Powershell which is not the case as the environment is
passed to the node.js function `execAsync`, but would also mean that we
would be reliant on a specific shell.  The mismatched case would also
result in `PATH` and `Path` being set, and it is unclear which would
actually get used.

debugger: repair the Windows launching of tests

---

src/TestExplorer/TestRunner.ts

Fold away the conditional as both sides are identical.  This simply
reduces the code but should have no impact.

TestExplorer: fold duplicate if/else (NFC)

---

src/utilities/utilities.ts

Introduce `getExecutableName` to append `.exe` suffix for tools on Windows.

Introduce `getExecutableName`

---

src/toolchain/toolchain.ts

This environment variable is not stable and should be avoided going
forward.  The toolchain no longer relies on it and will be removed in a
future toolchain release.  The paths which are being computed relative
to these variables can be computed in alternative manners.  This should
be safe with older releases and newer releases of the toolchain on
Windows.

toolchain: remove dependency on `DEVELOPER_DIR` on Windows

---

assets/test/package1/Package.swift
assets/test/package2/Package.swift
docker/Dockerfile
docker/docker-compose.yaml
docker/test.sh
test/runTest.ts
test/suite/SwiftPackage.test.ts
test/suite/WorkspaceContext.test.ts
test/suite/extension.test.ts

Run `npm test`
Requires it to be run by `xvfb` in a separate shell file. If you include in docker-compose file it doesn't run
Had to install a bunch of additional stuff in Dockerfile to get it to work
Also added fix for test that only works in swift 5.6

CI: Run tests on swiftserver

---

test/suite/SwiftPackage.test.ts
test/suite/index.ts

Since I'm facing frequent timeouts and cannot successfully run all tests on my Windows setup, can we just make it longer?

Extend test timeout a bit longer for slower machines

---

scripts/soundness.sh

Fixes #64 
- Exclude `.vscode-test` and `docker` folders from looking for headers.
- Update `replace_acceptable_years` to allow 2022 as an acceptable year
Error without the replace_acceptable_years change:
```
missing headers in file './test/suite/WorkspaceContext.test.ts'!
--- /dev/fd/63  2022-04-17 15:20:39.000000000 -0700
+++ /tmp/.vscode-swift-soundness_wyuu2U 2022-04-17 15:20:39.000000000 -0700
@@ -2,7 +2,7 @@
//
// This source file is part of the VSCode Swift open source project
//
-// Copyright (c) YEARS-2022 the VSCode Swift project authors
+// Copyright (c) YEARS the VSCode Swift project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
```
soundness.sh now runs properly (on my machine atleast :) ).

Fix soundness script

---

src/commands.ts
src/toolchain/toolchain.ts

Based on #252, this PR introduce a new cached variable to judge if the new driver is being used.

Judge and cache if the new driver is used

---

src/commands.ts
src/toolchain/toolchain.ts

Remove `SwiftToolchain.newSwiftDriver` and base access to swift scripts on Windows on swift version.
@stevapple I spoke with @compnerd  and he feels that the existence of the new driver on Windows should be based on swift version and not the series of checks you provided. Given the new driver variable is only used to gate access to swift scripts on Windows I removed the new driver check in the toolchain and used the swift version to control access to swift scripts.

Base swift script availability on swift version

---

src/toolchain/toolchain.ts

`which` doesn't exist on base Centos7 or AmazonLinux2 so use `type -p`. Also `type` is a builtin on Centos7 so cannot be spawn using execFile so using exec instead.

Fix finding swiftc in centos7 and amazonlinux2

---

src/WorkspaceContext.ts
src/debugger/launch.ts
src/utilities/utilities.ts

This is to fix the issue where the launch.json is only updated for projects that are open when editing the runtime path is set. 
- Added `launchConfigKeysToUpdate` which defines what parameters of launch config can be updated by new config.
- Clone old config and then merge new config into clone. If the old config and new merged config are not the same then update.
- Added option to not show dialogs

Merge debug configs always when generating

---

src/debugger/launch.ts
src/utilities/utilities.ts

When launch.json configs need updating instead of showing a dialog for each config, show one dialog listing all configs.

Show single dialog for updating launch configs

---

src/WorkspaceContext.ts

Although the Swift release of lldb does not currently function
(c.f. #260), the default debugger does function and would enable at
least partial debugging which is useful.

Windows: support launching lldb on Windows

---

src/debugger/launch.ts

This is used by the debugger to locate the Swift module information for
the debugger.  Without this, we would fail to setup the Swift scratch
space in LLDB, which then results in the failure of the debugger and
subsequently the DAP.
Fixes: #250

debugger: pass along `SDKROOT` for the launch of the debugger

---

src/toolchain/toolchain.ts

The shuffling and restructuring accidentally lost an entry in the path.
This corrects that which should repair part of the execution problems.

toolchain: correct XCTest path on Windows

---

src/BackgroundCompilation.ts
src/SwiftTaskProvider.ts

Instead of copying and editing build task for background build tasks just use the same task.

Use same build task for background build

---

src/sourcekit-lsp/LanguageClientManager.ts

This fixes bug where restart of LSP server doesn't pick up new configuration.

If LSP server is force restarted create new client

---

src/debugger/launch.ts

When adding xcTestPath to the testEnv path it is possible for testEnv.Path to be undefined. In that case we need to drop back to using process.env.Path

Fixed issue with Windows Path in tests

---

.vscodeignore

Almost uploaded a 120MB extension because the test assets had created `.build` folders

Add a few more folders to .vscodeignore

---

src/TestExplorer/LSPTestDiscovery.ts

When editing `TestItems` based off changes coming from LSP server, if we delete all the functions items from a class then we should also delete that class item.

Delete empty classItems in `updateTestItems`

---

package-lock.json
src/WorkspaceContext.ts
src/debugger/launch.ts
src/debugger/lldb.ts
src/utilities/result.ts
src/utilities/tempFolder.ts

If failed to setup CodeLLDB to use the Swift version of LLDB, then don't set setting specific to Swift LLDB. 
Also show error message when failing to setup CodeLLDB.

Only set `target.sdk-path` if CodeLLDB setup Swift LLDB

---

src/WorkspaceContext.ts
src/debugger/lldb.ts
src/sourcekit-lsp/LanguageClientManager.ts
src/toolchain/toolchain.ts

Since adding the error message for when lldb setup fails, it has been obvious on a number of platforms it is failing. This PR adds a backup for when the lldb script fails. It makes some assumptions about where the `lldb.dll/so/dylib` might be found. On Linux and Windows this is based on the current structure of the installs. On macOS the backup plan will probably fail, but the script should not fail on macOS so this isn't a huge issue.

LLDB setup backup plan

---

docs/settings.md
package.json
src/SwiftTaskProvider.ts
src/configuration.ts
src/sourcekit-lsp/LanguageClientManager.ts
src/utilities/utilities.ts

Something like this @stevapple?

Add setting for environment variables to send to Swift

---

src/WorkspaceContext.ts
src/debugger/lldb.ts

If Windows Swift LLDB setup fails it will most likely be due to LLDB failing to run because $PYTHONHOME has been setup incorrectly. This means Swift LLDB will fail to run the debugger and should not be setup. 
The code change here just means failure to setup Swift LLDB on Windows will fail silently and will not attempt to guess the location of the Swift LLDB DLL.

Treat Windows Swift LLDB setup fail differently

---

src/BackgroundCompilation.ts

Don't run auto-build if saving Package.swift as it clashes with the resolve  that is run after the Package.swift is saved

Don't auto build when Package.swift is saved

---

src/sourcekit-lsp/inlayHints.ts

Instead of doing manual fix up myself use official code to protocol converter. Fixes issue when filename has a space in it

Use code2ProtocolConverter for InlayHints TextDocument

---

CHANGELOG.md
package-lock.json
package.json

Update package.json and CHANGELOG.md

Release v0.5.3

---

src/BackgroundCompilation.ts
src/FolderContext.ts
src/TaskQueue.ts
src/TestExplorer/TestRunner.ts
src/commands.ts
src/extension.ts

It is quite possible to run multiple swift Tasks at the same time. But running multiple versions of swift on the same package at once causes issues. This is especially true if you have background compilation enabled.
This PR is an attempt to alleviate some of these issues. It adds a queue which all swift tasks invoked by code are fed through. The queue will only allow one task to run at the same time. The queue generalises access to running swift Tasks, so I can remove some of the specialised code that controlled when background compilation ran and if a resolve/update was required.
Unfortunately I cannot control when the user initiates a swift build Task via the UI, so it is still possible to have those run on top of any swift Task initiated via code.

Swift Task queue

---

src/TestExplorer/TestRunner.ts
src/utilities/utilities.ts
test/suite/extension.test.ts
test/suite/utilities.test.ts

Increase size of buffer for stdio used by tests to 16MB. I found 1MB is not enough, in some situations
Report errors returned by running tests. Previously these were lost

Test output buffer and error reporting

---

src/toolchain/toolchain.ts

We use `type swift` to get the location of swift on Linux. This was assumed to alway output `swift is <swift location>` and the regular expression used to parse the output was constructed with this assumption. Unfortunately on a system setup as French it returns `swift test <swift location>`.
To get around this if we prefix the `type swift` call with `LCMESSAGES=C` it will return the message in English

Use LCMESSAGES=C to get English output from linux command type

---

src/SwiftTaskProvider.ts

Remove unnecessary `command` from definition. It is always `swift`.
Make `cwd` relative to scope if it is a workspace folder.

Swift Task Provider cleanup

---

package.json
src/sourcekit-lsp/LanguageClientManager.ts
src/sourcekit-lsp/inlayHints.ts
src/sourcekit-lsp/lspExtensions.ts

Official support for inlay hints in LSP will soon make the custom implementation superfluous. For more information, see the accompanying server-side PR (which this PR should be considered blocked on):
- https://github.com/apple/sourcekit-lsp/pull/465
This PR removes the client-side implementation of inlay hints as custom text decorations, which will no longer be needed once VSCode's and `vscode-languageclient`'s support for native inlay hints ships in the next release.
Additionally, `vscode-languageclient` is upgraded to a beta release, so native inlay hints can already be tested in a recent VSCode Insiders build.

Migrate to upstream LSP inlay hints on the client side

---

src/FolderContext.ts
src/TaskManager.ts
src/sourcekit-lsp/LanguageClientManager.ts
test/suite/version.test.ts

When Swift 5.7 is released it will include a version of SourceKit-LSP which include multi-workspace support. This will allow us to run a single server and add and remove workspace folders to it when they are added/removed to the VSCode workspace. This is an alternative to what we have now where the server is restarted every time we focus on a new workspace folder.
This PR keeps the original restart solution as it is needed for Swift 5.6 and earlier, but will use the single server solution if the version of Swift is 5.7 or later.

Add support for running a single LSP server that has multi-workspace support

---

src/SwiftTaskProvider.ts

Ensure task always has a `cwd`

Fix not finishing task.

---

src/WorkspaceContext.ts

Previously we were just sending the focus event, which meant `WorkspaceContext.currentFolder` wasn't get setup correctly

At start call focusFolder to set current folder

---

src/debugger/launch.ts

This fixes an issue which was introduced when we introduced the build folder option

Make program folder absolute in launch.json

---

package.json

Remove command property from swift task definition

---

README.md

This has been added so we can tell the user to build their app before expect sourcekit-lsp to work.
It seems a pretty common issue, so adding to the README seems a good idea
@0xTim Not sure about the wording, don't know if you have any better ideas

Add language featues section to README

---

src/ui/PackageDependencyProvider.ts

It seems `package` is more accurate than `archive`
https://code.visualstudio.com/api/references/icons-in-labels#icon-listing

change icon to `package`

---

docs/remote-dev.md

trailing comma is not allowed in JSON (although VSCode can tolerate it)

fix invalid JSON in devcontainer.json example

---

package.json
src/commands.ts
src/configuration.ts
src/sourcekit-lsp/LanguageClientManager.ts
src/toolchain/toolchain.ts
src/ui/QuickPick.ts
src/utilities/utilities.ts

This PR adds a command palette action to the extension that allows a user to quickly switch between the macOS and iOS SDK targets. It's only available if the host is macOS because the iOS SDK is not (officially) available for distribution on other operating systems.
The goal of these changes are to make the extension a more reasonable replacement for XCode by getting closer to the cross-compiling convenience that XCode offers through its UI. 
https://user-images.githubusercontent.com/68570223/182044190-ccabae14-b421-4a9d-aa5b-66412b91f4fe.mov

Add quick switcher between iOS and macOS targets

---

package.json
src/SwiftPackage.ts
src/commands.ts
src/ui/PackageDependencyProvider.ts

1. local/remote/edited dependency has remote/edited dependencies, Package.resolved covers them
2. remote/edited dependency has a local dependency, the local dependency must have been declared in root Package.swift
3. local dependency has a local dependency, traverse it and find the local dependencies only recursively
4. pins include all remote and edited packages for 1, 2
3: requires traverse, 4: reads from `package.resolved`

traverse local depedencies from package.swift

---

src/commands.ts
src/toolchain/toolchain.ts
src/utilities/utilities.ts

- Include tvOS and watchOS
- Enabling building of targets using SDKs
- Add warning about undefined results when using build

Extend platform select

---

src/TestExplorer/TestExplorer.ts
src/toolchain/toolchain.ts

swiftenv uses a shim shell script to run swift. This fix gets the real swift executable from the shim.
If we don't do this LLDB initialisation can fail, also it allows swiftenv to change the swift version without us knowing

Get correct swift path from swiftenv

---

src/toolchain/toolchain.ts

Ensures we pick up the correct folder when DEVELOPER_DIR is set

Set environment when running xcrun

---

src/PackageWatcher.ts
src/SwiftPackage.ts
src/utilities/utilities.ts

Only send resolveUpdated event if Package.resolved hash has changed
This should fix an issue where multiple package resolves happen even though nothing has changed.

Store hash of Package.resolved

---

src/commands.ts
src/configuration.ts

Also make sure we clear the SDK when selecting macOS, instead of setting an empty string

Don't show error when selecting macOS SDK

---

package.json
src/commands.ts

Adds "Swift" sub-menu to editor right click menu. Entries include
- Run swift script *(when current file is not a snippet)*
- Run swift snippet *(when current file is a snippet)*
- Debug swift snippet *(when current file is a snippet)*
- Clean build *(when we have a package loaded)*

Add right click sub-menu to editor window

---

assets/test/identity-case/Package.resolved
assets/test/identity-case/Package.swift
assets/test/identity-case/Sources/identity-case/identity_case.swift
src/SwiftPackage.ts
src/ui/PackageDependencyProvider.ts
test/suite/SwiftPackage.test.ts

This PR fixes the bug of some dependency (eg. `Yams`) not being recognized due to case-sensitive identity comparison.

Swift package identity is case-insensitive

---

docs/settings.md
package.json
src/TestExplorer/TestRunner.ts
src/configuration.ts
src/extension.ts

Previously we would list every test we wanted to run in the XCTest command line. This causes issues on Windows where the maximum length for a command line is 4096 characters. This PR tries to avoid by reducing the length of the XCTest command line
- If all tests are run then it will not include an `-XCTest` filter at all
- Where it can it will use the XCTestCase class name as a filter instead of adding an entry for every function in that class.

Reduce length of XCTest command line

---

src/extension.ts

When the extension is not run through a debugger, VS Code does not show the extension failed to activate message if activation throws an error. This PR ensures it shows an error if activation fails.

Show error message when activation fails

---

assets/test/identity-different/Package.resolved
assets/test/identity-different/Package.swift
assets/test/identity-different/Sources/identity-different/identity_different.swift
src/SwiftPackage.ts
test/suite/SwiftPackage.test.ts

Previous code was just lowercasing the package name, when the identity should be extracted from the URL

Calculate V1 resolved package identity correctly

---

assets/test/identity-different/Package.resolved
src/WorkspaceContext.ts

It was possible to add a folder twice, via `addWorkspaceFolders` and `focusUri`.
If a package takes a long time to load during initialisation, a focus event can occur prior to the package being fully loaded. At this point because the folder for that package isn't setup it will attempt to add the package again.

Ensure we don't add folders twice at startup

---

package.json
src/SwiftTaskProvider.ts
src/WorkspaceContext.ts
src/configuration.ts
src/debugger/launch.ts
src/extension.ts

In #400 I added the ability to set configuration values on a per folder basis. I didn't realise this wouldn't work automatically.
This PR implements loading configuration settings for each workspace folder. It also removes the ability to set it on a number of settings eg `buildArguments`, because they are used by SourceKit-LSP and it only has one set of arguments.

Read configuration from workspace folder and not workspace

---

src/toolchain/toolchain.ts

If swift path configuration setting is set and swift inside that path is a symbolic link find the real version of swift. Basically this adds the same checks to swift exe's found via the system $PATH to swift exe's that are found via the configuration setting `swift.path`
Currently implementation of `swiftly` uses symbolic links

If swift exe in `swift.path` is symbolic link find real swift

---

src/FolderContext.ts
src/SwiftPackage.ts
src/SwiftPluginTaskProvider.ts
src/extension.ts
src/ui/StatusItem.ts

Previously part of the package load was to load the package plugins, but this seems to internally do a package resolve which means it can look like package loading takes longer than expected. This PR moves the plugin loading after the package resolve and adds a status item for the plugin loading. Now the order of operations is load, resolve, load plugins. 
This PR also adds helper function StatusItem.showStatusWhileRunning which shows a status item while a task/process is running.

Reorder plugin loading to occur after package resolve

---

src/TestExplorer/TestExplorer.ts

Old school linux test discovery allows for arbitrary test names. This is made use of by libraries like Quick.

Relax rules for test names in list test output

---

src/TestExplorer/TestRunner.ts

Changes are mainly to reduce the size of the parsing functions and remove duplicated code.
Also add parsing of Test Suite messages, although we don't use them yet. 
Was hoping they'd give me a more solid idea of what target was being run as Linux test parsing is lacking some information and I have to make guesses about the test target a test is in. Unfortunately this hasn't helped. But this leaves test output parsing in a better place as I have a better understanding of the parsing state now.

Cleanup test output parsing

---

package.json
src/WorkspaceContext.ts

Triggers extension when a compile_commands.json exists at root of workspace. Because there is no package.swift in the folder most of the extension will do nothing, but it will start the LSP server so code completion will be available.
Also look for CMake projects in the subfolders of workspaces.

Add support for CMake projects

---

src/TestExplorer/TestExplorer.ts

This fixes an issue where building tests would clear the location of tests

Only add testItem if it doesn't exist

---

src/TestExplorer/TestRunner.ts
src/toolchain/toolchain.ts

Adds addition TestRunProfile that will output lcov files to be used by code coverage extensions. Have to push running of tests through `swift test` to get code coverage output working. Runs tests and after runs llvm-cov. 
You can view the code coverage results using extension https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters

Generate code coverage lcov files after tests

---

src/TestExplorer/TestRunner.ts

The build has already been run.
You only need to enable the build when code coverage has been enabled. This also fixes an issue on Windows where tests were not running.

Skip build when running tests

---

src/TestExplorer/TestOutputParser.ts
src/TestExplorer/TestRunner.ts
test/suite/TestOutputParser.test.ts
test/suite/extension.test.ts

Move Test output parsing code into TestOutputParser.ts
Add interface for test run state `iTestRunState` which allows us to test this code outside of the TestRunner
Add testing of Darwin test output parsing
Fix issue where test output line is split between two buffers 
Add testing of Linux test output parsing and fixed bug with skipped tests

Extract TestOutputParser from TestRunner and add tests

---

package.json
src/TestExplorer/TestCoverageReport.ts
src/TestExplorer/TestRunner.ts
src/WorkspaceContext.ts
src/commands.ts

I couldn't find an extension that would provide a test coverage report from the text output of llvm-cov so here is one for vscode-swift

Test coverage report

---

package.json
src/WorkspaceContext.ts
src/commands.ts
src/editor/CommentCompletion.ts
src/extension.ts

In addition to typing "///" you can now add a function documentation comment header using the shortcut key `Alt+Cmd+/` while the cursor is on the first line of the function declaration.

Add command to insert function comment header

---

src/ui/StatusItem.ts

When you click on the status item, if it is associated with a task, it will run the show task command

Add show task command to status item

---

assets/test/sleep.sh
docker/Dockerfile
src/TaskManager.ts
test/suite/tasks.test.ts

If two tasks with same name but different scopes are executed at the same time the second one does not run. This showed up as a bug in the test explorer when you have more than two workspaces folders both with tests. Both packages would instigate a build but the second build would never run. The fix is to add a promise to wait until the first task has actually stated then the second one will start. 🤷 
I've also added a bunch of tests for the TaskManager and TaskQueue

Workaround vscode task execution bug

---

package.json
src/configuration.ts
src/sourcekit-lsp/LanguageClientManager.ts

The Sourcekit-LSP C/C++ support is clashing with the C/C++ extension
Setting has options
- always enable
- always disable
- disable if cpptools extension is active (default)

Add setting to disable c/c++ support

---

src/editor/CommentCompletion.ts

Updated comment completion function capture to avoid catching `init` inside function eg
```swift
var value: test { .init("test') }
```
Changed regex to stop at `{`

Fix getFunctionDetails to not capture init inside function 

---

package-lock.json
package.json
src/sourcekit-lsp/LanguageClientManager.ts

Copy of the default error handler, except it includes an error message that asks if you want to restart the sourcekit-lsp server again after so many crashes.
This require 8.1.0 release of vscode-languageserver-node. If you want to test this please make sure you run `npm install` before running.

Sourcekit-LSP crash handler dialog

---

src/ui/LanguageStatusItems.ts

Base swift version on documentSelector from LanguageClient
Only display Package.swift if there is a Package.swift

Fix language status item visibility

---

src/debugger/launch.ts

This is preparation for the swift throw breakpoint. You need to tell CodeLLDB you are running a swift program for it to display the `Swift: on throw` breakpoint toggle.

Set launch configs sourceLanguage to swift

---

src/WorkspaceContext.ts
src/extension.ts

Previously it was done on focus/unfocus and only the active project plugins were available. Now it sets the availability based on all the workspace folders. It checks availability after load plugins has finished

Set plugin available context key after loading plugins

---

src/toolchain/toolchain.ts

In the case the `Info.plist` is encoded improperly (e.g. UTF16-LE) we would fail to parse the file and then error out.  Catch the error and surface it properly for the user to follow along.
Fixes: #515

toolchain: ensure that we catch decoding failures

---

src/TestExplorer/TestOutputParser.ts
src/TestExplorer/TestRunner.ts
test/suite/TestOutputParser.test.ts

Changed iTestRunState suite interface to include start, pass and fail methods. TestRunner implementation then stores last test item processed and when suite is passed or failed checks it is the parent of last item and then updates it.

Update class TestItems as test suites are finished

---

package.json
src/SwiftPluginTaskProvider.ts
src/SwiftTaskProvider.ts
src/TaskManager.ts
src/TaskQueue.ts
src/WorkspaceContext.ts
src/extension.ts
src/utilities/utilities.ts
test/suite/tasks.test.ts

Added disableTaskQueue flag to both swift and swift-plugin task definitions.
This will disable processing tasks in the task queue while this task is running. Build tasks will automatically get this set. 
Tasks that go in the task queue include resolve, update, reset, clean etc
You could use this to disable auto-resolve while a command plugin is running

Add flag to disable queued tasks while running build/plugin tasks

---

src/SwiftPluginTaskProvider.ts

Add defaults for lambda-runtime package, docc generate and preview, SwiftFormat
I didn't add any for swift-format as it requires you to add project specific arguments
@0xTim if you can think of any others that'd be great

Add defaults settings for commonly used command plugin

---

package.json
src/SwiftTaskProvider.ts
src/TestExplorer/TestExplorer.ts
src/configuration.ts
src/debugger/launch.ts
src/toolchain/Sanitizer.ts
src/toolchain/toolchain.ts

- Adds build arguments where required
- On macOS adds environment variables that are needed to run sanitizer outside of `swift test`.
- On macOS when listing tests if you are using a sanitizer rebuild the application as changing between sanitizers can cause swift to hang when listing tests while skipping the build.

Add sanitizer configuration setting

---

src/SwiftTaskProvider.ts

if there is an active task running on the folder task queue (eg resolve or update) then don't add build tasks for this folder instead create a dummy task indicating why the build tasks are unavailable.
Not totally sure about this one, it fixes the issue where running a build on top of an update or resolve can break your `.build` folder. But it creates a dummy task that can be run and added to your tasks.json. Even though the task does nothing it's not great.
The other option is to just not create the dummy task, but then there is no indication to the user why the build tasks are not available.
I have added the following request to the vscode repo https://github.com/microsoft/vscode/issues/184047 which would allow us to add tasks to the build tasks list which were not actionable. This …

Don't add build tasks, while active operation running

---

src/SwiftTaskProvider.ts
src/utilities/version.ts
test/suite/WorkspaceContext.test.ts
test/suite/extension.test.ts

Don't need "-Xswiftc", "-g", "-Xswiftc", "-use-ld=lld" anymore

With Swift 5.9 we can remove some build arguments for Windows

---

docs/settings.md
package.json
src/configuration.ts
src/sourcekit-lsp/LanguageClientManager.ts

Body:
In this Pull Request, I have added a new configuration option sourcekit-lsp.support_languages. This configuration allows users to specify the list of languages that the sourcekit-lsp extension should support.
The primary reason for this change is to resolve the conflict between the sourcekit-lsp and clangd extensions. The original cpptools-inactive option only considered the ms-vscode.cpptools extension. However, in a mixed Swift and Objective-C++ development environment, the Language Server Protocol (LSP) can often encounter issues, and clangd tends to be more stable than cpptools in these scenarios.
This update allows users to leverage clangd for Objective-C and Objective-C++ development while continuing to use sourcekit-lsp for Swift. It provides more flexibility for developers …

 Add configurable language support to mitigate conflict with clangd extension

---

src/commands.ts

When the Xcode developer directory is changed using the selectXcodeDeveloperDir command we need to reload the application to ensure we are running with the correct version of swift

Reload window after selectXcodeDeveloperDir command

---

package.json

Compiler errors like this one didn't show up in the VS Code Problems pane:
```
<unknown>:0: error: cannot open file 'foobar.h': no such file or directory
```
This is because the `swiftc` problem matcher requires a line and a column number. This change updates the regex to support the lack of a column number, so that the error above will show up in the Problems pane. It shows up under a dummy file called `<unknown>`, but that's probably the best we can do with the VS Code problemsMatcher API. I tried making the first matching group not match when finding `<unknown>` but VS Code really expects something in the file group.
How tested: used a custom build task that prints error-like lines:

Update problemMatcher to match Swift errors without a column number

---

src/sourcekit-lsp/LanguageClientManager.ts

The text edits attached to InlayHints returned by SourceKit-LSP do not always produce valid code. This adds an InlayHint middleware to remove them until SourceKit-LSP returns valid code or it disables the text edits

Remove InlayHint text edits

---

src/BackgroundCompilation.ts
src/extension.ts

In this situation the build replaces the resolve as a build will run a resolve

If background compilation is on, run build at startup

---

docker/docker-compose.yaml
src/toolchain/toolchain.ts
test/suite/extension.test.ts

Fix check for swift version when we are running Swift 5.3 or earlier. Previously extension would fail to startup.
We don't really support versions earlier than 5.4 but this was a small fix

Fix swift 5.3 version check

---

package.json
src/configuration.ts
src/sourcekit-lsp/LanguageClientManager.ts

Deprecate old settings without swift prefix.
Eventually we will want to remove the old settings.
This is to fix the issue where users have the old sourcekit-lsp extension installed and the setting names clash and cause the swift extension to not load anymore.
See #498

Add sourcekit-lsp settings with swift prefix

---

src/SwiftPluginTaskProvider.ts
src/SwiftTaskProvider.ts
src/TestExplorer/TestRunner.ts
src/sourcekit-lsp/LanguageClientManager.ts
src/toolchain/toolchain.ts
src/utilities/utilities.ts
test/suite/utilities.test.ts

Instead of getSwiftExecutable
This is cleaner, will return the actual executable path rather than the one in $PATH (/usr/bin/swift on macOS)

Use SwiftToolchain.getToolchainExecutable

---

src/TestExplorer/TestRunner.ts
src/debugger/launch.ts
src/debugger/logTracker.ts
src/extension.ts

While messing about with the llvm lldb-vscode DAP I found the `DebugAdapterTracker` class which allows us to catch every message going between VSCode and the debugger. This PR adds one to catch all the output to stdout and stderr by the debuggee and passes it to the test runner. It cleans up the last issue I really had with debugging tests where the output from tests didn't appear until you had finished running the tests.

Added debug adapter tracker to catch logging from debugger

---

src/toolchain/toolchain.ts

The extension fails to find Swift on Windows due to missing `.exe` suffix.

Fix custom Swift path on Windows

---

package.json
src/TestExplorer/TestExplorer.ts
src/WorkspaceContext.ts
src/configuration.ts
src/extension.ts

Previously you would have to open a file from the actual swift package before it would load. With this option it will search the workspace folder tree for swift packages and automatically load them.
Also fixed an issue where a folder was being added twice to the workspace. And then added a check in `addPackageFolder` to ensure it doesn't happen elsewhere.

Add option to search subfolders for packages on initialisation of extension

---

CHANGELOG.md
package.json
src/WorkspaceContext.ts
src/configuration.ts
src/debugger/debugAdapter.ts
src/debugger/debugAdapterFactory.ts
src/debugger/launch.ts
src/debugger/logTracker.ts
src/extension.ts

This is only available in the Windows toolchain at the moment. If you want to use it on other platforms you need to build a toolchain yourself and extract the lldb-vscode executable out of the build folder and copy into the bin folder alongside swift.
This is not enabled by default. You have to go into the settings and select `swift.debugger.useDebugAdapterFromToolchain`

Use lldb-vscode debug adapter from Swift Toolchain

---

src/debugger/lldb.ts
src/sourcekit-lsp/LanguageClientManager.ts
src/toolchain/Sanitizer.ts
src/toolchain/toolchain.ts

Previously it was two folders up and swift executables were assumed to be in a `usr/bin` folder relative to the toolchain folder. It looks like this cannot be assumed. The arm64 toolchains generated by @futurejones are installed at `/usr/libexec/swift` and have their binaries folder in `/usr/libexec/swift/bin`. So the toolchain path is now set to one folder up instead and the binaries folder is set to be `bin` relative to the toolchain folder.
I have checked the sourcekit-lsp code to see if it is happy with this as a valid toolchain path. It appears to be, but will verify with developers

Toolchain path is one folder up from swift bin path

---

src/toolchain/toolchain.ts

Previous PR setting to toolchain path to be one below bin folder, missed one case ie where the swift path is set explicitly

Fix setting toolchain path from custom swift folder

---

src/debugger/launch.ts

Debug configuration paths were generated with mixed back and forward slashes and no `.exe` extensions. That worked for `lldb` but not for `swift-lldb`.
https://github.com/swift-server/vscode-swift/pull/609 scoped down and applied to `pre-release/1.6`

Fix debug config path formats on Windows

---

src/commands.ts
src/extension.ts
src/sourcekit-lsp/LanguageClientManager.ts
src/toolchain/BuildFlags.ts
src/toolchain/toolchain.ts
test/suite/BuildFlags.test.ts
test/suite/SwiftPackage.test.ts
test/suite/version.test.ts

Typescript does not support operator overloading. What was happening when we compared two Version objects was that `toString` was called on both sides and the strings were compared. Unfortunately the unit test wasn't catching this because the strings ended up being lexicographically ordered.
This probably fixes several issues, but the one I was after is the Windows xctest path in the debug configuration being incorrect with a Swift 5.11 build because the `>= new Version(5, 7, 0)` was returning false.

Fix version comparison

---

src/coverage/LcovResults.ts

Fixes issue where swift-nio coverage was unavailable

Increase stdout size available to llvm-cov

---

src/extension.ts

Build and run should be available as soon as resolve has finished, not after the plugin list has loaded

Dont await loadSwiftPlugins.

---

src/BackgroundCompilation.ts
src/SwiftSnippets.ts
src/SwiftTaskProvider.ts
src/TaskQueue.ts
src/TestExplorer/TestExplorer.ts
src/TestExplorer/TestRunner.ts
src/commands.ts
test/suite/tasks.test.ts

The task queue allows us to control what processes are running in a workspace. Previously you could only add vscode tasks to the task queue. This meant I could ensure resolve, update tasks never clashed with a build task. VSCode tasks don't allow for parsing of their output, so some processes had to be spawned manually. There was no control over when these processes could be run, so sometimes they would clash with other processes particularly build tasks.
This PR allows you to add operations that spawn executables and parse their output to the task queue. And then the changes are used to add test list parsing and unediting of package dependencies to the task queue. So they should not clash with any build process.

Spawn processes and parse their output on task queue

---

src/toolchain/toolchain.ts

When using `type swift` we need to set `LC_MESSAGES=C` to get the output in English. Unfortunately we set `LCMESSAGES=C`

Fix LC_MESSAGES typo

---

src/TestExplorer/TestRunner.ts

TestResults are automatically shown, and calling this overrides the option `Testing: openTesting` which controls when to show the Test Results pane

Don't call testing.showMostRecentOutput on test start

---

package.json
src/SwiftTaskProvider.ts

Add `macos`, `linux` and `windows` sections to swift task definition to allow for platform specific settings
Also add `env` field for setting environment variables while running a swift task

Platform specific task config

---

.gitignore
src/TestExplorer/LSPTestDiscovery.ts
src/TestExplorer/TestDiscovery.ts
src/TestExplorer/TestExplorer.ts
src/sourcekit-lsp/LanguageClientManager.ts
src/sourcekit-lsp/lspExtensions.ts

- Generalised test explorer update for single file and whole workspace.
- Create test explorer update from `workspace/tests` LSP response and apply
- Create test explorer update from document symbols response for a single file and apply (Replacing previous update code in LSPTestDiscovery.ts)
I haven't include in this PR the creation of a test explorer update from `swift test list` just to keep the PR size down. I'll do that in another PR.

Use `workspace/tests` to get list of tests instead of `swift test list`.

---

.github/dependabot.yml
package.json

- Get Dependabot to report for only direct dependencies. It is suggesting so many updates I can't keep up with it
- Move Typescript `@types` files to devDependencies, they don't need to be included in the released package

Dependabot direct

---

src/TestExplorer/TestRunner.ts
src/utilities/utilities.ts

Instead of just reporting there was an error, actually review the error and respond. Also moved error checking to the correct catch block
- If process return 1 and was not killed. Assume test failed and ignore
- If process was killed report in console
- If process signal is SIGILL then it crashed, report in console and attach last line of stderr as error for currently running test
- Unrecognised errors are reported to the console
Also execFileStreamOutput no longer pointlessly wraps the error in `{}`

Improve error handling when running tests

---

src/TestExplorer/TestOutputParser.ts
src/TestExplorer/TestRunner.ts
test/suite/TestOutputParser.test.ts

Added `TestItemFinder` interface to define how you get a TestItem from the test id extracted from XCTest output
Added `TestRegex` interface which defines the regex to use when parsing the XCTest output.
Merge both `parseResultDarwin` and `parseResultNonDarwin` into one function `parseResult`.
I will also need the `TestItemFinder` when supporting parallel testing

Merge test parsing functions into one

---

package-lock.json
package.json
src/TestExplorer/TestExplorer.ts
src/TestExplorer/TestRunner.ts
src/TestExplorer/TestXUnitParser.ts
src/utilities/tempFolder.ts

This adds a new test runner for running tests in parallel (It is in the menu at the top of the test explorer that includes test coverage).
Because parallel testing doesn't produce a parseable output by default, I have to use `--xunit-output` to output xUnit XML. This is then parsed using the `xml2js` module.
There are a couple of issues with this as is
- Skipped tests are indicated as passed in the xUnit XML.
- When running `swift test --parallel` failed test output does not have any newlines. So I can't parse out error messages. This is fixed on swift main, so will be resolved in Swift 6.
- The last time I checked running `swift test` using `execFile` on Windows does not work, so parallel testing will not be available on Windows in a similar way coverage isn't available.
Because of the …

Parallel testing

---

src/FolderContext.ts
src/SwiftPackage.ts
src/SwiftTaskProvider.ts
src/TestExplorer/TestDiscovery.ts
src/TestExplorer/TestExplorer.ts
src/debugger/launch.ts

Return all targets if undefined

Add TargetType enum for SwiftPackage.getTargets

---

src/TestExplorer/TestOutputParser.ts
src/TestExplorer/TestRunner.ts
test/suite/TestOutputParser.test.ts

Capture all the issues recorded in a failing test and add them as individual failures on the vscode.TestRun.

Support recording multiple issues per test

---

src/TestExplorer/DocumentSymbolTestDiscovery.ts
src/TestExplorer/LSPTestDiscovery.ts
src/TestExplorer/SPMTestDiscovery.ts
src/TestExplorer/TestDiscovery.ts
src/TestExplorer/TestExplorer.ts
src/sourcekit-lsp/LanguageClientManager.ts
src/sourcekit-lsp/lspExtensions.ts
test/suite/testexplorer/DocumentSymbolTestDiscovery.test.ts
test/suite/testexplorer/SPMTestListOutputParser.test.ts
test/suite/testexplorer/TestOutputParser.test.ts

If the LSP is available and supports the two requests for listing tests then use those to discover tests in the workspace/document. If these requests are unsupported or if they fail, fall back to the existing methods.
This patch uses the existing code to leverage the LSP's workspace/tests method and adds the textDocument/tests for listing tests within documents as they change.
These requests produce a collection of TestClass structures, which are hierarchical. These are passed to one of the methods in TestDiscovery.ts which diffs against the existing tree and adds/removes tests. This is similar to how it already worked, but now supports arbitrary levels of nesting in the TestClass structure.
This patch also adds preliminary support for listing swift-testing tests through the LSP methods, …

Discover tests via LSP if available

---

CONTRIBUTING.md
package.json

Setting `swift.sourcekit-lsp.serverPath` can cause issues if the binary's version doesn't match the user's installed toolchain.
Deprecate the setting, keeping it available for extension developers, and make a note in the CONTRIBUTING.md.

Deprecate swift.sourcekit-lsp.serverPath setting

---

src/SwiftPackage.ts
src/TestExplorer/LSPTestDiscovery.ts
src/TestExplorer/TestDiscovery.ts
src/TestExplorer/TestExplorer.ts

The test target ID provided to XCTest needs to be a valid Swift identifier. The test target name is not guarenteed to be valid.
Instead, use the c99name, which is the name converted to a c identifier, which is also a valid swift identifier.

Use c99name for test target IDs

---

.vscode/launch.json
package-lock.json
package.json
src/SwiftPluginTaskProvider.ts
src/SwiftTaskProvider.ts
src/tasks/SwiftExecution.ts
src/tasks/SwiftProcess.ts
src/tasks/SwiftPseudoterminal.ts
src/utilities/native.ts
src/utilities/tasks.ts
test/suite/WorkspaceContext.test.ts
test/suite/extension.test.ts
test/suite/tasks.test.ts

To give us more control of the swift process and allow us to consume the output from swift, introduce our own CustomExecution. This will set us up to address #750, #653 and #694.
The CustomExecution will load the asar bundled node-pty module that ships with vscode. This way we don't need to build for every platform and arch

Add a CustomExecution for `swift` tasks

---

docker/Dockerfile
src/SwiftPluginTaskProvider.ts
test/suite/WorkspaceContext.test.ts
test/suite/tasks.test.ts

There are two different current working folders in a Swift Plugin task. One is the one inside the tasks definition. This should always be relative to the workspace folder, so the task.json can be shared across multiple machines. The other is the actual current working folder to run the executable in.
This PR splits the two.

Setup cwd correctly for plugin tasks

---

test/suite/tasks.test.ts

The `Event handlers fire` task test was timing out with the main toolchain.

Increase timeout in task test

---

src/SwiftTaskProvider.ts

SwiftPM in Swift 6 and later does not allow for multiple processes to access the build folder and stalls them until it is available. So we don't need to disable build tasks.
I also added a relative path to the `Build tasks disabled` text when it is needed in a similar manner to the actual build tasks.

Only disable build tasks in swift versions less than v6

---

src/TestExplorer/TestDiscovery.ts
src/TestExplorer/TestParsers/SwiftTestingOutputParser.ts
src/TestExplorer/TestParsers/TestEventStreamReader.ts
src/TestExplorer/TestParsers/TestRunState.ts
src/TestExplorer/TestParsers/XCTestOutputParser.ts
src/TestExplorer/TestRunArguments.ts
src/TestExplorer/TestRunner.ts
src/TestExplorer/TestUtils.ts
src/debugger/launch.ts
src/toolchain/toolchain.ts
src/utilities/tempFolder.ts
src/utilities/utilities.ts
test/suite/testexplorer/MockTestRunState.ts
test/suite/testexplorer/SwiftTestingOutputParser.test.ts
test/suite/testexplorer/TestRunArguments.test.ts
test/suite/testexplorer/XCTestOutputParser.test.ts

Support running swift-testing tests the same as XCTests. If a test run has both types, swift-testing tests will be run first followed by XCTests.
First a list of XCTests and swift-testing tests to run is parsed from the test request. Test type is determined by a tag on each `vscode.TestItem[]`, either `"XCTest"` or `"swift-testing"`.
swift-testing tests are launched by running the binary named <PackageName>PackageTests.swift-testing inside the build debug folder. This binary is run with the `--experimental-event-stream-output` flag which forwards test events (test started, complete, issue recorded, etc) to a named pipe. The `SwiftTestingOutputParser` watches this pipe for events as the tests are being run and translates them in to `ITestRunner` calls to record test progress in VSCode. …

Add support for swift-testing

---

src/TestExplorer/TestParsers/TestEventStreamReader.ts

Using Node's built in net.Socket imposes an 8kb message limit on the JSONL writes from swift-testing. This meant that if a test case had a lot of iterations the `test` event would overrun the limit and the message would never be read.
Create our own readable stream and manage pausing/resuming the pipe on data/drain events. This allows for swift-testing to write whatever size messages it wants.

Handle swift-testing events > 8kb

---

src/toolchain/toolchain.ts

It is possible for `which swift` to return multiple lines if the user has more than one Swift toolchain installed. Windows behavior is to use the first one, so we use it as well but also warn the user.

Handle having multiple Swift toolchains on Windows

---

src/SwiftTaskProvider.ts
src/TestExplorer/TestDiscovery.ts
src/TestExplorer/TestParsers/SwiftTestingOutputParser.ts
src/TestExplorer/TestParsers/TestRunState.ts
src/TestExplorer/TestParsers/XCTestOutputParser.ts
src/TestExplorer/TestRunArguments.ts
src/TestExplorer/TestRunner.ts
src/utilities/utilities.ts
test/suite/testexplorer/MockTestRunState.ts
test/suite/testexplorer/SwiftTestingOutputParser.test.ts
test/suite/testexplorer/TestRunArguments.test.ts
test/suite/testexplorer/XCTestOutputParser.test.ts

Swift-testing emits a `test` event at the beginning of a test run that enumerates all the parameterized test cases to be executed.
This patch waits for the `test` event and then generates `vscode.TestItem`s for each parameterized test execution, parenting them to their test. Then when we recieve a `runStarted` event we enqueue all the tests along with the newly created parameterized `TestItem`s.
Before a new test run starts we remove the existing parameterized `TestItems` so we can regenerate them, as there may be a different number of parameterized tests run with every execution.

Support parameterized swift-testing tests

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.gitignore

Use swiftlang/swift:nightly-6.0-jammy as base image. Install build requirements. Install NVM and Node, make separate node_modules volume so we can build Linux specific node_modules, ensure we can write to it and run `npm install`
It also includes the requirements for building SourceKit-LSP.

Add DevContainer for building and testing VSCode extension

---

src/TestExplorer/TestRunner.ts

The named pipe to parse swift-testing test results was not being created when doing a debug run, preventing test results from being parsed.

Ensure named pipe is created for swift-testing debug test runs

---

package.json

Adding our own button to the welcome page by default is a tragedy of the commons issue. I'd like to keep the button available, but allow it to be hidden with a configuration option.

Allow hiding the create swift project button from the welcome page

---

scripts/soundness.sh
src/TestExplorer/TestParsers/SwiftTestingOutputParser.ts
src/TestExplorer/TestParsers/TestEventStreamReader.ts
src/TestExplorer/TestParsers/TestRunState.ts
src/TestExplorer/TestUtils.ts
src/tasks/TaskQueue.ts
test/suite/testexplorer/MockTestRunState.ts
test/suite/testexplorer/TestExplorerIntegration.test.ts
test/suite/testexplorer/utilities.ts

Just realised we haven't been running the soundness script in CI.
@yim-lee can I have CI run the soundness script. There is a docker-compose `soundness` service which should trigger the script. Thank you

Update soundness script and files without headers

---

docker/docker-compose.2204.60.yaml

We are testing on Swift 5.10 and the trunk branch (main) toolchain, but not the 6.0 toolchain.

Add docker image for testing the Swift 6.0 toolchain

---

package.json

The custom coverage reporting was removed. However, there are references to two of the coverage commands remaining in the package.json. This PR removes those references.

Remove references to coverage commands

---

assets/test/defaultPackage/Tests/PackageTests/PackageTests.swift
src/TestExplorer/TestParsers/SwiftTestingOutputParser.ts
src/TestExplorer/TestParsers/TestRunState.ts
src/TestExplorer/TestParsers/XCTestOutputParser.ts
src/TestExplorer/TestRunner.ts
test/suite/testexplorer/MockTestRunState.ts
test/suite/testexplorer/SwiftTestingOutputParser.test.ts
test/suite/testexplorer/TestExplorerIntegration.test.ts
test/suite/testexplorer/XCTestOutputParser.test.ts

If an expectation fails within a withKnownIssue closure the issue is marked with `isKnown` and should be excluded from the list of expectation failures. If all expectations in a test are marked `isKnown` then the test should be shown as skipped.
rdar://129024156

Respect withKnownIssue in swift-testing tests

---

assets/test/diagnostics/.vscode/launch.json
assets/test/diagnostics/Package.swift
assets/test/diagnostics/Sources/func.swift
assets/test/diagnostics/Sources/main.swift
package.json
src/DiagnosticsManager.ts
src/SwiftSnippets.ts
src/WorkspaceContext.ts
src/configuration.ts
src/sourcekit-lsp/LanguageClientManager.ts
src/tasks/SwiftTaskProvider.ts
test/fixtures.ts
test/suite/DiagnosticsManager.test.ts
test/suite/WorkspaceContext.test.ts
test/suite/tasks/SwiftTaskProvider.test.ts

Fixes #653
* Keeping "$swiftc" problem matcher around in case it is still being used
* Add "diagnosticsCollection" setting to give more control on which diagnostics are kept around and provided to the user
* Setup diagnostics from task output and hooking into sourcekit-lsp
* Handle merging based on "diagnosticsCollection" setting
This does not include serialized diagnostics which will involve changes in swift itself

Deduplicate swift diagnostics

---

src/TestExplorer/TestParsers/SwiftTestingOutputParser.ts
src/TestExplorer/TestRunner.ts

On posix platforms if a named pipe hasn't been written to then occasionally calls to fs.lstat (which I believe fs.rm uses internally) will  hang indefinitely.
If a test run failed due to a compiler error in the build then the pipe never be written to. By repeatedly trying to perform a test run with code that fails to compile eventually this hang would appear.
Work around the issue by writing to the pipe if compilation fails, ensuring the connection opens/closes and the pipe can be removed

Fix flakey pipe removal

---

src/tasks/SwiftPseudoterminal.ts

We were silently failing and closing off the task instead of letting the user know something is wrong

Show task error messages

---

src/tasks/SwiftTaskProvider.ts

Use the folder path as part of the build all task cache key. This prevents the same build task from being returned for different folders in the workspace.

Key build all tasks with folder path

---

src/sourcekit-lsp/LanguageClientManager.ts

When restarting SourceKit-LSP its output channel was not disposed, which caused a new entry to be added to the output channel list without removing the old one.
Fixes #839

Dispose LSP's output channel on restart

---

src/TestExplorer/TestRunner.ts
src/utilities/utilities.ts

When debugging an XCTest that fails to build the debugger promise rejects but did not provide an error. The undefined error is caught and passed to `getErrorDescription` which fails to read `stderr` off of it. This caused another error to be thrown and caught at the top level, showing a dialog.
Throw an error string instead of undefined, and handle the undefined error case in getErrorDescription.

Provide error when debugger isn't started

---

src/TestExplorer/TestRunner.ts

As of VS Code 1.90.0 coverage must be recorded before `testRun.end()` is called.
The code was added here
https://github.com/microsoft/vscode/commit/6e69d8b462ff61e8428c5d30d479e7477f04372a#diff-77f48e4fa33d8a37b2d3cd46e4ffdd01200c8128a883aff0af3a4a2ba08ac4cbR556 in https://github.com/microsoft/vscode/pull/212212.

Compute coverage before test run end

---

src/debugger/buildConfig.ts

Set the arguments in the format:
`xctest --XCTest <filter1>,<filter2> test.xctest`
Not:
`xctest --XCTest <filter1> --XCTest <filter2> test.xctest`
Fixes #864

Fix XCTest argument format when debugging

---

src/TestExplorer/TestRunner.ts

Relevant output is included in the Test Results panel, including build failures, so the Terminal is redundant. It would also switch away from the test results view if a test failed regardless of the "testing.openTesting": "openOnTestFailure" setting.
Fixes #862

Silence terminal on test runs

---

package.json

VSCode docs suggest .<extension> is expected. Also adding .swift as it seems like VSCode uses this list to decide which language extensions to recommend in extensions view
Adding "Testing" category

Update language file extensions

---

src/toolchain/toolchain.ts

Swiftly is only available on Linux. Short circuit the toolchain discovery if the platform is macOS or Windows as it will find nothing of interest.

Disable swiftly toolchain discovery on macOS and Windows

---

src/debugger/buildConfig.ts

`xctest` doesn't recognize it and fails to run.

Do not append diagnostics style when debugging XCTests

---

assets/test/defaultPackage/Tests/PackageTests/PackageTests.swift
src/TestExplorer/TestParsers/XCTestOutputParser.ts
src/TestExplorer/TestRunArguments.ts
src/TestExplorer/TestRunner.ts
src/TestExplorer/TestXUnitParser.ts
test/suite/testexplorer/TestExplorerIntegration.test.ts
test/suite/testexplorer/TestRunArguments.test.ts
test/suite/testexplorer/XCTestOutputParser.test.ts
test/suite/testexplorer/utilities.ts

Add a trailing slash to suite test runs so that running a suite like `TestTarget.MySuite` doesn't also run `TestTarget.MySuite2`.
Test runs now register whenever a test starts/completes/records issue that isn't in the expected list of tests to be run. This is used by tests to verify no unknown tests ran.

Don't match similarly named suites

---

src/TestExplorer/TestRunArguments.ts
src/TestExplorer/TestRunner.ts
test/suite/testexplorer/TestRunArguments.test.ts

The xctest executable accepts exact matches, not a regex.

Only add trailing suite slash to XCTests when not debugging

---

src/TestExplorer/TestParsers/TestRunState.ts
src/TestExplorer/TestParsers/XCTestOutputParser.ts
src/TestExplorer/TestRunner.ts
test/suite/testexplorer/MockTestRunState.ts
test/suite/testexplorer/SwiftTestingOutputParser.test.ts
test/suite/testexplorer/XCTestOutputParser.test.ts

If a test fails with XCTAssertEqual or XCTAssertIdentical, parse the result to provide a diff by setting the expected and actual values on TestMessage.
If the string representation of the class used for XCTAssertIdentical is identical, the diff would be identical, so don't show the diff view in that case.
Fixes #654

Show diff for failed XCTAssertEqual and XCTAssertIdentical calls

---

src/toolchain/toolchain.ts

Issue: #887 
On Windows, the LLDB executable is named `lldb.exe` and wasn't being located correctly.

Use proper lldb path on Windows

---

CONTRIBUTING.md

Add instructions that outline how to build and install a .vsix from a local repository. This will help users who want to live on unreleased features without having to build and run the extension in an extension host.

Update CONTRIBUTING.md with instructions on building a .vsix

---

src/debugger/debugAdapter.ts
src/debugger/debugAdapterFactory.ts
src/extension.ts

Issue: #848
We can always register this and that way the user does not need to reload the window when use change to using lldb-dap. Now they can use the updated debug configurations right away

Always register the swift-lldb debug adapter provider

---

src/sourcekit-lsp/LanguageClientManager.ts

Issue: #747 
Adds extra checks surrounding enablement of SourceKit-LSP to improve the wording of the configuration changed notification.

Improve LSP configuration change notification

---

assets/test/defaultPackage/Package@swift-6.0.swift
assets/test/defaultPackage/Tests/PackageTests/PackageTests.swift
test/suite/testexplorer/TestExplorerIntegration.test.ts

Swift testing recently dropped support for Swift 5.10 in https://github.com/apple/swift-testing/pull/467
Our tests were only runing swift-testing tests in 6.0 and up, but the test project was configured to include it as a dependency with 5.10. Bump this up to 6.0.

Update tests to only use swift-testing in 6.0

---

src/TestExplorer/TestParsers/SwiftTestingOutputParser.ts

https://github.com/apple/swift-testing/pull/482 removes the `_testCase` field if the test isn't parameterized. The code that recorded issues relied on this being present. If the issue for a parameterized test case then just extract the test from the testID.

The _testCase field is no longer provided for non paramtereized tests

---

assets/test/defaultPackage/Tests/PackageTests/PackageTests.swift
src/TestExplorer/TestRunner.ts
test/suite/testexplorer/TestExplorerIntegration.test.ts
test/suite/testexplorer/utilities.ts

The Test Explorer automatically shows a pass/fail state based on the state of a TestItem's children. The Test Results in the bottom right were showing suites as passing even if a child test failed. We should simply omit suites from being marked as pass/fail.
Also adds a test for swift-testing parameterized tests.

Don't mark tests with children as pass/fail

---

src/sourcekit-lsp/LSPOutputChannel.ts
src/sourcekit-lsp/LanguageClientManager.ts

Issue: #833
IFF sourcekit logMessage notification includes a logName property, we'll
use a different output channel to not polute the langauge server's main
log. For a known list of logs we'll set them up on startup so we can
control if the log level and/or timestamp is included in the log message.
For the current known indexing log, for example, all messages will be
"Info" so we'll just add timestamp. If new logs are introduced, we'll
show log level and timestamp by default

Allow writing to different sourcekit output channels

---

src/TestExplorer/TestRunner.ts

If we're testing in both frameworks we're going to start more than one debugging session. If both build configurations have the same name LLDB will replace the output of the first one in the Debug Console with the output of the second one. This means the user loses the debug output from the first session.
If they each have a unique name the Debug Console gets a nice dropdown the user can switch between to see the output for both sessions.
This approach has the caveat where VS Code doesn't seem to have an API to remove an old session with a different name from the dropdown.
Specifically, if we do a debugging run of all tests in a XCTest+Swift Testing project this creates two sessions with, for instance, the names "XCTest" and "Swift Testing". However if then we run a single XCTest the …

Give debugging sessions unique names

---

package.json
src/DiagnosticsManager.ts
src/commands.ts
src/configuration.ts
test/suite/DiagnosticsManager.test.ts

Remove stale swiftc diagnostics
Issue: #750
If the user modifies source and SourceKit diagnostics differ, they may
want to cleanup all the old swiftc ones. This will be turned on by
default. The swiftc must match with a former SourceKit one, and once
SourceKit returns a new list of diagnostics, if that matched diagnostic
is no longer there, assume it is fix and remove the matching swiftc error
Tie this to a setting so the user can turn off.
Keep track of all current diagnostics regardless of source to allow for
this cleanup, and has the added benefit that we can update the list
when the diagnosticsCollection setting changes.

Remove stale swiftc diagnostics

---

.vscode/launch.json

Otherwise need to set a breakpoint in .js file under out

Fix src/*.ts source mapping when debugging extension tests

---

src/TestExplorer/TestRunner.ts

When performing a swift-testing test run with code that fails to compile the build output was being discarded. This made it hard to see why tests weren't being run.
This was happening because swift-testing tests don't have their run started until the .swift-testing binary has sent all of its `test` events, which enumerate the parameterized test cases. This means that build output is witheld until the run starts.
If there is a compile error, unless we call `testRunStarted()` to flush the buffer of test result output, nothing is printed to the Test Results panel and build output is lost.

Ensure build output is printed on swift-testing compiler error

---

package.json

Move the following settings in to their own group. Their ID does not change so there is no need to deprecate them or make code changes.
- `swift.excludePathsFromPackageDependencies`
- `swift.showBuildStatus`
- `swift.showCreateSwiftProjectInWelcomePage`
- `swift.openAfterCreateNewProject`
Issue #901

Add UI Settings Group

---

src/TestExplorer/LSPTestDiscovery.ts
src/sourcekit-lsp/lspExtensions.ts
test/suite/testexplorer/LSPTestDiscovery.test.ts

Adds comprehensive tests for LSP test discovery. Removes the capabilities cache since all it was doing was short circuiting a nested property lookup.

Add tests for LSP test discovery

---

src/DiagnosticsManager.ts
test/suite/DiagnosticsManager.test.ts

This will fix the issue mentioned. There is also an issue that SourceKit and swiftc have different ranges reported which I'll reach out about
Issue: #912

Make sure swiftc diagnostics are cleaned up after new swift commands

---

package.json
src/TestExplorer/TestRunner.ts
src/commands.ts
src/commands/captureDiagnostics.ts
src/extension.ts
src/sourcekit-lsp/LanguageClientManager.ts
src/toolchain/toolchain.ts
src/ui/SwiftOutputChannel.ts
test/suite/DiagnosticsManager.test.ts
test/suite/ui/SwiftOutputChannel.test.ts

Adds a new command that users can use to help generate bug reports for the extension itself. The Capture VSCode Swift Diagnostic Logs command will create a new folder in a temporary directory that contains:
- Swift version and path information
- Extension logs
- Any diagnostics in the Problems pane
Users can copy the folder path or, if they're on macOS, open it in Finder. From there they can zip and attach these files to a GitHub issue. We'll want to update the New Issue Template with instructions on how to capture and attach these logs.
Fixes #842

Add Swift: Capture VSCode Swift Diagnostic Logs command

---

src/TestExplorer/TestDiscovery.ts
src/TestExplorer/TestExplorer.ts
test/suite/testexplorer/TestDiscovery.test.ts

Add tests that ensure TestClasses returned from the LSP (or elsewhere) are properly added to the vscode TestController.

Add tests for Test Discovery

---

src/DiagnosticsManager.ts
src/ui/SwiftBuildStatus.ts
src/utilities/tasks.ts
test/suite/DiagnosticsManager.test.ts

Stop parsing diagnostics once build is complete
Issue: #925

Don't show XCTest failures under Problems view

---

src/TestExplorer/TestRunner.ts

Parameterized test results should inherit the tags of their parent. This keeps them visible in the Test Explorer when tests are filtered by tag.

Parameterized test results should inherit tags

---

src/ui/ToolchainSelection.ts

The URL for installing Swiftly has changed to https://swiftlang.github.io/swiftly

Fix the URL for Swiftly

---

src/TestExplorer/LSPTestDiscovery.ts

With https://github.com/swiftlang/sourcekit-lsp/pull/1530, `sourcekit-lsp` will start prepending a test target's name to the test id. This helps disambiguate when there are two identically named suites in two different test targets.
To maintain the current behaviour with older sourcekit-lsp versions only prefix the test target if it isn't already there.
- Depends on https://github.com/swiftlang/sourcekit-lsp/pull/1530
- Fixes #936

Don't prepend target id to test ids if it exists

---

src/terminal.ts

I originally added logic to avoid adding to `PATH` if the `swift.path` setting already existed. However, this leads to weird behaviour if the path is already there, but is lower in the list. Now the Swift extension will always add `swift.path` to the terminal `PATH` as long as the user has overridden it in settings.
Issue: #914

always add Swift path to terminal PATH

---

src/sourcekit-lsp/LanguageClientManager.ts
src/sourcekit-lsp/lspExtensions.ts
src/sourcekit-lsp/peekDocuments.ts

This PR utilises the following PR in sourcekit-lsp: https://github.com/swiftlang/sourcekit-lsp/pull/1479
This takes a custom `PeekDocumentsRequest` and opens a peek window to display each given document. In the current state, this request is being used by `ExpandMacroCommand` in sourcekit-lsp to display Macro Expansions.
To check out this functionality, build the `main` branch of `sourcekit-lsp`. Then, configure your "swift.sourcekit-lsp.serverPath" to the built sourcekit-lsp. (This step will not be necessary once this build of sourcekit-lsp is packaged with Swift itself given that you use the latest Swift Toolchain)
*Since the macro expansions feature is behind an experimental feature flag*, configure your swift extension settings as follows:
```
"swift.sourcekit-lsp.serverArguments": [ …
```

Handle `PeekDocumentsRequest` to show documents from sourcekit-lsp (like, Macro Expansions) in a "peeked" editor 

---

src/sourcekit-lsp/peekDocuments.ts

During the swiftlang org transition CI was not running, which failed to catch this missing licence declaration.

Add missing licence header to peekDocuments.ts

---

src/terminal.ts

The shell has the ability to add/change environment variables after startup via configuration files. Use `applyAtShellIntegration` to overcome this for the automatic terminal configuration. Terminal profiles, unfortunately, do not have this option. In this case we have to grab the created terminal and inject our environment variables using a command after the terminal starts up.
Issue: #914

Apply changes to PATH after terminal creation

---

src/coverage/LcovResults.ts

Code coverage reports are filtered to omit the tests themselves, as well as all library code checked out in `.build`. This is done with the `--ignore-filename-regex` argument passed to llvm-cov's `export` command.
The current filter is defined as
`Tests|swift-testing|Testing|.build|Snippets|Plugins`, and filters out files if they contain any of those strings in their filename. This can be too aggressive, and was filtering out valid files under test and omitting them from reports. For instance the file [`SwiftTestingScanner.swift`](https://github.com/swiftlang/sourcekit-lsp/blob/b016a0de4f405089284f0628882f30ec7b412f0e/Sources/SourceKitLSP/Swift/SwiftTestingScanner.swift#L4) is filtered out of the coverage report for the sourcekit-lsp repository despite being a valid file to be covered. …

Improve specificity of ignored files in coverage reports

---

package.json
src/configuration.ts
src/coverage/LcovResults.ts

Adds `swift.excludeFromCodeCoverage` which provides a list of absolute or relative paths to exclude from the code coverage reports. Relative paths are specified from the workspace root.
Issue: #963

Add setting to exclude files/directories from code coverage reports

---

package.json
src/TestExplorer/LSPTestDiscovery.ts
src/WorkspaceContext.ts
src/commands.ts
src/contextKeys.ts
src/sourcekit-lsp/lspExtensions.ts

Adds a command to trigger a re-indexing of the open project. Should only be needed when background indexing is enabled and it gets out of sync. While that is a bug, this can act as a temporary workaround.
Blocked By: https://github.com/swiftlang/sourcekit-lsp/pull/1561, https://github.com/swiftlang/sourcekit-lsp/pull/1563
Issue: #939

Add Re-Index Project Command

---

src/commands.ts

Show a warning informing the user that they shouldn't have to reindex the project, and doing so indicates a bug in SourceKit-LSP. Show a button that links out to the SourceKit-LSP issue creation page, prepopulating the issue title as "Symbol Indexing Issue".
Requested by @ahoppen in https://github.com/swiftlang/vscode-swift/pull/964#issuecomment-2231169148

Show warning message when reindexing project

---

src/debugger/buildConfig.ts

The windows debug config was delegating to the macOS debugging config, which runs xctests through a prebuilt executable included in the toolchain. On Windows, like Linux, an xctest executable is built during `swift test`/`swift build --build-tests`. This should be used instead.
This patch brings the Windows config in line with what we do on Linux.
Issue: #970

Use correct xctest path when debugging on Windows

---

src/TestExplorer/TestRunner.ts
src/debugger/buildConfig.ts

Add XCTest.dll to PATH and supply arguments when running swift-testing tests. Also fixes extra whitespace in output when debugging XCTests on Windows.

Add XCTest.dll path to Path when testing on Windows

---

src/sourcekit-lsp/LanguageClientManager.ts

Provide the LSP with a mapping of supported code lenses to commands. SourceKit-LSP will provide code lenses for running and debugging applications with a @main function only when we configure the commands we support.
Blocked by https://github.com/swiftlang/sourcekit-lsp/pull/1556

Inform LSP of supported code lenses

---

src/sourcekit-lsp/LanguageClientManager.ts
src/ui/SwiftOutputChannel.ts
test/suite/ui/SwiftOutputChannel.test.ts

If SourceKit-LSP fails to initialize, typically because of unrecognized launch arguments, don't attempt to restart it and limit the number of erorr dialogs to just one descriptive one. Clicking the "Go to Output" button on this dialog takes you to the SourceKit-LSP Output panel which now shows the SourceKit-LSP launch error.

Improve error reporting when SourceKit-LSP fails to start

---

src/sourcekit-lsp/LanguageClientManager.ts
src/sourcekit-lsp/getReferenceDocument.ts
src/sourcekit-lsp/lspExtensions.ts
src/sourcekit-lsp/peekDocuments.ts

This PR utilises the newly introduced `GetReferenceDocumentRequest` to resolve the contents of macro expansion obtained from `PeekDocumentRequest` through a new scheme.
This change doesn't cause any behavioural changes facing the user.
The `GetReferenceDocumentRequest` implemented in sourcekit-lsp allows it to not create temporary files whenever it makes a `PeekDocumentRequest`.
Accompanying PR in sourcekit-lsp repository: https://github.com/swiftlang/sourcekit-lsp/pull/1567
------
[Expansion of Swift Macros in Visual Studio Code - Google Summer Of Code 2024](https://summerofcode.withgoogle.com/programs/2024/projects/zQNf7ztP)
@lokesh-tr @ahoppen @adam-fowler

Retrieve macro expansions for `PeekDocumentsRequest` through `GetReferenceDocumentRequest` instead of showing temporary files

---

src/TestExplorer/TestParsers/TestEventStreamReader.ts
src/TestExplorer/TestRunner.ts
src/debugger/buildConfig.ts
src/toolchain/toolchain.ts

With the merge of https://github.com/swiftlang/swift-package-manager/pull/7766 a `swift build --build-tests` produces a single binary that contains both XCTests and swift-testing tests.
Update the build configs when debugging tests to use this new unified test binary if it exists.
To determine if we're running a unified binary on macOS we can check for the presence of the swiftpm-testing-helper, which is used to run the swift-testing tests in the unified binary.
This utility isn't required on Windows and Linux as the test binary can be invoked directly. To determine if we're running a unified binary we check if the latest build produced a .swift-testing binary in the build folder. If it doesn't exist, or if it does exist but its `mtime` is older than the last build start time, we know its …

Support a Unified Test Binary

---

src/coverage/LcovResults.ts
src/debugger/buildConfig.ts

With the introduction of the new unified testing binary we need to supply it to lcov export instead of the .swift-testing binary.

Use unified test binary when computing coverage

---

src/TestExplorer/TestRunner.ts
src/ui/SwiftBuildStatus.ts

Is hanging build status when debugging a test. The build task ends but the status keeps churning, never hiding itself. For some reason the execution's emitter never fires. For now putting this fix in to prevent the hang.

Fix hanging build status in vscode 1.92

---

src/TestExplorer/TestRunner.ts
src/tasks/SwiftTaskProvider.ts

We were naively transforming the arguments of the returned Build All task to create one that would run a release version of Build All. Unfortunately the `task.execution` remained the same and so while upon inspection the task looked like it would run a release build it was not.
Create two separate versions of the Build All task, one for Debug and one for Release builds, and use the release version when building tests in release mode.

Create separate Build All Release task

---

src/TestExplorer/TestRunner.ts
src/debugger/buildConfig.ts

We were checking the `mtime` of the `<ProductName>.swift-testing` binary to determine if it was produced by the latest build. The issue with this is that when you run tests over and over without making any code changes the binary is never rewritten because it is already up to date.
Instead of checking the `mtime` of the .swift-testing binary in the build folder to determine if it was produced, use the build `description.json` and check the builtTestProducts list to see if the legacy `.swift-testing` binary was produced by the latest build.

Use build description to check for unified testing binary

---

src/tasks/SwiftTaskProvider.ts

With #1000 merged in, we are now showing the Release variant of the build all task in the list of provided tasks when running the "Run Task" command. We don't want that since only needed for debugging a test in release mode

Don't add "Build All - Release" task to list of provided tasks

---

docs/settings.md
package.json
src/configuration.ts
src/extension.ts
src/sourcekit-lsp/LanguageClientManager.ts

Adds a setting that will send `backgroundIndexing: true` along with a `backgroundPreparationMode` in the SourceKit-LSP initialization request.
The server must be restarted when either of these settings are changed.
Issue: #987

Add setting for background indexing

---

assets/test/defaultPackage/Tests/PackageTests/PackageTests.swift
src/TestExplorer/TestParsers/SwiftTestingOutputParser.ts
src/TestExplorer/TestParsers/TestRunState.ts
src/TestExplorer/TestParsers/XCTestOutputParser.ts
src/TestExplorer/TestRunner.ts
test/suite/testexplorer/MockTestRunState.ts
test/suite/testexplorer/SwiftTestingOutputParser.test.ts
test/suite/testexplorer/TestExplorerIntegration.test.ts
test/suite/testexplorer/XCTestOutputParser.test.ts

For both XCTests and swift-testing associate each line of the output with the appropriate test. This lets users view just the output for a given test via the test history pane, and also shows the output for the given test when navigating through the test run issues via prev/next issue buttons. Clicking a test issue in the test history pane highlights the issue inline and then clicking the "Go to Previous Test Failure" button will show complete output captured for the test.
A current limitation is this does not capture output from user `print()` calls in the same order they'd appear in stdout. We do the best we can to capture prints from stdout and inject them in to the test output, but because we're mixing this with output generated from the JSON event stream the exact position of print …

Associate test run output with individual tests

---

src/TestExplorer/TestRunner.ts
src/tasks/SwiftProcess.ts

If the user hits ctrl+c during a task we want to treat that as an unsuccessful process execution and stop proceeding.
Forward the signal and ignore the exit code of a signal is present on process exit.
Issue: #1001

Forward signal as exit code

---

test/suite/testexplorer/TestExplorerIntegration.test.ts

`swift-testing` has updated the message it uses when recording an unconditional issue, as of:
https://github.com/swiftlang/swift-testing/commit/b7ef61e773292f5f28c02d9c269c44979123dcea

Fixup test w/ newer issue failed message

---

docs/contributor/test-strategy.md
package.json
src/sourcekit-lsp/LanguageClientManager.ts
test/unit-tests/MockUtils.ts
test/unit-tests/sourcekit-lsp/LanguageClientManager.test.ts
test/unit-tests/ui/SwiftBuildStatus.test.ts

* Add new `mockConstructor` utility for returning a mock instance when a constructor is called. This should be used as sparingly as possible, with dependency injection being preferred
* Add an initial set of tests for the LanguageClientManager
* Add some extra `await`s so unit tests know when function is done

Add unit tests for the LanguageClientManager

---

src/configuration.ts
src/debugger/debugAdapter.ts
src/debugger/debugAdapterFactory.ts
src/toolchain/toolchain.ts

The `lldb-dap` binary is not in the toolchain directory on Darwin like it is on Linux and Windows. Use `xcrun -find lldb-dap` on Darwin to find the correct `lldb-dap` location.

Fix lldb-dap path on Darwin

---

package.json
src/TestExplorer/TestExplorer.ts
src/TestExplorer/TestRunner.ts
src/commands.ts
test/suite/testexplorer/TestExplorerIntegration.test.ts

Adds two new items to the context menu when you right click a test in the test explorer:
- Run Multiple Times
- Run Until Failure
Selecting either of these promts with a text input where the user can input how many times they want to run the test(s).
If the user selected Run Until Failure the tests will be run a maximum number of times, stopping at the first iteration that produces a failure.
A current limitation in VS Code is if you have multiple tests selected in the Test Explorer (by shift or ctrl clicking them) only the first is passed to the command.
Issue: #832

Add "Run Test Multiple Times"

---

src/WorkspaceContext.ts
src/sourcekit-lsp/LanguageClientManager.ts
src/sourcekit-lsp/getReferenceDocument.ts
src/sourcekit-lsp/peekDocuments.ts

This PR makes VS Code to recognise files with scheme "sourcekit-lsp", thereby allowing them to be handled by SourceKitLSP and provide Semantic Functionality. Specifically, This PR enables Semantic Functionality in Macro Expansion Reference Document's Peeked Editors.
Refer to the sourcekit-lsp PR below for more information on what semantic functionality is supported as of now.
Accompanying PR in sourcekit-lsp repository: https://github.com/swiftlang/sourcekit-lsp/pull/1610
------
[Expansion of Swift Macros in Visual Studio Code - Google Summer Of Code 2024](https://summerofcode.withgoogle.com/programs/2024/projects/zQNf7ztP)
@lokesh-tr @ahoppen @adam-fowler

Allow VS Code to recognise files with "sourcekit-lsp" scheme to provide Semantic Functionality through SourceKitLSP

---

src/sourcekit-lsp/peekDocuments.ts

While expanding nested macros, the peeked window is supposed to appear at the same position as the previous one. The "editor.action.peekLocations" command causes the previous peeked editor to close without reopening with the new contents if invoked at the same position in the same file.
This fixes the issue by having a workaround in which we open a dummy peeked editor so that the previous peeked editor is closed, followed by opening the actual peeked editor so that, we have the peeked editor to always display at the same position in the same file while expanding a macro.
This issue is not macro expansion specific and exists in general.
Semantic Functionality and nested macro expansions PR in sourcekit-lsp where the issue was faced initially: …

Fix peeked editor closing without reopening with new contents when triggered again at the same position in the same file

---

.vscode-test.js

The current behaviour will not include files with 0% coverage.
Address this by adding the correct flag.
Issue: swiftlang#1021

Include all files under src in coverage report

---

src/TestExplorer/TestParsers/SwiftTestingOutputParser.ts
test/suite/testexplorer/SwiftTestingOutputParser.test.ts
test/suite/testexplorer/TestExplorerIntegration.test.ts

If a swift-testing `#expect` macro has preceding comments they are sent along with the expectation failure text as entries in the EventMessage array. Pull them out of the array so they don't appear as their own separate issues and append them to the actual issue text.
Also fixes up some of the issue message colorization to be more consistent with how swift-testing behaves on the command line.

Associate comment details on #expect w/ test issue

---

package.json
src/commands.ts
src/commands/newFile.ts
test/suite/commands/NewFile.test.ts

Add a command that creates a new Swift File. Add it as an option to the File > New File picker. Add it as an option when right clicking a folder in a Swift project context. Add a keybinding of Opt+S Opt+N (or Alt+S Alt+N) to create a new Swift file.

Add New Swift File command

---

assets/test/.vscode/settings.json
assets/test/defaultPackage/Tests/PackageTests/PackageTests.swift
package.json
src/TestExplorer/TestRunner.ts
src/configuration.ts
src/coverage/LcovResults.ts
src/debugger/buildConfig.ts
src/tasks/SwiftTaskProvider.ts
test/suite/WorkspaceContext.test.ts
test/suite/testexplorer/TestExplorerIntegration.test.ts

Adds a new setting that allows users to specify extra arguments when running `swift test` and `swift build --build-tests` during a test run from inside VS Code.
For example users could set `swift.testBuildArguments: ["-Xswiftc", "-DTEST"]` to enable code guarded by an `#if TEST` compiler directive.
This patch required reworking how we do a build all before starting a debug session since using the premade Build All tasks do not allow for dynamically customizing arguments.

Add swift.testBuildArguments Setting

---

package.json

We can add the Run Multiple Times and Run Until Failure menu items onto the green play button icon in the gutter of the editor. This is in addition to having it on individual items in the test explorer.

Add Run Multiple menu items to test item gutter

---

src/TestExplorer/TestParsers/XCTestOutputParser.ts
test/suite/testexplorer/TestExplorerIntegration.test.ts

The lastTestItem was not being set right away when a test succeeded because tests were being marked as passed in a second pass of the XCTest output after a run completed.
Going by the removed comment this second pass was added to disambiguate passing tests with the same suite/test name across multiple targets.
However, the test target is present in the `testName` used to look up a test's index. For instance, it may look like
`TestTargetA/Suite/testFoo` and so would not be identical to `TestTargetB/Suite/testFoo`, and so we get the correct `testIndex` for either test.

Mark XCTests as passed without a second pass over the output

---

.vscode-test.js
.vscode/launch.json
package.json
test/suite/BackgroundCompilation.test.ts

Issue was the dist/extension.js file was what vscode-test was running as the extension as it was what was specified as the entry point in the package.json. So The globalWorkspaceContextPromise helper we use in a lot of tests to make sure the extension is activated, returns an instance of the WorkspaceContext. Any behaviour stimulated through that context is missed from the coverage report, and also any breakpoint hits are ignored. So for example the BackgroundCompilation instance that is created on extension activation was left out of the coverage report.
To fix, only bundle to a single extension.js file when packaging a vsix. When debugging or running tests we transpile all the files individually. The dist/extension.js file is still used when activating, but sourcemap now works so the …

Fix coverage report

---

package.json
src/TestExplorer/TestExplorer.ts
src/TestExplorer/TestUtils.ts

Keep a flattened list of swift Test Explorer test IDs in the context and use a `when` clause on the context menu items to only show them on Swift tests in the Text Explorer.
Issue: #1047

Show Swift test explorer context menu items only for Swift tests

---

src/sourcekit-lsp/LanguageClientManager.ts
src/sourcekit-lsp/uriConverters.ts
test/unit-tests/sourcekit-lsp/uriConverters.test.ts

`vscode.uri` fails to round-trip URIs that have both a `=` and `%3D` (percent-encoded `=`) in the query component.
```ts
vscode.Uri.parse("scheme://host?outer=inner%3Dvalue").toString() -> 'scheme://host?outer%3Dinner%3Dvalue'
vscode.Uri.parse("scheme://host?outer=inner%3Dvalue").toString(/*skipEncoding*/ true) -> 'scheme://host?outer=inner=value'
```
The SourceKit-LSP scheme relies heavily on encoding options in the query parameters, eg. for Swift macro expansions and the values of those query parameters might contain percent-encoded `=` signs.
To work around the round-trip issue, don't percent-decode any components of the URI and then use `toString(/*skipEncoding*/ true)` to serialize it into a string again.
Technically, we should percent-decode authority and path but if we do that, we …

Work around `Uri` round-tripping issue in VS Code for `sourcekit-lsp` scheme

---

src/debugger/buildConfig.ts

These have been stabilized and the `experimental` versions of the flags have been deprecated.

Remove `experimental` from swift-testing flags

---

src/TestExplorer/TestParsers/SwiftTestingOutputParser.ts
test/suite/testexplorer/SwiftTestingOutputParser.test.ts

Instead of reconstructing the swift-testing output from a combination of stdout and the JSON event stream, simply pass stdout through directly and use that as the test results log. Use the JSON event stream to drive test pass/fail/skip/issue/etc behaviour.
This resolves a race condition between the JSON event stream and stdout interleaving output in an incorrect order.
This approach has the drawback of no longer associating individual lines of output derived from the JSON event stream with a specific test, however this was offering limited benefit since user output wasn't captured in this way. Once every line of output can be accounted for in the JSON event stream we can add this functionality back in with user output included.
Issue: #1054

Use swift-testing stdout as test results log verbatim

---

src/commands.ts
src/commands/openPackage.ts
test/suite/commands/openPackage.test.ts

The language status item has a link to the Package.swift file. If the user has a version specific manifest file in the form `Package@swift-[version].swift` where the version matches their currently installed Swift version, open that Package.swift instead.
Issue: #1070

Open version specific manifest if applicable

---

src/utilities/native.ts

* VSCode has moved node-pty out of the asar bundle and into a typical node_modules folder structure
* If old way fails, fall back on new insiders path

Fix extension activation for insiders build

---

assets/test/defaultPackage/Tests/PackageTests/PackageTests.swift
src/TestExplorer/TestRunArguments.ts
src/debugger/buildConfig.ts
src/utilities/utilities.ts
test/suite/testexplorer/TestExplorerIntegration.test.ts
test/suite/utilities/utilities.test.ts

The regex to specify a specific XCTest to run did not specify that there should be no more text after the test ID. As a result, attempting to run a test like `testFoo` would also run a test in the same suite called `testFooBar`.
Swift-testing tests do not have the same issue as their IDs include the function parentheses and argument labels, and no text can appear after the closing paren.
Issue: #1084

Add line terminator to XCTest filter regex

---

src/debugger/buildConfig.ts
src/debugger/debugAdapterFactory.ts
src/toolchain/toolchain.ts
test/suite/tasks/SwiftTaskProvider.test.ts

Fixes up some issues with Windows debugging found in the latest 6.0 toolchain:
- Add Testing.dll to the PATH same as XCTest.dll
- Don't append .exe when debugging testing binaries
- Don't follow incorrectly created symlink at `.\build\debug`, point to real folder at the build triple path

Fix Several Windows Debugging Issues

---

.vscode/launch.json
assets/test/.vscode/tasks.json
src/tasks/SwiftTaskProvider.ts
src/ui/StatusItem.ts
test/suite/tasks/SwiftTaskProvider.test.ts
test/unit-tests/tasks/SwiftTaskProvider.test.ts
test/utilities.ts

* Move what can be to the unit level
* Add in more unit test cases to cover additional branches
* Add in integration tests where needed to increase coverage
Issue: #1038

Improve tests for "swift" tasks

---

assets/test/.vscode/tasks.json
assets/test/command-plugin/Package.swift
assets/test/command-plugin/Plugins/command-plugin/command-plugin.swift
src/FolderContext.ts
src/tasks/SwiftPluginTaskProvider.ts
test/suite/tasks/SwiftPluginTaskProvider.test.ts
test/unit-tests/tasks/SwiftPluginTaskProvider.test.ts

* Wrote mostly unit tests for resolveTask and provideTasks
* Wrote some integration tests to make sure the vscode task APIs like fetchTasks and executeTasks work with these tasks
* Make sure can run a plugin task provided by the extension or resolved from the tasks.json
Issue: #1038

Add tests for swift-plugin tasks

---

src/toolchain/toolchain.ts

If the user's toolchain doesn't contain swift-testing its possible that the SWIFT_TESTING_VERSION key is missing from the platform manifest plist. If this is the case, log and return undefined instead of erroring and halting Toolchain setup.
Issue #1096

Warn instead of error on missing test framework version

---

src/debugger/debugAdapter.ts

The CodeLLDB extension expects the debug adapter to be called `lldb`. If we are using it and we don't call `registerDebugAdapterTrackerFactory` with `lldb` as the adapter name then we fail to get logs in the debugSessionCallback when running tests. This prevents XCTests results from being parsed, and hides the swift-testing output.
Revert a portion of #1024 that always set the debug adapter name to `swift-lldb` and use `lldb` when we're using CodeLLDB as the debug adapter.
Issue #1100

Revert using universal debug adapter name

---

docker/Dockerfile
docker/test.sh

Use `rsync` to exclude copying unnecessary files in to the working directory. This mainly helps speed up running the containers during local development since the developer may already have `node_modules`, `.build`, and `.vscode-test`, all of which can be quite large.

Only copy required files into Docker work directory

---

test/integration-tests/DiagnosticsManager.test.ts

It appears there is an issue in Swift 5.6 where a line of diagnostics output is improperly cleared from the terminal by the build progress prints. When this happens the tests potentially miss diagnostics they expect to see. This only happens on Swift 5.6, so to ensure these tests pass consistently, skip them there.

Disable flakey diagnostics tests in Swift 5.6 and below

---

src/TestExplorer/TestRunner.ts

Occasionally a swift-testing test can start printing output before the test start JSON event is recieved over the named pipe. This output was always recorded to the test run, but wasn't necessarily captured in the structure used to record test results for the vscode-swift unit tests.
This would cause the `swift-testing: Runs passing test` test to occasionally fail when it couldn't find the output line printed during the test, because it was printed before the test start event was recieved.
Record the output no matter when it occurs so that it can be verified in the tests correctly.

Fix swift-testing test not always capturing terminal output

---

package-lock.json
package.json
src/extension.ts
test/common.ts

The stack traces that we get from users' logs and the ones within the tests aren't very helpful since they point to transpiled code. Use the `source-map-support` module to automatically re-map stack traces in errors to their original source location to make it easier to find problems in the future. I've also updated our build scripts to always generate source maps even when packaging for production.

Use source-map-support to provide better stack traces

---

test/unit-tests/debugger/lldb.test.ts

There's a unit test that gets skipped if the platform isn't Windows in order to test some functionality of `getLLDBLibPath()`. Use `mockGlobalValue()` here to set the value of `process.platform` so that the test can run on all platforms.

Fix unit test that gets skipped if not on Windows

---

docs/contributor/test-strategy.md
scripts/soundness.sh

Check for broken links as part of the `soundness` job. The job will fail if a link returns a non 200 HTTP status code.
Fixes a broken link in `./docs/contributor/test-strategy.md`

Check for broken links in CI

---

test/integration-tests/extension.test.ts

VS Code recently updated its built-in TypeScript Language Server to v5.6.2 which shows an error in `extension.test.ts` that is not present in CI (currently this repo uses TypeScript 5.5.2). However, this is a legitimate issue as the `rootWorkspaceFolder` variable can indeed be undefined.
I've simply fixed up the code in this area to properly handle the fact that the variable can be undefined as well as an issue where a `throw` would not have been handled properly. However, I'm hesitant to jump to TypeScript 5.6.2 since TypeScript ESLint currently does not support 5.6.

Fix error in extension.test.ts

---

.vscode-test.js
.vscode/extensions.json
.vscode/launch.json
.vscode/settings.json
.vscode/tasks.json
CONTRIBUTING.md
package.json
tsconfig.json

Build the test code and source into `./dist` rather than `./out`. This fixes two issues:
1. The test code used to import different source modules from VS Code which caused issues during integration tests.
2. The code coverage for integration tests was inconsistent as it was coming from code executed from both the `dist` and `out` folders.
The downside of this approach is that building in `watch` mode can overwrite files when you try to run a test at the same time. Thankfully, this can be easily solved by performing a separate build every time the extension host is launched. There is no noticeable performance impact with this as `esbuild` is quite fast.

Ensure that integration tests execute the same code as the extension

---

src/TestExplorer/TestParsers/TestRunState.ts
src/TestExplorer/TestParsers/XCTestOutputParser.ts
src/TestExplorer/TestRunner.ts
test/integration-tests/testexplorer/MockTestRunState.ts
test/integration-tests/testexplorer/XCTestOutputParser.test.ts

Capture the XCTest output associated with suites and assocaite it with the test item that appears in the test run history. This makes it easy to see the start/end time output of a suite by clicking on it.
In order to capture the test target for a suite we need to wait for the first test that executes within that suite in order to get the target. For whatever reason, XCTest does not print a suites target, only a test's when it starts. The approach is if a suite starts, queue output up until the first test run, then associate the last line of queued output with the test target found on the started test. Lines before the last line are not assocaited with a test (these are typically the top level suite like "Selected Tests" or the test target name.
Issue: #1148

Associate XCTest suite start/stop with test item

---

src/TestExplorer/TestRunner.ts
src/commands/testMultipleTimes.ts
src/utilities/cancellation.ts
test/integration-tests/testexplorer/TestExplorerIntegration.test.ts

There are two ways to cancel a running test, one via the Cancel button at the top of the test explorer, and the other using the Cancel button in the test run tree in the bottom right of the Test Results output panel.
We were handling cancellation via the first method, but the one in the test run tree uses a different cancellation token to indicate a test run should be cancelled. It is is found on the constructed vscode.TestRun.
In our situation we want both of these to do the same thing, cancel the build if its running and stop the test run if its running.
Create a `CompositeCancellationToken` that wraps both these child tokens and performs cancellation if either of them request cancellation.
This approach also centralizes the cancellation logic to the `TestRunProxy`, removing the need to …

Improve Test Cancellation

---

src/TestExplorer/TestDiscovery.ts
src/TestExplorer/TestRunner.ts
src/utilities/utilities.ts

When running a swift-testing test that takes arguments the results are added to the Test Explorer showing their pass/fail status. At this time these tests cannot be run with a specific argument so these tests should not be marked as runnable. This prevents the "Run", "Debug" and "Coverage" buttons from appearing on the test items in the explorer.
Issue: #1147

Don't mark swift-testing test case results as runnable

---

src/toolchain/toolchain.ts
src/utilities/filesystem.ts
test/integration-tests/utilities/filesystem.test.ts
test/unit-tests/utilities/filesystem.test.ts

* Lower some tests from integration to the unit level
* Template the expandFilePathTilda function to not mock platform paths
* Add more tests

Add some more unit tests for "filesystem" utility module

---

.unacceptablelanguageignore
CHANGELOG.md
CONTRIBUTING.md
NOTICE.txt
src/TestExplorer/TestExplorer.ts
src/tasks/SwiftProcess.ts
src/tasks/SwiftPseudoterminal.ts
test/MockUtils.ts
test/fixtures.ts

Rewords documentation and APIs that don't meet Apple's unacceptable language standards. Unblocks the CI check that runs the check-unacceptable-language.sh script.
Issue: #1161

Unblock CI check for unacceptable language

---

.github/dependabot.yml

Major update breaks dependabot. Will leave until a later time when we can properly move to version 8
https://github.com/swiftlang/vscode-swift/pull/1160
Issue: #1136

Don't allow major updates of typescript-eslint

---

.github/dependabot.yml

Major update breaks dependabot. Will leave until a later time when we can properly migrate to the next major version of the various chai dependencies.
https://github.com/swiftlang/vscode-swift/pull/1167
Issue: #1136

Don't allow major updates of chai

---

.github/dependabot.yml

Major update breaks dependabot because require going to node.js 20. Will leave until a later time when we can properly migrate to the next major version of node.js and vsce
https://github.com/swiftlang/vscode-swift/pull/1171
Issue: #1136

Don't allow major updates of vsce

---

test/integration-tests/testexplorer/TestExplorerIntegration.test.ts

Add on to the parameterized integration test to verify that there is a test case added for each argument, and that they are not runnable.

Test parameterized test children aren't runnable

---

docker/test.sh
package.json
scripts/soundness.sh
src/utilities/native.ts

This allows us to turn off the licence check GitHub Action temporarily until we can merge #1176, which unblocks #1159, allowing us to start using the GitHub Actions CI flow.

Temporarily reenable old licence check

---

src/TestExplorer/TestRunArguments.ts
test/integration-tests/testexplorer/TestRunArguments.test.ts

If the user tried to run a test suite that had as many tests as there are test suites in the module we improperly simplified the test arguments to run all suites in the module.
This patch fixes this behaviour, and also introduces more robust tests.
Issue: #1183

Fix improper test argument simplification

---

src/debugger/buildConfig.ts
src/debugger/launch.ts
src/debugger/lldb.ts

- The original GH Actions change has this option added to build config, but not to other configurations like launch and snippet.
- This causes commands that passes through debugger but disregard breakpoints like the run build command to fail in CI.
- This would also show up once we have a nightly workflow going.
- Both issues described above will be addressed by this PR.
Issue: #1198

Add disableASLR to all debug configurations

---

test/integration-tests/ui/SwiftOutputChannel.test.ts

Output channels were not designed to be created and immediately disposed because they're added to the disposable store internal to VS Code asynchronously.
Issue #1197

Fix warnings printed during SwiftOutputChannel tests

---

src/commands.ts
src/commands/build.ts
src/debugger/launch.ts
src/ui/ReloadExtension.ts
src/utilities/command.ts
src/utilities/commands.ts
test/integration-tests/BackgroundCompilation.test.ts
test/integration-tests/DiagnosticsManager.test.ts
test/integration-tests/commands/build.test.ts
test/integration-tests/editor/CommentCompletion.test.ts
test/integration-tests/testexplorer/TestExplorerIntegration.test.ts
test/integration-tests/testexplorer/utilities.ts
test/unit-tests/ui/ReloadExtension.test.ts
test/utilities/debug.ts

- Validate the workflow of user calling the Swift: Run Build/Clean Build/Debug Build commands.
- Ensure Swift: Run Build will not get blocked by pre-set breakpoint.
- Ensure Swift: Clean Build will result in a cleaned up .build folder.
- Ensure Swift: Debug Build will stop on a breakpoint and resume.
Issue: #1184

Add integration tests for build commands

---

.github/workflows/pull_request.yml

Reorder the jobs so that the tests appear at the top of the list. This should make it so developers don't have to scroll the jobs list to see what tests failed.

Sort test actions at the top of the workflow jobs list

---

test/integration-tests/commands/build.test.ts

Right now the clean command test relies on the build command test to complete. That's not behaviour we want. Ideally tests should be able to run in isolation.
Issue: #1184

Make sure build command tests has no ordering requisite

---

src/TestExplorer/TestRunArguments.ts
test/integration-tests/testexplorer/TestRunArguments.test.ts

When right clicking a test target and debugging the tests, no XCTests are run.
The test run argument simplification code would simplify too much when debugging a test target; the `xctest` binary does not accept a test target as an `-XCTest` argument. Only fully specified test names or test suites are permitted.
Issue: #1207

Fix debugging entire XCTest targets

---

.vscode/launch.json
src/DiagnosticsManager.ts
src/WorkspaceContext.ts
src/extension.ts
src/sourcekit-lsp/LanguageClientManager.ts
test/integration-tests/BackgroundCompilation.test.ts
test/integration-tests/DiagnosticsManager.test.ts
test/integration-tests/ExtensionActivation.test.ts
test/integration-tests/WorkspaceContext.test.ts
test/integration-tests/commands/build.test.ts
test/integration-tests/commands/dependency.test.ts
test/integration-tests/commands/runTestMultipleTimes.test.ts
test/integration-tests/debugger/lldb.test.ts
test/integration-tests/extension.test.ts
test/integration-tests/tasks/SwiftExecution.test.ts
test/integration-tests/tasks/SwiftPluginTaskProvider.test.ts
test/integration-tests/tasks/SwiftTaskProvider.test.ts
test/integration-tests/tasks/TaskManager.test.ts
test/integration-tests/tasks/TaskQueue.test.ts
test/integration-tests/testexplorer/TestExplorerIntegration.test.ts
test/integration-tests/testexplorer/utilities.ts
test/integration-tests/ui/PackageDependencyProvider.test.ts
test/integration-tests/utilities/testutilities.ts

Favour using the new `activateExtensionForSuite` and `activateExtensionForTest` methods, which automatically deactivate the extension when the suite or test completes.
These methods take optional setup/teardown methods that run on suite/test setup/teardown. If the setup method returns a promise, this is run automatically on teardown. This is useful for setup methods that modify settings, as they can now return the promise directly from `updateSettings` and any modified settings will be reverted automatically.
This also prints any logs captured to the output channel if a suite/test setup/teardown method fails with an error, which was being silently lost before.

Simpler test activation/deactivation in tests

---

package.json
src/configuration.ts
src/sourcekit-lsp/LanguageClientManager.ts
test/unit-tests/sourcekit-lsp/LanguageClientManager.test.ts

Now that backgroundIndexing is no longer experimental it can be enabled by default in Swift 6.1.
This patch evolves the `sourcekit-lsp.backgroundIndexing` setting to be an enum with three possible values, `true`, `false` or `auto`.
The `true` and `false` options function as they did previously. The new `auto` setting will enable background indexing on Swift >= 6.1. To enable background indexing on Swift 6.0 the user must still set this setting to `true`, as this feature is experimental in 6.0.

Add "auto" mode to sourcekit-lsp backgroundIndexing setting

---

assets/test/.vscode/settings.json
assets/test/diagnostics/Sources/main.swift
src/DiagnosticsManager.ts
test/integration-tests/DiagnosticsManager.test.ts

The format of messages generated from macro errors/warnings is different than those generated normally. The parsing regex would capture the location for the related info diagnostic with a backtick. The location for the parent regex would be "#macro expansion" which when clicked would open an error window in a VS Code tab stating that the file "#macro expansion" could not be found.
This patch tweaks two things:
1. Makes the regex for capturing the filepaths of warnings/errors account for leading trivia
2. If the path for a diagnostic is invalid, wait until we parse the related information and use the URI from there.
Issue #1224

Fix location for diagnostics generated from macros via swiftc

---

.prettierignore
.vscode/extensions.json
.vscode/launch.json
.vscode/settings.json
.vscode/tasks.json

Prettier was ignoring files in the .vscode directory by default since it's considered hidden. However, we actually want these files to have the same formatting with all of our other JSON files.

Format JSON files in the .vscode directory

---

test/integration-tests/commands/build.test.ts
test/unit-tests/sourcekit-lsp/LanguageClientManager.test.ts

Two PRs that touched the LanguageClientManager unit tests were merged at the same time and broke the unit tests.

Fix LanguageClientManager unit tests

---

assets/test/.vscode/settings.json
test/integration-tests/commands/build.test.ts
test/integration-tests/commands/dependency.test.ts

- The build command output is not logged properly in dependency test
- The build command test teardown is not needed and it adds unnecessary run time in the CI
- Check in the default setting for background compilation since updateSettings cannot reset to undefined, this way running locally will not cause git status to show unstaged changes even on test pass

Address some issues found when running test locally

---

test/integration-tests/commands/dependency.test.ts

- The tests do not need to activate and deactivate per test case, which seems to mess with the spm cache when using local dependency.
- Adjust to do it per suite and the tests are now passing consistently.

Make dependency integration test not flaky

---

test/integration-tests/DiagnosticsManager.test.ts
test/integration-tests/commands/dependency.test.ts
test/integration-tests/tasks/SwiftPluginTaskProvider.test.ts
test/integration-tests/ui/PackageDependencyProvider.test.ts

- This is true especially on flaky test, sometimes we check for the exit code but not print out the output from the command on failure.
- Fix it for a bunch of asserts where sporadic failures were observed to better understand what went wrong.

Improve the debugging on expect statement in test

---

assets/test/swift-macro/Package.swift
assets/test/swift-macro/Sources/swift-macro/swift_macro.swift
assets/test/swift-macro/Sources/swift-macroClient/main.swift
assets/test/swift-macro/Sources/swift-macroMacros/swift_macroMacro.swift
test/integration-tests/language/macro.test.ts

- Validate the workflow of user calling Expand Macro actions on a swift project with macro
- Add test fixture for swift macro
- Verify expand macro by asserting expanded macro document contain the right macro
Issue: #1205

Add integration tests for Expand Macro actions

---

assets/test/cmake-compile-flags/CMakeLists.txt
assets/test/cmake-compile-flags/compile_flags.txt
assets/test/cmake-compile-flags/main.cpp
package.json
src/WorkspaceContext.ts
test/integration-tests/ExtensionActivation.test.ts

SourceKit-LSP can handle projects configured with the paired down clang `compile_flags.txt` configuration file, as well as projects configured with the Build Server Protocol's `buildServer.json`.
Activate the extension if the folder added to the workspace contains either of these files in the root.
Issue: #1087

Activate extension when compile_flags.txt or buildServer.json is present

---

.eslintrc.json
src/TestExplorer/TestRunner.ts
src/TestExplorer/TestXUnitParser.ts
src/WorkspaceContext.ts
src/debugger/logTracker.ts
src/tasks/TaskManager.ts
src/ui/SwiftOutputChannel.ts
test/.eslintrc.json

Add an ESLint warning when using methods like console.log in the extension code. It is preferable to use the `SwiftOutputChannel` so that these logs are captured by the extension diagnostics mechanism, and so that they are all grouped together in the same place when debugging.
Sources under the tests directory do not have this restriction.

Warn when using `console` logging methods

---

.github/dependabot.yml

Since update rules are more permissive now, we get spammed when daily. I propose weekly is sufficient.

Lower dependabot interval

---

assets/test/defaultPackage/Package.swift
assets/test/defaultPackage/Package@swift-6.0.swift
assets/test/defaultPackage/Snippets/hello.swift
package-lock.json
package.json
src/SwiftSnippets.ts
test/integration-tests/BackgroundCompilation.test.ts
test/integration-tests/DiagnosticsManager.test.ts
test/integration-tests/SwiftSnippet.test.ts
test/integration-tests/commands/build.test.ts
test/integration-tests/commands/dependency.test.ts
test/integration-tests/language/macro.test.ts
test/integration-tests/tasks/SwiftExecution.test.ts
test/integration-tests/tasks/SwiftPluginTaskProvider.test.ts
test/integration-tests/tasks/SwiftPseudoterminal.test.ts
test/integration-tests/tasks/SwiftTaskProvider.test.ts
test/integration-tests/tasks/TaskManager.test.ts
test/integration-tests/tasks/TaskQueue.test.ts
test/integration-tests/ui/PackageDependencyProvider.test.ts
test/integration-tests/utilities/testutilities.ts
test/utilities/commands.ts
test/utilities/debug.ts
test/utilities/tasks.ts
test/utilities/types.ts

* Created some common utilities for dealing with debug sessions
* Add integration test for run command and debug variant, big difference
being whether the breakpoint is hit or not
Issue: #1125

Add tests for the Swift snippets workflows

---

test/integration-tests/DiagnosticsManager.test.ts

Improve wait condition. Passes using `act` locally
Issue: #1261

Fix sourcekit-lsp diagnostics tests

---

src/commands.ts
test/integration-tests/commands/runPluginTask.test.ts

Will mock to verify correct command is called
Issue: #1230

Test for run plugin task command

---

.github/workflows/nightly.yml

Documentation says the user must have write access to trigger this

Allow manually triggering of nightly build

---

test/integration-tests/commands/build.test.ts

30 seconds often wasn't enough to complete the build.
Issue: #1269

Increase timeout for build tests

---

test/integration-tests/language/LanguageClientIntegration.test.ts
test/utilities/tasks.ts

* Moving macros into common file with tests from #1236
* Fix some flakyness and failures

Some e2e/smoke tests for our integration with sourcekit-lsp

---

.github/workflows/pull_request.yml

Adding the `full-test-run` label to a PR before creating it will trigger the same workflow as the nightly job.

Allow triggering nightly build from PR label

---

src/sourcekit-lsp/extensions/SymbolInfoRequest.ts

The `textDocument/symbolInfo` request was created with an incorrect method name and response type.

Fix SourceKit-LSP symbol info request

---

src/sourcekit-lsp/LanguageClientManager.ts

I’m working on adding semantic functionality to generated interfaces in SourceKit-LSP and this will generate reference documents with a `sourcekit-lsp:` scheme and a `.swiftinterface` file. We shouldn’t change those URIs to a `readonly` scheme.

Only change scheme of `.swiftinterface` files to `readonly` if old scheme was `file`

---

package.json

I noticed this small typo while browsing the extension settings in VS Code.

Fix typo in description for swift.buildArguments setting

---

src/TestExplorer/TestDiscovery.ts
src/TestExplorer/TestExplorer.ts
test/integration-tests/testexplorer/TestDiscovery.test.ts

Because swift-testing suites can be defined through nested extensions the tests provided might not be directly parented to the test target. For instance, the test target might be `Foo`, and one of the child `testItems` in the document tests response might be `Foo.Bar/Baz`. If we simply attach the `testItems` to the root test target then the intermediate suite `Bar` will be dropped. To avoid this, syntheize the intermediate children just like we synthesize the test target.

Test suites in nested extensions have incorrect parent in test explorer

---

src/extension.ts
src/toolchain/SelectedXcodeWatcher.ts
test/unit-tests/toolchain/SelectedXcodeWatcher.test.ts

If the user performs an `xcode-select` and doesn't have a `swift.path` set in their VS Code settings, prompt them to restart the extension to pick up the new Xcode path. This only applies on macOS where `xcode-select` is possible.

Prompt to restart extension on `xcode-select`

---

src/documentation/DocumentationManager.ts
src/documentation/DocumentationPreviewEditor.ts

Switch to using `vscode.workspace.onDidChangeTextDocument()` instead of listening for text editor selection changes. This reduces the number of unnecessary requests made to SourceKit-LSP. Additionally, check the language of the editor before we send a request as SourceKit-LSP can only handle Markdown, Tutorial, and Swift files. Anything else we can safely assume will not succeed.

Clean up live preview VS Code event handlers

---

assets/test/.vscode/launch.json
test/integration-tests/SwiftSnippet.test.ts
test/integration-tests/commands/build.test.ts
test/utilities/debug.ts

* Timing issue waiting for the debug configuration to be created, but we should not have to do this
* Using existing launch config, the  adapter tracker was waiting for "swift-lldb" but we fallback to the "lldb" type for swift versions < 6.0
Issue: #1269

Fix debug command test

---

test/integration-tests/commands/build.test.ts
test/integration-tests/ui/PackageDependencyProvider.test.ts

* Seem to be intermittent failures if defaultPackage was not in the the workspace context as a package folder so lets be explicit
Issue: #1258

Fix flaky package dependency tests

---

docs/settings.md
package.json
src/configuration.ts
src/tasks/SwiftPluginTaskProvider.ts
test/integration-tests/tasks/SwiftPluginTaskProvider.test.ts
test/integration-tests/utilities/testutilities.ts

Packages can define their own plugins either directly or through their dependencies. These plugins define commands, and the extension exposes a list of these when you use `> Swift: Run Command Plugin`.
If a command requires special permissions to write to disk or use the network the user is prompted in the integrated terminal to type "yes". This can be bypassed by passing a permission flag to the command such as `--allow-writing-to-package-directory`. The extension does supply permission flags for a small list of well known package plugins, however if the user creates their own or uses one not on this list they must enter "yes" every time they run the command plugin.
This patch introduces a new setting that can be specified globally or on a per workspace folder basis that allows users to …

Configurable Command Plugin Permissions

---

src/DiagnosticsManager.ts
test/integration-tests/DiagnosticsManager.test.ts

Use the Uri's fsPath right away so we don't need to worry about mismatches downstream
Issue: #1304

Fix missing windows diagnostics

---

.vscodeignore
package-lock.json
package.json
src/documentation/DocumentationPreviewEditor.ts
src/documentation/webview/ErrorMessage.ts
src/documentation/webview/webview.ts

SourceKit-LSP has the capability of returning error messages for live preview that should be displayed to the user. Show an error message in this case that matches the style of errors shown in VSCode text editors.

Display error messages in the Documentation Live Preview Editor

---

.gitignore
.vscode/launch.json
assets/test/defaultPackage/Tests/PackageTests/PackageTests.swift
package.json
src/TestExplorer/TestParsers/SwiftTestingOutputParser.ts
src/TestExplorer/TestRunner.ts
src/configuration.ts
src/debugger/buildConfig.ts
src/utilities/tempFolder.ts
test/integration-tests/testexplorer/SwiftTestingOutputParser.test.ts
test/integration-tests/testexplorer/TestExplorerIntegration.test.ts

Support swift-testing attachments. Currently prints the attachments out as a report at the end of a test run. In order to leverage them we set the `--experimental-attachment-path` defined by a new `swift.attachmentsPath` setting. This is a directory path which can be global or scoped to the workspace. It can be relative or absolute. If relative, the absolute path is computed relative to the project workspace root. Defaults to `.build/attachments`.
If the `attachmentsPath` directory doesn't exist, it is created. Each test run that produces attachments creates a subfolder named with the date/time of the test run, and places the runs attachments within it. 
This will only work with nightly toolchains as it isn't in 6.0 or 6.1.

Swift Testing Attachments Support

---

src/SwiftPackage.ts
src/ui/PackageDependencyProvider.ts

Registry dependencies are stored in a different location than those checked out from source control.
Issue: #1307

Fix empty folder in dependencies view for registry deps

---

src/editor/CommentCompletion.ts
test/integration-tests/editor/CommentCompletion.test.ts

The comment completion parser was stumbling over the type declaration for typed throws, causing it to stop parsing the function declaration before it got to the return type.
Issue: #1313

Handle typed throws when generating comment completions

---

package.json
src/TestExplorer/TestExplorer.ts
src/sourcekit-lsp/LanguageClientManager.ts

Add some notifications to let users know that several things won't work as expected if SourceKit-LSP is disabled.
Issue: #892

Improve user feedback if SourceKit-LSP is disabled

---

src/SwiftSnippets.ts
src/tasks/SwiftTaskProvider.ts
src/ui/SwiftBuildStatus.ts
test/unit-tests/ui/SwiftBuildStatus.test.ts

The build progress notification would only appear once the progress values were shown in the output, i.e. [12/122]. Until progress values appear, show a "Preparing <task>" notification. This only needs to apply when the `showBuildStatus` value is `notification` or `progress`, since `swiftStatus` already shows a message in the bar immediately.
This patch also only sets the `showBuildStatus` setting on a Task if it is coming from a user defined task. Previously it was being set on synthetic tasks which were being cached, so when the user updated the `showBuildStatus` setting it wouldn't take effect until they restarted the extension.
Issue: #1322

Notify build is preparing before progress starts

---

src/ui/SwiftBuildStatus.ts
test/unit-tests/ui/SwiftBuildStatus.test.ts

Previously we were waiting for output from the build, which could be several seconds.
Issue: #1323

Show build preparing status immediately

---

CONTRIBUTING.md
README.md
docs/remote-dev.md
package-lock.json
package.json
test/integration-tests/ExtensionActivation.test.ts
test/integration-tests/utilities/testutilities.ts

In preparation for the move in the VS Code marketplace, rename the extension ID and associated references in the documentation.

Rename the extension from `sswg.swift-lang` to `swiftlang.vscode-swift`

---

test/integration-tests/testexplorer/TestExplorerIntegration.test.ts

This test case seems to get stuck frequently on Swift 5.10 now. Move it to nightly for now so that we can avoid creating false positives.
Issue: #1317

Move CodeLLDB XCTest case to nightly

---

assets/test/diagnostics/Sources/main.swift
assets/test/diagnosticsCpp/Sources/MyPoint/MyPoint.cpp
src/DiagnosticsManager.ts
test/integration-tests/DiagnosticsManager.test.ts

Display the full diagnostic message instead of stopping at backslashes or square brackets and update the diagnostics test case to check for this.
Issue: #1312

Show swiftc diagnostics with square brackets

---

CHANGELOG.md
CONTRIBUTING.md
README.md
docs/remote-dev.md
package-lock.json
package.json
test/integration-tests/ExtensionActivation.test.ts
test/integration-tests/utilities/testutilities.ts

Because there is already another extension with `vscode-swift` as its name, and the VS Code Marketplace _name_ must be unique (not just the full ID), switch to the extension ID `swiftlang.swift`.

Rename extension ID from `swiftlang.vscode-swift` to `swiftlang.swift`

---

.devcontainer/Dockerfile
.github/workflows/nightly.yml
.github/workflows/pull_request.yml

swiftlang/github-workflows migrated linux builds from nightly-6.0 to the nightly-6.1. Need https://github.com/swiftlang/github-workflows/pull/90 to land before we can migrate windows

Migrate from nightly-6.0 to nightly-6.1

---

src/sourcekit-lsp/LanguageClientManager.ts
test/unit-tests/sourcekit-lsp/LanguageClientManager.test.ts

Adds a middleware to the LanguageClientManager that will intercept code lenses from SourceKit-LSP and add the VS Code run and debug icons to them.

add VS Code iconography to code lenses from SourceKit-LSP

---

package.json

Now that `sswg` extension is renamed, we can use `Swift`

Rename extension to `Swift`

---

README.md

This pull request includes several updates to the `README.md` file for the Swift extension for Visual Studio Code. The changes enhance the clarity and completeness of the documentation, ensuring users have a better understanding of the extension's features and setup requirements. 
Key updates to documentation:
* Improved the introduction to highlight the seamless experience for developing Swift applications on all supported platforms.
* Updated the description of dependencies and installation steps to be more detailed and user-friendly.
* Clarified the commands available in the extension, specifying those that are exclusive to macOS and refining the descriptions for better understanding. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L53-R49) …

Copy edit on README

---

src/toolchain/toolchain.ts

If the CLT are installed add it to the list of available toolchains.
Also, if there are no Xcodes installed, omit the top level item from the list of quick pick options since it would render as an empty row.

Make CommandLineTools toolchain selectable if installed

---

assets/test/dependencies/Package.swift
assets/test/dependencies/Sources/main.swift
assets/test/identity-different/Package.resolved
assets/test/identity-different/Package.swift
package.json
src/FolderContext.ts
src/PackageWatcher.ts
src/SwiftPackage.ts
src/WorkspaceContext.ts
src/commands.ts
src/commands/dependencies/updateDepViewList.ts
src/contextKeys.ts
src/ui/PackageDependencyProvider.ts
test/integration-tests/SwiftPackage.test.ts
test/integration-tests/commands/dependency.test.ts
test/integration-tests/ui/PackageDependencyProvider.test.ts
test/unit-tests/ui/PackageDependencyProvider.test.ts

Currently the Package Dependencies view lists all dependencies in a flat list. This list not only includes those explicitly defined in the project's Package.swift, but also all the dependencies of dependencies.
As such its difficult to tell at a glance how a dependency is included. It can also be confusing to see dependencies in the list that you did not explicitly add.
Instead, show a top level list that is only the dependencies explicitly defined in Package.swift. Expanding one shows any child dependencies of the dependency. The files in the dependency's folder are still shown as well, just after any child deps.

Show project dependencies hierarchically

---

package.json
src/commands/attachDebugger.ts
src/configuration.ts
src/debugger/buildConfig.ts
src/debugger/debugAdapter.ts
src/debugger/debugAdapterFactory.ts
src/debugger/launch.ts
src/debugger/logTracker.ts
test/unit-tests/debugger/attachDebugger.test.ts
test/unit-tests/debugger/debugAdapter.test.ts
test/unit-tests/debugger/debugAdapterFactory.test.ts

This PR changes the behaviour of the generated launch configurations to always use a type of `"swift"` instead of switching between `"swift-lldb"` and `"lldb"` based on user settings. This new launch configuration type will then delegate to the appropriate debug adapter depending on settings. That way the extension no longer has to check for debug configuration updates all the time.
I've deprecated the `swift.debugger.useDebuggerFromToolchain` setting in favour of using a new `swift.debugger.debugAdapter` setting that is an enumeration of `"auto"`, `"CodeLLDB"`, and `"lldb-dap"`. Auto mode will continue to use CodeLLDB by default until we can properly move to the LLDB DAP extension provided by LLVM. Setting this to `"lldb-dap"` will continue to use the extension provided debug adapter …

Use one launch configuration type for all debug adapters

---

scripts/soundness.sh

The soundness script was failing to run with the error: `find: you have too many ')'`

Fix extra parentheses in soundness.sh

---

package.json

This PR adds two new actions in the editor for running and debugging the active Swift file. These actions use existing commands and are only shown when the active Swift file belongs to an executable target.

add editor run actions for Swift executables

---

package.json
src/debugger/debugAdapterFactory.ts

Certain non standard workflows (CMake) could produce binaries that end in .xctest. Only append .exe if it doesn't already have a valid extension.
Also declare `testType` in the debug configuration schema allowing users to declare what type of test framework they're using in the launch config if they're using a non standard flow.
Issue: #1364

Don't append .exe to binaries ending in .xctest

---

src/TestExplorer/TestParsers/XCTestOutputParser.ts
src/TestExplorer/TestXUnitParser.ts
test/integration-tests/testexplorer/TestExplorerIntegration.test.ts
test/integration-tests/testexplorer/utilities.ts

The `ParallelXCTestRunStateProxy` in `XCTestOutputParser.ts` wraps the test run state and only allows issues to be recorded using the terminal output of the test run. The remaining test run state is filled in with the xml xUnit output. This is because SwiftPM only dumps test output to the terminal if there is a failure. Using these two sources we can (almost) fully reconstruct a regular test run.
When parsing XCTest output from the terminal failure messages might be broken up over multiple lines. In order to capture all these lines and group them in to a single failure message even if the message is broken up across terminal buffer chunks we maintain an `excess` variable on the TestRunState, which we check at the beginning of chunk parsing to know if we need to continue an error message. …

Fix flakey XCTest parallel test failure reporting

---

src/TestExplorer/TestRunner.ts
src/tasks/SwiftExecution.ts

During a standard test run (not using the debugger) a cancellation request from VS Code did not terminate the process under test, which lead to it being orphaned.
Issue: #1389

Terminate process under test on test run cancellation

---

src/toolchain/toolchain.ts

This is essentially the same change made in:
https://github.com/swiftlang/swift-package-manager/pull/8199
VS Code would be able to leverage it for regular runs with `swift test` but because when debugging we launch the xctest executable directly to run tests, we must include the same framework search paths as SPM.

Add PrivateFrameworks as additional Swift Testing framework path

---

assets/test/.vscode/launch.json
assets/test/.vscode/settings.json
assets/test/defaultPackage/.vscode/launch.json
assets/test/diagnostics/.vscode/launch.json
package.json
src/configuration.ts
src/debugger/debugAdapterFactory.ts
test/integration-tests/SwiftPackage.test.ts
test/integration-tests/commands/dependency.test.ts
test/integration-tests/testexplorer/TestExplorerIntegration.test.ts
test/integration-tests/utilities/testutilities.ts
test/unit-tests/debugger/debugAdapterFactory.test.ts

Recent changes to launch configuration options and prompts for CodeLLDB broke the nightly tests. Fix those issues here by:
- Updating tests to use the `swift` launch config type instead of `swift-lldb`
- Use the new setting `swift.debugger.debugAdapter` to set the debug adapter that the tests use
- Add a new setting called `swift.debugger.setupCodeLLDB` that controls how CodeLLDB settings are updated. Tests now set this to `"alwaysUpdateGlobal"` so that they don't have to deal with the prompt at all.
I also had to disable the use of `liblldb` in tests with Swift versions <5.10 since those versions of `liblldb` don't seem to be compatible with CodeLLDB. The tests fail to start due to the debug adapter crashing.

Fix nightly debugging test failures

---

src/extension.ts
src/sourcekit-lsp/LanguageClientManager.ts
src/toolchain/toolchain.ts
src/ui/SwiftOutputChannel.ts
test/integration-tests/ui/SwiftOutputChannel.test.ts
test/integration-tests/utilities/testutilities.ts
test/unit-tests/debugger/lldb.test.ts

The logging of the SwiftOutputChannel on test failures was printing the previous test's logs rather than the current test. Fix this by moving the `beforeEach()` and `afterEach()` hooks into the test runner setup.
I've also opted to remove the console logging in SwiftOutputChannel as it was just polluting the logs with extra unnecessary info. This isn't needed anymore since the test failure logging is working now.

Fix output logs on integration test failure

---

test/integration-tests/tasks/TaskQueue.test.ts

Although I cannot reproduce locally it is taking 7600ms which is very close to the timeout so going to try increasing the timeout to fix.

Increase timeout for TaskQueue test

---

package.json
src/debugger/debugAdapter.ts
src/debugger/debugAdapterFactory.ts
test/unit-tests/debugger/debugAdapterFactory.test.ts

Add an extension dependency on the LLDB DAP extension by the LLVM project. I've also removed the debug adapter executable factory and instead launch debug sessions for lldb-dap via the LLDB DAP extension.
A PR will come later for removing the dependency on CodeLLDB.

Use LLDB DAP extension to launch debug sessions

---

package.json
src/debugger/debugAdapterFactory.ts
test/integration-tests/utilities/testutilities.ts
test/unit-tests/debugger/debugAdapterFactory.test.ts

VS Code added an alarming warning when installing the Swift extension because it depends on the unverified CodeLLDB extension. Remove the direct dependency on CodeLLDB in favour of prompting the user to install it themselves when they try to debug a Swift toolchain <6.0.0.

Remove dependency on CodeLLDB

---

assets/test/defaultPackage/Tests/PackageTests/PackageTests.swift
src/TestExplorer/TestRunArguments.ts
src/TestExplorer/TestRunner.ts
src/tasks/SwiftExecution.ts
src/tasks/SwiftProcess.ts
src/tasks/SwiftTaskProvider.ts
test/integration-tests/testexplorer/TestExplorerIntegration.test.ts
test/integration-tests/testexplorer/TestRunArguments.test.ts
test/integration-tests/testexplorer/utilities.ts

node-pty on Linux suffers from a long standing issue where the last chunk of output before a program exits is sometimes dropped, especially if that program produces a lot of output immediately before exiting. See https://github.com/microsoft/node-pty/issues/72
For swift processes that don't require input and may produce a lot of output that could potentially be truncated we can add a new `ReadOnlySwiftProcess` that spawns a child process using node's built in `child_process`. These spawned child processes emit their full output before exiting without the need to resort to flakey workarounds on the node-pty process.
When creating new `SwiftExecution`s in future `readOnlyTerminal` should be set to `true` unless the process may require user input.
Issue: #1393

Fix missing Test Result output on Linux when using `print`

---

src/debugger/debugAdapter.ts
test/unit-tests/debugger/debugAdapter.test.ts

Now that we've removed the dependency on CodeLLDB to avoid VS Code warnings about untrusted extensions, we should use `lldb-dap` by default on Swift 6.0 and later.

Use `lldb-dap` by default when `swift.debugger.debugAdapter` is set to `"auto"`

---

.vscode-test.js
.vscode/testing-debug.code-profile
README.md

- Switch from CodeLLDB to LLDB DAP in the testing-debug.code-profile
- If you're running the tests from within VS Code at desk you'll want to delete the existing Testing profile and reload with the new one.
- Fixup the README
- Fixup the vscode-test.js required extensions

Remove more references to CodeLLDB

---

src/tasks/SwiftProcess.ts

This kept the executed command from being printed in the terminal when using `swift test`

Add missing spawn event on ReadOnlySwiftProcess

---

src/TestExplorer/TestRunner.ts

Print the command being run when starting a debugging session while running tests, just like a regular non-debug run.

Print the command being run when debugging tests

---

docs/settings.md

Add some documentation to the settings docs that outlines how to specify which Visual Studio installation Swift should pull its dependencies from on Windows.
Also annotates existing setting names in the document with links that jump straight to the relevent setting in VS Code.
Issue: #1419

Document how to use a different Visual Studio

---

test/integration-tests/testexplorer/MockTestRunState.ts
test/integration-tests/testexplorer/XCTestOutputParser.test.ts

When performing a parallel XCTest run we first parse the terminal output, then parse the xUnit XML output and merge the two data sets together to create the run results. This merging was not being tested at the unit test level, only at the integration test level, which lead to a subtle and occasional bug, #1334 (fixed in #1343).
As a followup, update the existing XCTestOutputParser tests to test both regular and parallel test run output. xUnit XML is synthesized from the expected results and fed in to the `TestXUnitParser` to modify the test's `TestRunState` just as it is in the extension.

Add tests for parsing parallel XCTest run output

---

src/TestExplorer/TestParsers/SwiftTestingOutputParser.ts

Swift-testing updated their icons for test failure in https://github.com/swiftlang/swift-testing/pull/983

Align test result icons for terminal with swift-testing

---

src/TestExplorer/TestRunner.ts
test/integration-tests/testexplorer/TestExplorerIntegration.test.ts

Add a `skipped` tag to tests in the test explorer if they were skipped in the last run. This lets users filter down just the skipped tests in a test run.

Add tag to skipped test

---

docs/settings.md
package.json
src/configuration.ts
src/tasks/SwiftPluginTaskProvider.ts
test/integration-tests/tasks/SwiftPluginTaskProvider.test.ts

Packages can define their own plugins either directly or through their dependencies. These plugins define commands, and the extension exposes a list of these when you use `> Swift: Run Command Plugin`.
It may be desirable to build and run these plugins with specific arguments. This patch introduces a new setting that can be specified globally or on a per workspace folder basis that allows users to configure arguments to pass to plugin command invocations.
The setting is defined under `swift.pluginArguments`, and is specified as an object in the following form:
```json
{
"PluginCommandName:intent-name": ["--some", "--args"]
}
```
- The top level string key is the command id in the form `PluginCommandName:intent-name`. For instance, swift-format's format-source-code command would be …

Configurable Command Plugin Build Configuration

---

src/tasks/SwiftTaskProvider.ts

The environment in the task.json definitions was not adding workspace/global env settings. Layer in the `swiftEnvironmentVariables` the same way as in generated build tasks.

Ensure environment from settings is added to resolved tasks

---

README.md
package.json
src/commands.ts
src/commands/switchPlatform.ts
src/contextKeys.ts
src/extension.ts
test/unit-tests/commands/switchPlatform.test.ts

SourceKit-LSP now provides code editing support for non-macOS Darwin platforms starting Swift 6.1 using the `--swift-sdk` flag. Set this flag to the appropriate target-triple when using the `Select Target Platform` feature on macOS.
Issue: #1335

Set swift.swiftSDK for target platforms

---

src/ui/ToolchainSelection.ts

The toolchain selection UI was setting the `DEVELOPER_DIR` environment variable to the path to the Xcode application which is actually incorrect. This still worked for `xcrun` and `xcode-select` because they are more lenient in what they allow `DEVELOPER_DIR` to be set to. However, other tools will fail if they encounter an unexpected value.
Use `xcode-select -p` to determine the actual location of the developer directory before setting the `DEVELOPER_DIR` environment variable.

Use `xcode-select` to determine the actual `DEVELOPER_DIR` value

---

src/TestExplorer/LSPTestDiscovery.ts
src/sourcekit-lsp/LanguageClientManager.ts
src/sourcekit-lsp/didChangeActiveDocument.ts
src/sourcekit-lsp/extensions/DidChangeActiveDocumentRequest.ts
test/unit-tests/sourcekit-lsp/LanguageClientManager.test.ts

`sourcekit-lsp` recently added an LSP extension method to notify the server of the active documnent, so it doesn't need to infer it from information in other requests. This capability was added in https://github.com/swiftlang/sourcekit-lsp/pull/1989.
This also relies on https://github.com/swiftlang/sourcekit-lsp/pull/1994

Notify sourcekit-lsp of active document changes

---

package-lock.json
package.json
src/BackgroundCompilation.ts
src/FolderContext.ts
src/WorkspaceContext.ts

This `swift.backgroundCompilation` setting listened for file save events from VS Code and triggered the build task. This meant that only modifications made by saving in a VS Code editor would trigger background compilation.
Switch to using a `vscode.FileWatcher` so background compilation still gets kicked off even if a file is modified from outside VS Code. This is useful if you have a command plugin that modifies source files like swift-format.
Issue: #1274

Use FileWatcher for background compilation

---

src/DiagnosticsManager.ts

Starting with Swift 6.2 some warnings may end with a tag such as `[#no-usage]`. Update parsing logic to remove these tags from the warnings to ensure we can combine them with the warnings from SourceKit.
Issue: #1434

Update diagnostics parsing to handle new warnings

---

src/configuration.ts
test/integration-tests/configuration.test.ts

VS Code defines several predefined variables that can be substituted in task and launch configurations. It is useful to have some of these defined for use in Swift settings, specifically the ones that are comprised of paths.
This patch introduces a limited list of variables that are substituted in some settings. The variables supported are:
- `${workspaceFolder}`
- `${workspaceFolderBasename}`
- `${cwd}`
- `${userHome}`
- `${pathSeparator}`
The settings that support variable subsitution are:
- `${swift.path}`
- `${swift.runtimePath}`
- `${swift.sdk}`
- `${swift.buildArguments}`
- `${swift.packageArguments}`
- `${swift.buildPath}`
- `${swift.serverArguments}`
- `${swift.additionalTestArguments}`
- `${swift.attachmentsPath}`
- `${swift.debugger.customDebugAdapterPath}`
- …

Resolve settings variables in Swift settings

---

src/TestExplorer/TestParsers/XCTestOutputParser.ts
test/integration-tests/testexplorer/XCTestOutputParser.test.ts

The values of the error message in the VS Code UI is swapped from how they appear in XCTAssertEqual.
Issue: #1441

Swap expected and actual assertion values

---

test/integration-tests/process-list/processList.test.ts

The process names for insider versions of VS Code are slightly different from the release versions. Update the test to account for this.
Issue: #1442

Update Process List test to handle insider builds

---

README.md

The README incorrectly stated that CodeLLDB was being used for debugging by default.

Update debugging section in the README

---

.github/workflows/nightly.yml
.vscode/launch.json
package.json
scripts/check_package_json.ts
scripts/lib/utilities.ts
scripts/preview_package.ts
scripts/soundness.sh
scripts/update_swift_docc_render.ts

Update the `preview-package` script to generate a pre-release package with one minor version greater than the current version from the `package.json` and a patch number set to today's date formatted as `YYYYMMddhhmm`. The nightly CI will now generate both a release and pre-release extension VSIX. This enables us to create a pre-release version of the Swift extension.
Going forward, we'll have to abide by the following rules in order for this to work:
1. The version in the `package.json` should always be the current release version of the extension as published on the VS Code marketplace.
2. Always use even numbered minor versions for releases. Pre-release builds will then always have an odd minor version.
I've added a check in CI to enforce even numbered minor versions in the …

Build pre-release VSIX in CI

---

CHANGELOG.md
package-lock.json

The changelog on main doesn't include the 2.0.2 release.

Cherry pick changelog from release/2.0.2

---

src/commands.ts
src/ui/ProjectPanelProvider.ts
test/integration-tests/ui/ProjectPanelProvider.test.ts

Because we use `swift package describe` to extract metadata about the package we need the Package.swift to be buildable. If it isn't, create a header node in the project panel that calls out the fact that the Package.swift can't be built. Clicking it will take the user to the Package.swift.

Show error message in project panel when manifest can't be built

---

src/ui/ProjectPanelProvider.ts

If users want to have non-Swift task types in their package they should be able to.

Show all task types in project panel

---

scripts/preview_package.ts

VSCode only allows the patch version number to be between 0 and 2,147,483,647. The full date and time is not possible to fit into this value. Instead, we will now just do `YYYYMMdd` which will only allow us to publish daily builds. We could tack on a build number from 0-99 in the future like the Python extension if we ever need more than one build per day.

Shorten pre-release version number

---

test/integration-tests/language/LanguageClientIntegration.test.ts
test/integration-tests/utilities/lsputilities.ts

The tests used `workspace/_pollIndex` to determine if sourcekit-lsp had finished indexing, however this hidden request was removed from sourcekit-lsp recently in favour of `workspace/_synchronize`
Issue: #1457

Use `synchronize-request` in LSP tests on 6.2

---

test/integration-tests/testexplorer/TestExplorerIntegration.test.ts

The format of the ID used by parameterized test cases has changed recently in the nightly (6.2) toolchains. This ID doesn't matter much to the extension, it just needs to be unique, so only the tests need to be updated.
Issue: #1458

Fix `swift-testing Runs parameterized test` on nightly toolchains

---

src/debugger/debugAdapterFactory.ts
test/unit-tests/debugger/debugAdapterFactory.test.ts

The new process picker will always return a string due to the nature of VS Code variable substitutions. However, `lldb-dap` expects the `pid` property to always be a number. This PR adds a check to the `LLDBDebugConfigurationProvider` that will make sure the `pid` property is an integer.
Issue: #1464

Convert "pid" property in launch configuration to an integer

---

src/TestExplorer/TestRunner.ts

When running a standard test session (not debugging) the xctest process was terminated when the user hit the cancel test button, but the promise to continue and mark the test run as ended was not resolved. This kept the UI in a state that looked like the test was still running.

Resolve session promise on test run cancellation

---

src/toolchain/ToolchainVersion.ts
src/toolchain/toolchain.ts
test/unit-tests/toolchain/ToolchainVersion.test.ts

On macOS the toolchain path is determined by `xcrun --find swift`. `xcrun` will return paths inside the active Xcode. If the active toolchain is being managed by the newly released Swiftly 1.0 on macOS then the swift path and the toolchain path will be mismatched.
Check to see if the active toolchain is managed by Swiftly, and if so point the toolchain path to the Swiftly installed toolchain. The name of the `.xctoolchain` folder needs to be reverse engineered from Swiftly's in use toolchain name using the ToolchainVersion.parse method which was ported from Swiftly's codebase. A nice feature in the future would be to be able to ask Swiftly where its managed toolchains are stored on disk.

Use Swiftly's toolchain path if active toolchain is managed by Swiftly

---

src/ui/ReloadExtension.ts
test/unit-tests/ui/ReloadExtension.test.ts

If `showReloadExtensionNotification` is in flight and being awaited then return the promise being awaited instead of showing another dialog.
Also, debounce `showReloadExtensionNotification` with a 5 second window because its possible for users to close the first dialog very fast and have another one appear immediately if we update several settings at a time that require an extension restart.
Issue: #1471

Ensure only one reload extension dialog can be shown at a time

---

src/debugger/debugAdapterFactory.ts

The `promptForCodeLldbSettings()` function was not performing an `await` when updating CodeLLDB settings. This meant that the debug session got started before the settings update took place.
Issue: #1481

Properly wait for CodeLLDB settings to take effect

---

package.json
src/commands/runSwiftScript.ts
src/configuration.ts

This PR tries to implement a secondary quick pick for selecting desired Swift Version for `Run Swift Script` command, and also enabling global settings for it in vscode workspace.
- Fixes  #1427

feat: secondary quick pick for selecting Swift Version with `runSwiftScript` command

---

src/extension.ts

If there is no toolchain available we short circuit extension activation but still try and stop the workspace, which hasn't been created.

Fix potential error when no toolchain found

---

scripts/test_windows.ps1
test/integration-tests/utilities/testutilities.ts

Occasionally the Windows tests will hang after all tests have completed until the GitHub action times out. Using `Start-Process` with the `-Wait` flag will wait for the process and all of its child processes to terminate. This means that if the VS Code instance under test has any lingering processes the build may hang forever.
Instead run the test command directly, referencing the success status with `$LASTEXITCODE`. This should hopefully report the status more reliably without hanging.

Run windows tests directly in same shell

---

.github/workflows/nightly.yml

6.1 is stable, don't want to run insiders against multiple versions

Only run insiders job against 6.1

---

scripts/test_windows.ps1

For now just comment out the Windows SDK settings to see if builds are passing on 6.1

Use latest Windows SDK to run tests on Swift >=6.1

---

README.md

Docs are now published, but to a slightly different URL.

Fix URL to docs from README.md

---

CHANGELOG.md
package-lock.json
package.json

- Bump version number to 2.2.0 in the `package.json`
- Update change log

Release activities for 2.2.0

---

assets/test/defaultPackage/Tests/PackageTests/PackageTests.swift
src/TestExplorer/TestRunner.ts
test/integration-tests/testexplorer/TestExplorerIntegration.test.ts

If a test crashes during a test run the extension never marks the test as failed, since it doesn't see the output that marks the test as completed.
If we finish a test run and we still have a test in the 'pending' state where no pass/fail/skip has been seen, mark the test as failed with a message stating the test never finished.
Issue: #1504

Fail tests if they crash

---

src/utilities/utilities.ts

When running `execSwift` or `execFile` it was possible for very large results to exceed the default max buffer size as defined by Node.JS (1MB).
This was happening when initializing a complex package during the `swift package show-dependencies --format json` call, which produced a very large dependency graph.

Increase the size of child_process buffers

---

src/WorkspaceContext.ts
src/configuration.ts
src/contextKeys.ts
src/debugger/debugAdapterFactory.ts
src/extension.ts
src/tasks/SwiftPluginTaskProvider.ts
src/tasks/SwiftTaskProvider.ts
src/terminal.ts

Refactor the extension activation method such that it only starts up the necessary services and registers their disposables for extension deactivation. The startup order of services has been tweaked slightly so that it will fail fast if the toolchain is not configured properly. Fixes a few services that were registred for disposal twice.
Fixes up `registerDebugger` so that toggling the setting works immediately instead of silently requiring an extension restart before taking effect.

Cleanup extension activation

---

assets/test/.vscode/settings.json
src/DiagnosticsManager.ts
src/configuration.ts
test/integration-tests/DiagnosticsManager.test.ts

Moved these tests over to the fixture to make teardown less error

Automatically teardown settings for diagnotics tests

---

src/TestExplorer/TestParsers/XCTestOutputParser.ts
test/integration-tests/testexplorer/XCTestOutputParser.test.ts

Sometimes when running tests that print user output during their execution this output can be printed on the same line as XCTest results output, either before or after the results string. Previously this showed as a test that never finished (pending) in the test explorer, but with the introduction of #1505 tests that start but don't find any completion output are assumed to be crashed and marked as failed.
This extra user output interleaved with XCTest output would cause false positives, leading users to believe that their test never completed (crashed) when really we just missed the success/failure message from XCTest due to overly strict parsing.
Relax the XCTest output parsing regexes so that matched strings don't need to be at the start of a line.

Parse XCTest output anywhere in output lines

---

README.md

Now that we default to LLDB DAP on >=Swift 6 toolchains, update the README to mention LLDB DAP in the supported features list instead of CodeLLDB.

Fixup reference to CodeLLDB in README.md

---

src/SwiftPackage.ts
src/ui/ProjectPanelProvider.ts

Missed a few target types when adding icons to the Project Panel. Also adds the target type description to the tooltip to make it more clear what icons correspond to what target type.

Add system-target and binary target icons to Project Panel

---

src/documentation/webview/ThemeObserver.ts
src/documentation/webview/webview.ts

Adds logic to the webview that will update the `data-color-scheme` attribute on `<body />` (used by `swift-docc-render` to set the theme) when VS Code changes its theme. I've also removed VS Code's default styles because they were conflicting visually with `swift-docc-render`.

Update Live Preview theme when VS Code theme changes

---

src/documentation/webview/webview.ts

The links generated by SwiftDocC will only break the webview and should be disabled in Live Preview mode.

Disable clicking on links in Live Preview

---

src/toolchain/toolchain.ts

A change in SwiftPM removed the rpath that pointed to `usr/lib/swift/macosx/testing`
(https://github.com/swiftlang/swift-package-manager/pull/8295).
Consequently when debugging tests in VS Code `libTesting.dylib` could not be found and the tests would not start. This is only happening in nightly toolchains that contain the SwiftPM change noted above.
Fix this by adding the search path to the DYLD_LIBRARY_PATH.

Update DYLD_LIBRARY_PATH to fix debugging tests in nightly toolchains

---

scripts/download_vsix.ts

Since pre-release is always 1 minor version higher, we know it's the second binary

Allow renaming the prerelease VSIX

---

src/utilities/workspace.ts

Before: focus: undefined
After: 
```
19:13:49: Activating Swift for Visual Studio Code...
19:13:50: SourceKit-LSP setup
19:13:51: swift-data: add: /Users/chase/dev/swift-data
19:13:51: swift-data: focus: /Users/chase/dev/swift-data
```
Fix #1449

Support finding compile_commands.json in non root project directories

---

src/ui/ProjectPanelProvider.ts

When a task is updated, added or deleted it is not reflected in the project panel. There are no VS Code APIs that notify on task modification/update/deletion, so poll every 2 seconds and check if the tasks are updated. If they are, refresh the tasks list in the project panel.

Poll for updated tasks in project panel

---

CONTRIBUTING.md

Small PR - Commit 38db866516e604a26f6cdb7dec9f35386734d45b moved `install-pre-release.png`. This PR adjusts sources to changes. It also fixes a small typo along the way.

Update assets in contribution guide

---

src/toolchain/toolchain.ts
src/ui/ToolchainSelection.ts
test/unit-tests/toolchain/toolchain.test.ts

Using the Spotlight index to find Xcode installations on macOS may not always find all available Xcode applications depending on macOS settings and the state of the Spotlight index itself. Include the result of `xcode-select -p` when finding Xcode applications to ensure that the currently selected Xcode is always included in the list of available Xcode applications for toolchain selection.
Issue: #1528

Combine results from mdfind and xcode-select when searching for available Xcode applications

---

.github/workflows/nightly.yml
.github/workflows/pull_request.yml
package-lock.json
package.json
scripts/download_vsix.ts
scripts/test.sh

- Since pre-release is always 1 minor version higher, we know it's the second binary
- Eventually will be used downstream to tag releases
- Also setup PR job to package the VSIX and run tests against it so we can test against that in verifier jobs as well

Changes for release process

---

src/WorkspaceContext.ts
src/commands/runTask.ts
src/extension.ts
src/tasks/SwiftPluginTaskProvider.ts
src/ui/ProjectPanelProvider.ts
test/integration-tests/tasks/SwiftPluginTaskProvider.test.ts

Seems to be causing test failures because a different instance of the provider is used to resolve

Only have one instance of the plugin provider

---

package.json

The `VS Code Swift` portion of the command name is implied and only makes it harder to remember.

Shorten the name of the `Swift: Capture Diagnostics Bundle` command

---

src/TestExplorer/TestParsers/SwiftTestingOutputParser.ts

The inline issue label in VS Code doesn't support ANSI colour codes, and so renders them verbatim. Remove these so the messages are easier to read.

Don't colorize swift testing issue messages

---

src/configuration.ts
src/tasks/SwiftPluginTaskProvider.ts
src/tasks/SwiftTaskProvider.ts
test/unit-tests/tasks/SwiftPluginTaskProvider.test.ts
test/unit-tests/tasks/SwiftTaskProvider.test.ts

- Expand list of supported variables to include some vscode defines that make more sense in the context of tasks
- Apply to the list of "args" to "swift" and "swift-plugin" tasks
- Add unit tests to track
Issue: #1150

Substitute variables in task "args"

---

assets/test/.vscode/settings.json
test/integration-tests/utilities/testutilities.ts

Fix logic to reset these when changed, also consider if default value when reseting. This causes backgroundCompilation on in test project to get removed since that is the default

Fix reseting of settings

---

src/tasks/SwiftTaskProvider.ts
test/integration-tests/commands/dependency.test.ts
test/integration-tests/language/LanguageClientIntegration.test.ts
test/integration-tests/utilities/testutilities.ts

Was an issue with using the cached tasks between successive extension activations. Also using, create over get variant of the helper to not go through all the extra paths of fetching and matching names

Clear cache during teardowns

---

src/tasks/SwiftTaskProvider.ts
test/integration-tests/tasks/SwiftPluginTaskProvider.test.ts
test/integration-tests/ui/ProjectPanelProvider.test.ts

Output intermittently not captured causing this test to fail. I'm going to turn it off for now

Stop checking plugin task output

---

test/integration-tests/commands/runPluginTask.test.ts

We may be checking mock before actually called

Await the execution of the run plugin task command

---

package.json
src/contextKeys.ts
src/extension.ts

It appears that the `isMac` context key provided by VS Code does not work the way we expect when running in a remote extension host. Update the logic for the `swift.switchPlatformAvailable` context key to check for the active platform and use that instead.
Issue: #1363

Only use the context key for enabling the "swift.switchPlatform" command

---

test/integration-tests/testexplorer/TestExplorerIntegration.test.ts

Some tests have the default timeout, which could be contributing to intermittent failures on Windows.

Increase timeouts for @slow integration tests

---

src/ui/SwiftBuildStatus.ts

For tasks in the "build" group like those provided by the extension, we can ignore parsing the build output for completion and instead wait for the fallback of waiting for the task to end.
Issue: #1477

Better handle status updates for build tasks

---

.github/workflows/nightly.yml

Hasn't been a build off release/6.1 since March 3rd but we need the fix for https://github.com/swiftlang/swift/pull/80144 that was made March 25th

Disable nightly-6.1 run for Windows

---

src/DiagnosticsManager.ts
src/SwiftPackage.ts
src/TestExplorer/TestParsers/SwiftTestingOutputParser.ts
src/TestExplorer/TestParsers/XCTestOutputParser.ts
src/process-list/BaseProcessList.ts
src/toolchain/toolchain.ts
src/ui/SwiftBuildStatus.ts
src/utilities/tasks.ts
test/integration-tests/testexplorer/XCTestOutputParser.test.ts

For example https://github.com/swiftlang/vscode-swift/actions/runs/15164128210/job/42637324461?pr=1566, see extra blank lines I don't think should be there
```
99996
99997
99998
99999
100000
```

See if splitting is causing the mismatch output issues in tests

---

src/commands/runPluginTask.ts

Explicitly calling so not awaiting here may be causing a timing issue
```
2) runPluginTask Test Suite
Executes runTask command:
AssertionError: expected stub to have been called exactly once with arguments 'workbench.action.tasks.runTask', { type: 'swift-plugin' }
at Context.<anonymous> (d:\a\vscode-swift\vscode-swift\test\integration-tests\commands\runPluginTask.test.ts:37:58)
```
Issue: #1574

Await the run plugin task command

---

package.json
src/WorkspaceContext.ts
src/commands.ts
src/commands/generateLaunchConfigurations.ts
src/contextKeys.ts
src/debugger/debugAdapterFactory.ts
src/debugger/launch.ts
src/ui/ProjectPanelProvider.ts
test/unit-tests/debugger/launch.test.ts

Adds a new command called `Swift: Generate Launch Configurations` that can be used to manually trigger the generation of launch configurations for the workspace.
I've also simplified the logic for generating launch configurations by moving some of the generated keys into the debugAdapterFactory so they can be applied at runtime without needing to be set in the launch config. This will reduce the need for updating launch configurations and, by extension, reduce the number of notifications we push to the user.
Issue: #1533

Add command to generate launch configurations

---

package.json
src/debugger/buildConfig.ts
src/debugger/debugAdapterFactory.ts
src/debugger/lldb.ts
src/ui/SwiftOutputChannel.ts
src/utilities/utilities.ts
test/integration-tests/debugger/lldb.test.ts
test/unit-tests/debugger/debugAdapterFactory.test.ts

There was a bunch of code that checks for `process.env.CI === "1"` (or variations of that). Consolidated all of these checks into a utility called `IS_RUNNING_IN_CI` that will get optimized out of production builds using esbuild's `--define` command line argument.

Remove CI checks in production

---

.github/workflows/nightly.yml

Hasn't been a successful nightly build of the toolchain since early April

Disable windows nightly toolchain

---

src/tasks/SwiftExecution.ts
src/tasks/SwiftProcess.ts
src/tasks/SwiftPseudoterminal.ts
test/fixtures.ts
test/integration-tests/DiagnosticsManager.test.ts
test/integration-tests/commands/dependency.test.ts
test/integration-tests/tasks/SwiftExecution.test.ts
test/integration-tests/tasks/SwiftPseudoterminal.test.ts
test/utilities/tasks.ts

- Were not displosing of event emitters
- Were cleaning up read-only process data listeners early

Properly cleanup task event emitters

---

CHANGELOG.md
package-lock.json
package.json

- Bump version
- Add changelog entry

Release activities for 2.4

---

test/integration-tests/BackgroundCompilation.test.ts
test/integration-tests/SwiftSnippet.test.ts
test/integration-tests/commands/build.test.ts
test/integration-tests/commands/dependency.test.ts
test/integration-tests/tasks/SwiftExecution.test.ts
test/integration-tests/tasks/SwiftTaskProvider.test.ts
test/integration-tests/tasks/TaskManager.test.ts
test/integration-tests/tasks/TaskQueue.test.ts

Handled before suite activation and deactivation now and think some of the before hook timeouts come from this

Remove redundant waitForNoRunningTasks()

---

src/commands/resetPackage.ts
src/sourcekit-lsp/LanguageClientManager.ts
test/integration-tests/commands/dependency.test.ts

For versions of sourcekit-lsp prior to 6.1, the .build folder cannot be removed for package reset on Windows. To make this work stop the server and then restart it after the reset is done
Issue: #1210

Fix package reset on Windows

---

src/configuration.ts

If someone accidentally makes a string setting null, activation can fail
Issue: #1609

Make sure subsituted string is not null

---

.vscode-test.js
.vscode/launch.json
assets/test.code-workspace
assets/test/.vscode/tasks.json
assets/test/defaultPackage/.vscode/launch copy.json
scripts/test_windows.ps1
src/TestExplorer/TestRunner.ts
src/commands/build.ts
src/commands/dependencies/edit.ts
src/commands/dependencies/resolve.ts
src/commands/dependencies/update.ts
src/commands/dependencies/useLocal.ts
src/commands/resetPackage.ts
src/configuration.ts
src/debugger/buildConfig.ts
src/debugger/launch.ts
src/tasks/SwiftPluginTaskProvider.ts
src/tasks/SwiftTaskProvider.ts
src/ui/StatusItem.ts
src/utilities/tasks.ts
test/integration-tests/WorkspaceContext.test.ts
test/integration-tests/commands/build.test.ts
test/integration-tests/commands/dependency.test.ts
test/integration-tests/configuration.test.ts
test/integration-tests/extension.test.ts
test/integration-tests/tasks/SwiftPluginTaskProvider.test.ts
test/integration-tests/tasks/SwiftTaskProvider.test.ts
test/integration-tests/tasks/TaskQueue.test.ts
test/integration-tests/utilities/testutilities.ts

- Support workspace folder variable subsitution, ex. `${workspaceFolder:proj1}`
- When a code-workspace add the configured `name` instead of the relative path as a postfix to the task name
- Add same postfixes to plugin tasks
- For Run and Debug Build commands, all fetching launch configurations from outside the workspace
- Add a new test target to test a handful of currated suites to make sure that .code-workspace support does not break
Issue: #1072

Support for multi-root .code-workspace workspaces

---

src/commands.ts
src/toolchain/SelectedXcodeWatcher.ts
src/ui/ToolchainSelection.ts
test/unit-tests/toolchain/SelectedXcodeWatcher.test.ts

If the Xcode selected via xcode-select changes and the user has a "swift.path" setting configured, show warning notification suggesting they remove the setting or "Select Toolchain"
Also trigger this warning on startup if the toolchain path is not under the selected Xcode.app
Issue: #1472

Notify user if the `xcode-select`ed Xcode doesn't match setting

---

src/commands.ts
src/commands/dependencies/edit.ts
src/commands/dependencies/unedit.ts
src/commands/resetPackage.ts
src/ui/ProjectPanelProvider.ts
test/integration-tests/commands/dependency.test.ts

instanceof causes issues in nightly because VSIX version and test version of the PackageNode class are different
Also allow passing folder context to package commands as are some random focus issues

Avoid use of instanceof

---

README.md

Clarify that the extension is meant to work with Swift Package Manager based projects, and supporting Xcode projects is not well supported.
Fixes: #1636

Note in the readme the extension only works with SPM projects

---

package-lock.json
package.json
src/ui/ProjectPanelProvider.ts
test/integration-tests/ui/ProjectPanelProvider.test.ts
test/integration-tests/utilities/testutilities.test.ts
test/integration-tests/utilities/testutilities.ts
test/unit-tests/ui/PackageDependencyProvider.test.ts

The project panel should respect the `files.exclude` VS Code setting. This setting is combined with the existing
`swift.excludePathsFromPackageDependencies`.
The tests required an update to `updateSettings`, as the existing global `files.exclude` settings are combined with the ones set in the test. When setting the settings, verify that all expected settings are present before continuing, but don't require the settings object to be an exact match of what we set.

Hide files excluded with `files.exclude` from Project Panel

---

scripts/package.ts
scripts/test_windows.ps1

GitHub keeps changing the builder image out from under us. In this case it looks like they moved it back to the old version we had before.
To try and ease the pain simply pick the highest installed MSVC version.

Pick highest installed MSVC version

---

CHANGELOG.md
package-lock.json
package.json
src/commands.ts
test/integration-tests/commands/dependency.test.ts

Issue happens when a tree item is clicked in the view tree, vscode then sends the last clicked item to the command as context, so just make sure we always ignore the context
Issue: #1660

Make sure context is not provided to the package reset command handler

---

CHANGELOG.md
package-lock.json
package.json
src/commands/captureDiagnostics.ts
test/unit-tests/commands/captureDiagnostics.test.ts

The `captureDiagnostics` command would capture many log files and place them in a temporary folder, then present that folder to the user. The most common use case for capturing diagnostics is to share them, so zip the diagnostics up in to a more easily sharable .zip file.
Adds some tests to flesh out coverage on `captureDiagnostics`.

Capture diagnostics to zip file

---

src/TestExplorer/TestExplorer.ts
src/WorkspaceContext.ts
src/sourcekit-lsp/LanguageClientManager.ts
src/sourcekit-lsp/LanguageClientToolchainCoordinator.ts
test/integration-tests/testexplorer/TestExplorerIntegration.test.ts
test/integration-tests/testexplorer/utilities.ts
test/unit-tests/sourcekit-lsp/LanguageClientManager.test.ts

The LSP client was being created too early, before the imperative set of the `documentSymbolWatcher` on the client. Consequently we weren't making the `textDocument/tests` request when symbols updated in a test file.

Fix test explorer tests not updating on document modification

---

src/TestExplorer/TestDiscovery.ts
src/TestExplorer/TestParsers/SwiftTestingOutputParser.ts
src/TestExplorer/TestRunArguments.ts
src/TestExplorer/TestRunner.ts
test/integration-tests/testexplorer/TestDiscovery.test.ts

Two tests in swift-testing can share the same identifier, for instance if you have two identically named tests with the same name but that take arguments of different types, i.e:
```swift
@Test(arguments: [1]) func a(_ x: Int) {}
@Test(arguments: ["a"]) func a(_ x: String) {}
```
In this case sourcekit-lsp provides a disambiguated id with the filename/line number at the end, i.e. `TestTarget/a:File.swift:2:2`.
The code to synthesize parents in the test explorer when provided with test items that had none didn't take in to account this form of disambiguated id, which lead to these identically named tests being incorrectly synthesized and parented to the wrong test.

Fix improper parenting of tests w/ identical names in explorer

---

CHANGELOG.md
src/FolderContext.ts
src/TestExplorer/TestExplorer.ts
src/WorkspaceContext.ts
src/sourcekit-lsp/LanguageClientManager.ts
test/integration-tests/ExtensionActivation.test.ts
test/integration-tests/commands/runTestMultipleTimes.test.ts
test/integration-tests/testexplorer/TestExplorerIntegration.test.ts

If the user is working in a multi root workspace document symbols would not be provided if they were for any folder except the first one added. This also prevented the test explorer from properly initializing.
Check to see if the folder being added is in the list of VS Code workspace folders and associate the folder with the onDocumentSymbols request from the LSP. 
Issue: #1669

Ensure document symbols are provided for folders in multi root workspaces

---

CHANGELOG.md
src/SwiftPackage.ts
src/ui/ProjectPanelProvider.ts

Issue: https://github.com/swiftlang/vscode-swift/issues/1666
This MR makes a small change to how the `description` property of the dependency `vscode.TreeItem` gets determined. 
- For dependencies using a specific revision it will show the partial **_commit hash_** as the description
- For dependencies that are paths to a local pacakge is will show the _**local**_ keyword
- For dependencies that are edited local versions of a dependency it will show the _**editing**_ keyword
This is not 'new' functionality - `v2.0.2` and earlier of this extension had this functionality.
- Updated the `ResolvedDependency` interface to additionally have the `revision` value
- Added `getDescription` function to `PackageNode` to get the correct description value based on the package type
Additionally I also …

Re-add support for revision hash or local/editing keyword as dependency description

---

test/integration-tests/DiagnosticsManager.test.ts

Due to a change in the swift toolchain, diagnostic style changes are ignored and don't cause a new build so will add unique `-D` options to force a rebuild
Issue: #1680

Fix llvm diagnostics test

---

src/commands/captureDiagnostics.ts
src/utilities/utilities.ts

Cleans up a benign (but scary) warning that states using archiver will crash when called.

Cleanup archiver warning

---

src/tasks/SwiftTaskProvider.ts
test/integration-tests/utilities/testutilities.ts

Tasks are the basic building blocks of most of our features so most tests will not go well if `swift` tasks cannot be provided. I think this failure could be intermittently due to slower activation so will make sure tasks are provided
Issue: #1684

Make sure tasks are available before proceeding with test

---

src/ui/ProjectPanelProvider.ts
test/integration-tests/ui/ProjectPanelProvider.test.ts

The project panel would ignore all files of a given type regardless of if they their value was `true` or `false` in the setting. Only values of `true` should result in files being excluded.

Respect `files.exclude` values set to `false`

---

src/editor/CommentCompletion.ts
test/integration-tests/editor/CommentCompletion.test.ts

The regex was matching on the last encountered `func`. Update it to match the first encountered `func` instead.
Issue: #1694

Fix comment regex not handling params/types/fn names containing `func`

---

src/PackageWatcher.ts

In most cases this file won't exist, and that is OK. Omit the log pollution that prints the error when the .swift-version file can't be found.

Cleanup: Remove log on missing .swift-version file

---

.vscode/settings.json

When developing in this repository if you have the Swift extension installed sourcekit-lsp will begin indexing the test projects in assets/test which can be disruptive when opening the project for the first time.

Disable indexing swift packages in subfolders on this repo

---

src/TestExplorer/TestRunner.ts

This was only clearing in tests but could erroniously mark tests/suites as skipped in production.

Always clear enqueued test state

---

src/editor/CommentCompletion.ts
test/integration-tests/editor/CommentCompletion.test.ts

A comment block may be continued when editing a function declaration. Fix and add a test case.

Fix comment blocks getting incorrectly completed on fn decls

---

src/extension.ts
src/toolchain/toolchain.ts

If the swift binary can't be found log better messages to the Swift output channel for dianosing.

Improve swift not found error logging

---

CHANGELOG.md
assets/test/.vscode/settings.json
assets/test/excluded/Package.swift
assets/test/excluded/Sources/excluded/excluded.swift
package-lock.json
package.json
src/WorkspaceContext.ts
src/configuration.ts
src/sourcekit-lsp/LanguageClientToolchainCoordinator.ts
src/utilities/filesystem.ts
src/utilities/workspace.ts
test/integration-tests/utilities/workspace.test.ts
test/unit-tests/sourcekit-lsp/LanguageClientManager.test.ts
test/unit-tests/utilities/filesystem.test.ts
userdocs/userdocs.docc/Articles/Reference/settings.md

This will make sure the specified folders are not initialized and added to the `WorkspaceContext`. This means no tasks, tests, project panel, etc for these excluded folders, and they are not added to the sourcekit-lsp instance. SourceKit-LSP will still initialize if the an excluded file is open in the editor, an issue against the LS will be raised separately.
Issue: #636

Introduce new `swift.excludePathsFromActivation` setting

---

CHANGELOG.md
package-lock.json
package.json
src/toolchain/swiftly.ts
src/toolchain/toolchain.ts
src/ui/ToolchainSelection.ts
test/unit-tests/toolchain/swiftly.test.ts
test/unit-tests/toolchain/toolchain.test.ts

- Refactored Swiftly code from toolchain.ts to swiftly.ts
- Added list-available with json output
Issue: To be created

Add Swiftly toolchain management

---

CHANGELOG.md
src/TestExplorer/TestRunner.ts
test/integration-tests/testexplorer/utilities.ts

Refactor the enqueued tests list to be a Set so we can clear enqueued tests without the need to potentially traverse the full remaining list of enqueued tests.
Also avoid recreating the test item finder on every `get testItemFinder`, and store test items in the darwin test item finder in a Set as well for faster lookup.
Issue: #1728

Optimize clearing enqueued tests

---

package.json
src/WorkspaceContext.ts
src/commands/generateSourcekitConfiguration.ts
src/configuration.ts
src/extension.ts
test/integration-tests/commands/generateSourcekitConfiguration.test.ts

This change will notify users when they open their .sourcekit-lsp/config.json file if the $schema property does not exist or if the value does not match the latest computed schema URL. There is a setting that disables this check and it is set if they click the "Don't Ask Again" button
Issue: #1208

Notify user if configured $schema is out of date

---

CHANGELOG.md
package.json
src/TestExplorer/TestRunner.ts
src/configuration.ts

When running a large test suite full of tests that complete very quickly, VS Code spends a lot of time updating the test explorer UI. For every test the tree is refreshed, and in a suite where thousands of tests complete very quickly this can make the UI unresponsive and increase the amount of time the test run takes.
The UI updates because the duration of the test item is different between runs, requiring the UI to change. As in the case described above, omitting the duration when passing or failing test items significantly improves performance.
Introduce the `swift.recordTestDuration` setting which, when set to false, will omit the duration when recording test results. The default is `true`, making this optimization opt-in.
This intended use is to opt out of duration recording on a …

Add `swift.recordTestDuration` setting

---

src/commands.ts
src/extension.ts
src/toolchain/swiftly.ts
src/toolchain/toolchain.ts
src/ui/ToolchainSelection.ts
test/unit-tests/toolchain/swiftly.test.ts

In the swiftly toolchain version schema, there was a missing `name` attribute, which prevented it from parsing the value. In this fix, I have removed the `name` field from the top-level and added it at the object level. 
Issue: https://github.com/swiftlang/vscode-swift/issues/1739

Fixed JSON parsing error while selecting toolchain

---

package.json
scripts/download_vsix.ts

Bump release version number
Issue: N/A

Bump version to 2.10

---

CHANGELOG.md
assets/test/defaultPackage/Package.swift
assets/test/defaultPackage/Package@swift-6.0.swift
package.json
src/SwiftPackage.ts
src/configuration.ts
src/tasks/SwiftTaskProvider.ts
test/integration-tests/tasks/SwiftTaskProvider.test.ts
userdocs/userdocs.docc/Articles/Features/automatic-task-creation.md

Introduce a new `swift.createTasksForLibraryProducts` setting that is false by default, but when enabled causes the extension to automatically create and provide tasks for library products. Any automatic library products will still be ignored as they'd just result in a warning:
```
warning: '--product' cannot be used with the automatic product 'PackageLib'; building the default target instead
```
Issue: #1646

Optionally provide build tasks for library products

---

src/sourcekit-lsp/LanguageClientConfiguration.ts

Companion of https://github.com/swiftlang/sourcekit-lsp/pull/2204

When running against SourceKit-LSP 6.3, use a dictionary to communicate experimental client capabilities

---

src/TestExplorer/TestRunArguments.ts
test/integration-tests/testexplorer/TestRunArguments.test.ts

VS Code provides commands like `Tests: Run Tests` that can be executed before we have a list of tests from the LSP. When we receive an empty `TestRunRequest` today we gather up all the tests we know about and run those by creating the appropriate `--filter` arguments to pass to `swift test`.
To ensure we run all the tests whether the LSP has informed us of them or not, run `swift test` with no filter when we recieve an empty `vscode.TestRunRequest`.
Issue: #1764

Run all tests when none are specified in TestRunRequest

---

.vscode-test.js

The `Extension Tests` launch config stopped working because the vscode-test.js prints console output, which VS Code now wants to interpret as JSON configuration. Only log when we're building in CI.

Fix running Extension Tests from VS Code

---

CHANGELOG.md
scripts/lib/utilities.ts
scripts/preview_package.ts

Recent changes to the packaging commands accidentally removed the `--pre-release` flag from our invocation of `vsce` for the `preview-package` script. This means that we accidentally released 2.11.20250806 as an official release rather than a pre-release.
This PR adds back the `--pre-release` flag and adds 2.11.20250806 to the `CHANGELOG` as an official release.

Add `--pre-release` flag back to preview-package script

---

src/TestExplorer/TestRunner.ts
src/commands/testMultipleTimes.ts
src/debugger/logTracker.ts

When the user terminates the debugger using the red Stop icon and we're mid-run of a Debug Multple Times or Debug Until Failure command we should not execute the remaining iterations.
Issue: #1747

Cancel run multiple session when debugger is terminated

---

test/unit-tests/testexplorer/TestCodeLensProvider.test.ts

TestCodeLensProvider did not have very good test coverage. Add unit tests.

Add unit tests for TestCodeLensProvider

---

CHANGELOG.md
src/TestExplorer/TestRunner.ts

Similar to #1790, if your debugging all tests in a project with a mix of XCTest and swift-testing suites, if the user stops a debug session for the swift-testing tests, then the XCTest debug session should not then startup
Issue: #1002

Don't debug further tests when stopping the debug session

---

src/TestExplorer/TestRunner.ts

When we cancel a debug run, the remaining tests are marked as skipped instead of as failed. Follow this same logic for regular non-debug test runs to be consistent.
Issue: #1002

Skip remaining tests when cancelling a regular run

---

src/configuration.ts
src/sourcekit-lsp/LanguageClientConfiguration.ts
test/unit-tests/sourcekit-lsp/LanguageClientManager.test.ts

We're working on implementing signature help in SourceKit-LSP (https://github.com/swiftlang/sourcekit-lsp/pull/2250) and we faced a problem in VS Code where signature help wasn't triggered after accepting a completion item for a function, method, subscript, initializer, or enum case with associated values that would've normally had signature help if the user manually typed the `(` after the signature name.
Here's a demo of the issue with a development version of SourceKit-LSP:
https://github.com/user-attachments/assets/d44f2a95-ca78-40e7-a44f-b5a09ec61d58
To fix this, we added a `provideCompletionItem` middleware that inspects completion items that might have signature help (functions, methods (includes subscripts), initializers, and enum cases) and injects an …

Trigger parameter hints on accepting a function-like completion item

---

src/commands/installSwiftlyToolchain.ts
src/toolchain/swiftly.ts
test/unit-tests/toolchain/swiftly.test.ts

Add the branch parameter functionality (main-snapshot) for installing swiftly toolchains snapshot from quickPick
Issue: 1778
Reference: https://github.com/swiftlang/vscode-swift/pull/1780#discussion_r2304450969

Add support for selecting Swift snapshot branch for toolchain installation

---

src/sourcekit-lsp/LanguageClientConfiguration.ts
src/sourcekit-lsp/extensions/PeekDocumentsRequest.ts
src/sourcekit-lsp/peekDocuments.ts

This allows the peek window to scroll to a position within the peeked document.

Accept `Location` for `workspace/peekDocument`

---

CHANGELOG.md
src/commands/testMultipleTimes.ts
test/integration-tests/testexplorer/TestExplorerIntegration.test.ts
test/unit-tests/commands/runTestMultipleTimes.test.ts

When we process the `...args` passed to the 'run multiple' commands we're only checking if the argument is an object before deeming it a TestItem.
On linux VS Code is passing an event object like `{ preserveFocus: true }`, which is being treated as a TestItem and causing the command to error out.

Fix "Run Tests Multiple Times" on Linux

---

test/unit-tests/ui/ToolchainSelection.test.ts

The `should show open dialog for folder selection` test would write the selected toolchain value into settings. This would break the integration tests if you ran them after the unit tests because the location of `swift` would be incorrect.

Mock settings writes in ToolchainSelection tests

---

.mocha-reporter.js
.vscode-test.js
package-lock.json
package.json
test/integration-tests/ExtensionActivation.test.ts
test/integration-tests/commands/captureDiagnostics.test.ts
test/integration-tests/tasks/SwiftPluginTaskProvider.test.ts
test/integration-tests/tasks/SwiftTaskProvider.test.ts
test/integration-tests/tasks/TaskManager.test.ts
test/integration-tests/tasks/TaskQueue.test.ts
test/integration-tests/utilities/testutilities.ts
test/reporters/GitHubActionsSummaryReporter.ts

Timeouts were being disabled in our nightly suits accidentally because `isDebugRun` was being set to true. This PR makes sure that `isDebugRun` is always false when running in CI and adjusts timeouts for various setup hooks and tests.
Additionally, GitHub Actions supports providing a test summary by writing to the file in the environment variable `GITHUB_STEP_SUMMARY`. Our tests will now write a test summary to this file so that we can easily see what failed without having to scroll through the output of each job.
- ~[ ] Documentation has been updated~
- ~[ ] Added an entry to CHANGELOG.md if applicable~

Fix timeouts for tests and add a test summary to CI jobs

---

src/WorkspaceContext.ts
src/utilities/workspace.ts
test/integration-tests/utilities/workspace.test.ts
test/unit-tests/utilities/workspace.test.ts

Describe your changes clearly and use examples if possible
Issue: 
* #1791 
more detail check inside the issue

fixed bsp config file location issue

---

src/TestExplorer/TestParsers/SwiftTestingOutputParser.ts

With the introduction of issue severity, the issue payload contains the flag `isFailure`. If this is false, we were assuming that the issue didn't meet the severity threshold.
However if an issue is skipped with `withKnownIssue`, `isFailure` would be false but `isKnown` is true. In this case we still want to record the issue and have the test be marked as skipped.

Fix withKnownIssue not marking test as skipped in nightly toolchains

---

.github/workflows/nightly.yml

6.2 is latest stable release now
Issue: Please provide reference link to the Github issue

Drop 6.1 from Insiders nightly test matrix

---

CHANGELOG.md
src/commands/captureDiagnostics.ts

- Fix the regex which only worked for a single digit
- Make the progress notification increment to show bar fill up
Issue: #1799

Fix sourcekit-lsp diagnostics counter

---

test/integration-tests/tasks/SwiftTaskProvider.test.ts
test/integration-tests/utilities/testutilities.ts

Some tests that run the build all command are timing out during setup on Windows (and more specifically Swift 6.0). Adjusted the timeout to 3 minutes to give them plenty of time to finish.
Tagged a couple of the SwiftTaskProvider tests as `"medium"` as well since they failed a couple times on the 2 second timeouot.
- ~[ ] Documentation has been updated~
- ~[ ] Added an entry to CHANGELOG.md if applicable~

Adjust timeouts to resolve Windows test failures

---

src/commands/installSwiftlyToolchain.ts
src/toolchain/swiftly.ts
src/ui/ToolchainSelection.ts
test/unit-tests/toolchain/swiftly.test.ts

If a .swift-version exists in a project that specifies a toolchain the user doesn't have installed, prompt them to install it on extension launch.
If they cancel the dialog, fall back to using whatever toolchain is already installed, basically ignoring the .swift-version for this activation or until the .swift-version is changed again.
Issue: #1852

Prompt to automatically install missing toolchain

---

CHANGELOG.md
src/debugger/buildConfig.ts
src/toolchain/BuildFlags.ts
test/unit-tests/debugger/buildConfig.test.ts

When debugging tests we were appending `additionalTestArgs` to the build invocation. If the user has any incompatible flags that work for `swift test` but not `swift build`, this invocation will fail (i.e. `--no-parallel`).
Filter down `additionalTestArgs` when performing the build to only `swift build` compatible arguments. All `additionalTestArgs` are still passed to the executable when tests are run.
Issue: #1863

Filter out incompatible additionalTestArgs when building tests for debugging

---

src/commands.ts
src/commands/installSwiftlyToolchain.ts
src/toolchain/swiftly.ts
src/ui/ToolchainSelection.ts
test/unit-tests/toolchain/swiftly.test.ts

The `--use` argument for `Swiftly install` doesn't seem to have a good way of telling Swiftly to install as a global default toolchain. Instead of this, we will simply do a `swiftly use` after the install, asking the user where they want to use the new toolchain (workspace vs global). This also means that `installSwiftlyToolchainWithProgress()` no longer needs to show the reload message since installation no longer does a `use` by default.
- ~[ ] Documentation has been updated~
- ~[ ] Added an entry to CHANGELOG.md if applicable~

Ask where to use newly installed Swiftly toolchain

---

src/toolchain/swiftly.ts
src/utilities/filesystem.ts
test/unit-tests/toolchain/swiftly.test.ts

Some instances of Swiftly do not actually create the `.swift-version` file when `swiftly use` is called. They will only modify an existing `.swift-version` file. This is definitely an issue with Swiftly itself, but we can at least mitigate the problem in the Swift extension until we can determine a proper fix.
- ~[ ] Documentation has been updated~
- ~[ ] Added an entry to CHANGELOG.md if applicable~

Ensure that the .swift-version file exists before calling `swiftly use`

---

src/FolderContext.ts
src/WorkspaceContext.ts

When a duplicate folder context is created in a test this typically indicates the test is set up incorrectly. Capture the stack trace at the time of creation, and then log it when a duplicate folder is created.

Log FolderContext creation stack
